### ISSUE TITLE
App takes longer to start up

### ISSUE THREAD

**Issue by yephny** [recloudstream/cloudstream#10]
Is there a check the app does that possibly fails, resulting in a slower start-up? This became noticable in the last two days. I have Cloudstream 3.1.2, Beta 3.0.0, and Debug 3.1.2 installed, they all take about 10 seconds each.

**Comment by yephny** [comment]
It's fixed, somehow.

**Comment by C10udburst** [comment]
probably d91446c65471f2dd9bd74bd59e413961690f5dca
