### ISSUE TITLE
Add sort by release date in watchlist

### ISSUE THREAD

**Issue by Johnny5sword** [recloudstream/cloudstream#103]
### Describe your suggested feature

The watchlist I'm referring to are the categories in the home tab such as watching, plan to watch, etc.

It would be useful for someone who tends to start watching from the earliest media or even view the latest without researching the release dates one by one.  

### Other details

Sample UI implementation in [TachiJ2K manga app](https://github.com/Jays2Kings/tachiyomiJ2K)

https://user-images.githubusercontent.com/112535244/189621797-ad2c102c-52ac-4772-bf0b-9d3712093eb4.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
I anticipated this when making bookmarks, so I already store the date, but I have not made the logic or UI for it yet

**Comment by MudssirAhmed** [comment]
@LagradOst and @C10udburst I want to help in this issue, You can assign it to me, I'm to excited to dive in this project.

**Comment by C10udburst** [comment]
> I want to help in this issue, You can assign it to me, I'm to excited to dive in this project.

Sure, but you know that you don't need to be assigned to do a pull request, right?

**Comment by MudssirAhmed** [comment]
Yes I know this, but I think assigning provides more significance than first PR that's why I was ask you.

**Comment by MudssirAhmed** [comment]
https://user-images.githubusercontent.com/56527355/216056854-8736a8ed-b09e-4966-ab6b-97d01395628d.mp4

@Johnny5sword Can you help me to figure out the issue, Actually I'm getting only two sort metrics.

**Comment by MonuGit9** [comment]
Can you assign this task to me
