### ISSUE TITLE
'Load from Online' subtitles doesn't work 

### ISSUE THREAD

**Issue by Virohi** [recloudstream/cloudstream#1045]
### Steps to reproduce

In any media , when there is no substitle by site extraction, cloudstream have a feature to get substitle from internet via 'opensubstitle' but it doesn't work.

### Expected behavior

![Screenshot_2024-04-16-17-39-30-363_com lagradost cloudstream3](https://github.com/recloudstream/cloudstream/assets/167200142/72a0e155-b23c-4f27-8285-c4aa242a2405)

### Actual behavior

It only shows blank screen and none of substitle are fetched from opensubstitle website.
Similar options is there in VLC media player which works. 
So kindly check what the issue in opensubstitle api in cloudstream that it cannot show substitle from online.

### Cloudstream version and commit hash

4.3.0

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Works on pre. Update to pre
