### ISSUE TITLE
Note taking feature on the player

### ISSUE THREAD

**Issue by AnyoneMouse** [recloudstream/cloudstream#1052]
### Describe your suggested feature

There should be a button to add note on the player. I always log whatever I watch on different sites, apps. So, I like to add reviews as well sometimes. But while watching on the app I'll have to leave the app and open another app to take notes on what I think.

### Other details

If it is implemented the note should be on the player only. Not all the contents I watch should have notes. Sorry if I'm not clear enough. I would like to discuss if needed to make it clear.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Note taking is beyond the scope of the app. I recommend a physical paper or some note app which supports opening in an overlay window. Some ROMS even support making every app an overlay.
