### ISSUE TITLE
Compatibility with IMDB. 

### ISSUE THREAD

**Issue by Zain3967** [recloudstream/cloudstream#1057]
### Describe your suggested feature

Please add the feature to sync your IMDB account with CloudSteram.
This would improve the app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
AFAIK IMDB has not OAuth2 or similar api login for us to use, so it is impossible.
