### ISSUE TITLE
Issue in Navigating to delete icon or option Movie or file from Download section in CS

### ISSUE THREAD

**Issue by phisher98** [recloudstream/cloudstream#1059]
### Steps to reproduce

Download any Movie or Ep on Firstick or TV and Then go to Download and i was not able to navigate to Phone icon which is used to delete the File from CS

### Expected behavior

Navigation to Phone icon in download and select delete option

### Actual behavior

Not navigating to Option or icon to choose options

### Cloudstream version and commit hash

e6b9d62

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by phisher98** [comment]
![image](https://github.com/recloudstream/cloudstream/assets/153359846/dd9e567e-f5f1-42c9-99ba-778f7f2df144)

**Comment by KingLucius** [comment]
I will fix it
