### ISSUE TITLE
"Search globally" button when no results in saved shows

### ISSUE THREAD

**Issue by wsu808** [recloudstream/cloudstream#106]
### Describe your suggested feature

**Actual Behavior:**  
When searching from search box on "Home" tab only results from my library are being shown.

**Suggested Behavior:**  
When searching from "Home" tab "Search globally" button is shown at the top (especially when there is no search results from saved shows)

I found it very convinient and intuitive in other apps. Once you type your search query you don't have to type in again but you are automatically switched from "Home" to "Search" tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
This is the intended UX voted on by server
