### ISSUE TITLE
Navigation bar disappears when pressing options button

### ISSUE THREAD

**Issue by NicholasWahome** [recloudstream/cloudstream#1068]
### Steps to reproduce

1. Navigate to search page by pressing on the search button at the bottom of the lower navigation bar.
2. Press on the search bar option button at the top right
3. The lower navigation bar will then disappear.

### Expected behavior

<img width="322" alt="Screenshot 2024-03-22 at 10 58 14 PM" src="https://github.com/SOEN345-WINTER2024/discussion/assets/87381233/7d89fb73-a551-47d6-ab57-a739b2aa3316">

### Actual behavior

<img width="322" alt="Screenshot 2024-03-22 at 10 58 22 PM" src="https://github.com/SOEN345-WINTER2024/discussion/assets/87381233/809e73af-504b-4498-9742-d40f10ce2e89">

### Cloudstream version and commit hash

latest

### Android version

Device Information: PIXEL 6 API 34 (used emulator) Version of app: 4.3.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
It looks like you dont have any sources installed/or has no preferred media. I will be closing this for now as I suspect that is the case, if it is not then reopen it.
