### ISSUE TITLE
Add Feature Migrate series

### ISSUE THREAD

**Issue by WEPOXS** [recloudstream/cloudstream#1077]
### Describe your suggested feature

![Screenshot_20240507_024618_CloudStream](https://github.com/recloudstream/cloudstream/assets/146017577/205b64a1-6700-4532-83fe-6d8167ede90d)

when an extension changes url it will always be like this, and I suggest there is a migrate feature, for example there is a series like this I just have to search for it with 1 button 

example : 
![Screenshot_20240507_024912_Mihon](https://github.com/recloudstream/cloudstream/assets/146017577/4241a193-ed73-4bbb-8d81-83ccb77280d3)
![Screenshot_20240507_024925_Mihon](https://github.com/recloudstream/cloudstream/assets/146017577/c0dd6151-f7ae-403c-aa80-bd43e23dcda4)
![Screenshot_20240507_024930_Mihon](https://github.com/recloudstream/cloudstream/assets/146017577/fa4172bc-d2e7-4d27-b27d-aae702c425d2)

Sourch: mihon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by JimZiii** [comment]
If you open your library you can select what you it to open with and if you choose search and tap a movie/series it will search for it across all extensions, making it really easy to migrate to another extension

**Comment by WEPOXS** [comment]
> If you open your library you can select what you it to open with and if you choose search and tap a movie/series it will search for it across all extensions, making it really easy to migrate to another extension

but for example, extensions change domains and the entry can't be opened, how do I migrate serial? 

![Screenshot_20240521_160848_CloudStream.jpg](https://github.com/recloudstream/cloudstream/assets/146017577/2df8a7d0-d76c-4181-9a30-61cbfc02202d)

Like this, the domain is change
Before change is "samehadaku.vin"
After change is a "samehadaku.email"

**Comment by JimZiii** [comment]
The minutes you've watched something isn't migrated in aniyomi either, it only migrates the episodes you've watched, so just check which episode you're at and when you've added the new extension start the last episode and fast forward to the end to have it marked as played.

I recently "migrated" a ton of movies and series i had bookmarked on old dead versions of sflix and superstream to sora, and i did it this way.
If you'd rather wait for a full migrate feature that might never come, go ahead

**Comment by WEPOXS** [comment]
> The minutes you've watched something isn't migrated in aniyomi either, it only migrates the last episode you've watched, so just check which episode you're at and when you've added the new extension start the last episode and fast forward to the end to have it marked as played.
> 
> I recently "migrated" a ton of movies and series i had bookmarked on old dead versions of sflix and superstream to sora, and i did it this way.
> If you'd rather wait for a full migrate feature that might never come, go ahead

Yeah, maybe I will use the sisync feature to mark anime that I have watched 

Thank you very much for your mention
