### ISSUE TITLE
Continue watching bug.

### ISSUE THREAD

**Issue by HASNAINGAMERYT** [recloudstream/cloudstream#1078]
### Steps to reproduce

Using MyFlixier as a alternative of Sflix. But idk why it doesn't mention other movies or things I watch on the "continue watching" it always only adds the recent one.  Same thing with the tags "watching, plan to watch, Completed" for example, if I watch 2 movies, and not complete it, it will only show the recent one, not the one I watched before, in the "continue watching"

### Expected behavior

![Screenshot_20240508-073236](https://github.com/recloudstream/cloudstream/assets/30818465/da36ccda-a503-4f74-bc72-3b448244ea57)

### Actual behavior

Same thing as expected behavior.

### Cloudstream version and commit hash

4.3.0 3c152e04

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is an issue with the MyFlixier extention, report this to the owner of that extention and say that they dont provide the correct url to the series as the Id is calculated from the url https://github.com/recloudstream/cloudstream/blob/4d5cd288abd07c74fc88900c58e119c27f1b7867/app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt#L114
