### ISSUE TITLE
Request To Add New Repositories

### ISSUE THREAD

**Issue by FUSIONOF** [recloudstream/cloudstream#1079]
### Describe your suggested feature

You Have Many Repositories I Know But None Of Them Provide Atleast Fine Quality To Watch Movies Etc,Before I Used To Use CloudStream Now It Is Available Sometime Or Sometimes Not Not Even Single Please Add New Repositories Because Of That I Now Use Stemio App To Watch Movues In High Quality With MediaFusion Add-ons,I Suggest You To Make MediaFusion,Peario,Shluflix Add-on A Repository As They Are Open Source And Free Or Any Other Thing You Like Or You Can Do To Provide New Repositories Then Please Do It Because It Is A Very Needy Issue For Regular Users Like Me Of Your App That Has Better UI Than Any Other Apps.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by FUSIONOF** [comment]
> This is cloudstream APP development we do not make plugins We do not support piracy

So Where Can I Request It?Please Tell Me.

**Comment by fire-light42** [comment]
This is just the app repo, not the repo for extentions.
