### ISSUE TITLE
Subscene is DOWN, Suggesting a new replacement source of subtitles 

### ISSUE THREAD

**Issue by xeednem** [recloudstream/cloudstream#1080]
### Describe your suggested feature

as you know all cloud stream is using the website subscene as source for the online subtitles but since the subscene is down forever, there's a new replacement source for subtitles called SUBDL.COM  and you should know that all the database of subscene has been copied to that new website and also offers a free API.
i hope the developers see that suggestion and do something about it ASAP.
THANK YOU 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
Already done, will be pushed soon
