### ISSUE TITLE
Site request 

### ISSUE THREAD

**Issue by Jwjshhi** [recloudstream/cloudstream#1083]
### Describe your suggested feature

https://watch-wrestling.eu/
 This site has wrestling and mma replays
That are uploaded on Dailymotion or other servers.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by adilurrhmn** [comment]
Mkvcinemas
