### ISSUE TITLE
Movie search option is not working properly.

### ISSUE THREAD

**Issue by Rinhak** [recloudstream/cloudstream#1087]
### Steps to reproduce

1. Take any source (Superstream for example) and search for a movie in it 
2. Constantly shows a blank screen no matter what.
3. Can't search a movie we want to watch.

### Expected behavior

When you put a movie name you would expect the movie to come on screen. But it shows a blank screen no matter how much you search for it.

### Actual behavior

Shows a blank screen everytime you search for a movie.

### Cloudstream version and commit hash

4.3.2 ee4d1de

### Android version

Android 14

### Other details

![Screenshot_20240513_063643_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/99042103/1167ff84-998a-4965-8379-47c361bc458b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
Extension issue

**Comment by C10udburst** [comment]
Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the [discord](https://discord.gg/5Hus6fM).
