### ISSUE TITLE
New Site Request 

### ISSUE THREAD

**Issue by yuvarajbe** [recloudstream/cloudstream#1088]
### Describe your suggested feature

https://www.tamildhool.net

This one has all the tamil shows same time when they get released on ott platforms 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Leokiii** [comment]
Can you please add these two websites in CloudStream one is for series of all kinds https://burning-series.io/
And the other one for animes https://www.anime-loads.org/
Both sides are German
