### ISSUE TITLE
Choose different download source

### ISSUE THREAD

**Issue by Gissyup4** [recloudstream/cloudstream#109]
### Describe your suggested feature

Whenever you choose to download, the app preselects a source. This is often a source that has the highest quality video. While this is nice for most, it's bad if you have a metered data connection and you'll end up wasting 1GB+ of data to watch something that you could've seen using 200MB or less.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KillerDogeEmpire** [comment]
Hold on the video you want to download and select download mirrors

**Comment by Gissyup4** [comment]
> Hold on the video you want to download and select download mirrors

I see it now. Thanks alot
