### ISSUE TITLE
Feature To Select The Quality And Download Complete Series.

### ISSUE THREAD

**Issue by Zain3967** [recloudstream/cloudstream#1094]
### Describe your suggested feature

There should be a separate option to select and download the number of episodes in series or completely download the series. This option will greatly improve the app. And also an option to select the quality of the series or movie that is to be downloaded. I hope you will consider these suggestions suitable for the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Hold to select download quality, batch download is duplicate

**Comment by ShadowWalkerM** [comment]
> Hold to select download quality, batch download is duplicate

He bro i hold the download button and showed loading bottom of the screen and eventually it disappear without doing anything no popup menu to select quality or anything related to menu to select and im using red icon app
