### ISSUE TITLE
Please Add Hollywood extension to sorastream 

### ISSUE THREAD

**Issue by BoakyeDarlington** [recloudstream/cloudstream#1104]
### Describe your suggested feature

In sorastream I can select different streaming sources like Netflix, Disney, paramount, hulu and more. Can you please add Hollywood source too select. Just like Netflix you decide to switch to Hollywood movies. I watch Nigerian movies a lot. Cloudstream.... 😍 Life is simple

### Other details

This is a feature request in the sorastream extention. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Please do not talk about extensions in this repo as it only tracks issues regarding the app itself.
