### ISSUE TITLE
FaselHD not working

### ISSUE THREAD

**Issue by Kygojoe** [recloudstream/cloudstream#1108]
### Steps to reproduce

لماذا فاصل اعلاني لا يشتغل في التحديث الجديد

### Expected behavior

ارجو منكم معالجة المشكلة

### Actual behavior

شكرا

### Cloudstream version and commit hash

4.3.0

### Android version

14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Kygojoe** [comment]
FaselHD repository is not working on 4.3.0 update

**Comment by phisher98** [comment]
@Kygojoe  Its not an CS App Issue create a Issue on Plugin Maker Github Repo

**Comment by C10udburst** [comment]
Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the [discord](https://discord.gg/5Hus6fM).
