### ISSUE TITLE
Subtitle icons not parsing

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#1109]
### Steps to reproduce

Find a video with Hearing Impaired default subtitles

### Expected behavior

Icon to display properly

### Actual behavior

![Screenshot_20240530_054310_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/142361265/41e5d6ce-5390-4a17-9aa2-c3fae376495d)

### Cloudstream version and commit hash

4.3.2 dff5602

### Android version

Android 14

### Other details

I noticed this after updating to dff5602 and logging into SubDL account. I am not sure if it happened before but I assumed it had something to do with that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
Can you elaborate, where this screenshot appears?
As for SubDL it is totally via api and no scraping at all and the screenshots shows html, so I doubt it's something related but no harm to double-check

**Comment by Luna712** [comment]
It doesn't happen when searching online subtitles only the auto subtitles though.

**Comment by KingLucius** [comment]
So it's for sure one of sub providers of SS

**Comment by Luna712** [comment]
> So it's for sure one of sub providers of SS

@KingLucius

I think this has to do with opensubtitles, if you search subtitles on opensubtitles.com you get icons in there also like the fa-check which means "Subtitles from trusted source"

I think CloudStream needs to handle parsing this HTML properly. Probably stripping the check marks but could probably replacing the hearing impaired HTML icon with the icon used in CloudStream within subtitles search.

Looks like the same type of icon would also happen with SubDL and *maybe* addic7ed as well but I'm unsure if those even supports auto subtitles.

Also on another note, SubDL seems unreliable a bit, if you open subtitles on SubDL it shows a lot more then when you Search Online Subtitles from within CloudStream, it seems to omit any with Hearing Impaired at all and others (maybe omitting HI is just a coincidence but it seems only about 5% that actually exist in SubDL properly show up when searching in CloudStream)

**Comment by Luna712** [comment]
Wait I'm just now learning how subtitles even work. This potentially isn't even a CS issue but rather extension issue. I'm unsure. If it is I apologize.

**Comment by KingLucius** [comment]
You are right, SubDL api has an filtering issue
It feeds only the non hearing impaired subtitles
Reported to main dev there

**Comment by janowakps** [comment]
this issue still exists in the latest version 
![Screenshot_20240727-233213](https://github.com/user-attachments/assets/85cba497-7e69-4bac-89ec-14e6b2ff5993)

**Comment by KingLucius** [comment]
> this issue still exists in the latest version ![Screenshot_20240727-233213](https://private-user-images.githubusercontent.com/36198623/352778125-85cba497-7e69-4bac-89ec-14e6b2ff5993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNDkxODIsIm5iZiI6MTcyMjE0ODg4MiwicGF0aCI6Ii8zNjE5ODYyMy8zNTI3NzgxMjUtODVjYmE0OTctN2U2OS00YmFjLTg5ZWMtMTRlNmIyZmY1OTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA2NDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMTZlZWU2M2UwZDQ4NTFmMDM5NjU4ZWY2OTQ2OTExYjAwODI2MWJlMjlmMzI0ZDY2MmJiMDIzMTE1MTA0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oYtqReRwlbJYg6ueUdh90I6UQOq46bJFLDE_cZ8obHc)

Provider issue not app issue

**Comment by C10udburst** [comment]
extension issue

**Comment by elvistony** [comment]
Can we have a Regular expression to remove out the HTML part of the list items?
