### ISSUE TITLE
Ability to aggregate data from all the sources 

### ISSUE THREAD

**Issue by hexclann** [recloudstream/cloudstream#111]
### Describe your suggested feature

Selecting only one source will severely limit the content. Is it possible to get the contents from all the sources? This will be very helpful in situation when ISP blocks certain sources. Aggregating data from all the sources will also help in discovering more content.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gerrtuy** [comment]
لا وجود للاضافات الموقع متوقف !!

**Comment by LagradOst** [comment]
no, that is not how this app works, check out sunstream for another implementation using many sources

**Comment by hexclann** [comment]
@LagradOst thanks for the update. Are you referring to https://codeberg.org/QzReborn/SunStream? Do you have an alternate source for the apk!
