### ISSUE TITLE
Progress bar on a movie/shows title page is broken on android tv

### ISSUE THREAD

**Issue by JimZiii** [recloudstream/cloudstream#1113]
### Steps to reproduce

1. Start playing something
2. Go back to the page for the movie/show
3. Check progress bar

### Expected behavior

Should only display color of progress from left to right

### Actual behavior

Progress bar always shows a sliver of color on the far right side and where the progress color ends there's now ablack gap, splitting the progress bar into two bars

### Cloudstream version and commit hash

4.3.2 b3e3dad

### Android version

Android 11

### Other details

![Screenshot_20240603_074958_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/7854537/86138428-930f-4a84-a95e-fa4acff429ea)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
That's the new M3 design of the linearprogressindicator

**Comment by JimZiii** [comment]
@KingLucius that tiny sliver on the far right side made me think it was a bug but i googled the m3 design and it's apparently supposed to be there..
