### ISSUE TITLE
Swipe Right To Go Back Gesture

### ISSUE THREAD

**Issue by Alotheoner** [recloudstream/cloudstream#1129]
### Describe your suggested feature

To improve the quality-of-life in cloudstream, I suggest adding swipe right to go back gesture when on a selected entry. This gesture is similar to the swiping left gesture that displays similar shows that is represented by the icon in the pic below. One of the pictures is from another app; Infinity for Reddit settings.
![Screenshot 2024-06-10 2 10 48 PM](https://github.com/recloudstream/cloudstream/assets/120232276/bdee2f77-7b99-40e4-bf8a-585bf2ff4440)
![Screenshot 2024-06-10 2 24 00 PM](https://github.com/recloudstream/cloudstream/assets/120232276/27f10707-af94-42be-b2f8-be03e0539013)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
You can do this if you use swipe gesture navigation in your device, but I don't think this should be explicitly added to the app or it would conflict with Simkl as swiping to the right opens Simkl side panel if you are logged into it. That would make that design a lot harder to navigate with randomly potentially unexpected behavior. Furthermore, my opinion on the app implementation swipe to go back stuff is it is more for things like Chrome and other direct web browsing and I don't necessarily feel it even fits to much into CloudStream. But that's just my personal opinion of it.

**Comment by fire-light42** [comment]
Luna712 summed it up quite nicely.
