### ISSUE TITLE
Subtitles doesnt appear on cast

### ISSUE THREAD

**Issue by warrenlayson** [recloudstream/cloudstream#113]
### Steps to reproduce

1. Select movie 
2. Cast selected movie
3. See if subtitles appears

### Expected behavior

The subtitle should appear when casting a movie. 

### Actual behavior

Tje subtitle doesn't appear when casting the movie

### Cloudstream version and commit hash

3.1.5 9402a28

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Chromecast supports barely any subtitle formats (https://developers.google.com/cast/docs/media#subtitles_and_closed_captions)

This makes subtitles fail on superstream since they only use SRT :skull:

**Comment by warrenlayson** [comment]
That sucks, it's an issue with subtitle formats. Thanks!
