### ISSUE TITLE
Cannot download online subtitles **only in Android TV**

### ISSUE THREAD

**Issue by thanasistrisp** [recloudstream/cloudstream#114]
### Steps to reproduce

1. Stream the movie
2. I have already signed in to opensubtitles.com account successfully
3. I choose “Download online subtitles” and nothing happens. It does not open a window

### Expected behavior

In android phone (Samsung) it works perfectly.

### Actual behavior

I choose “Download online subtitles” and nothing happens. It does not open a window.
Also, open subtitle file does not work, even I have installed Amaze File Manager, ES Explorer. I do not know if Android TV supports [SAF](https://developer.android.com/guide/topics/providers/document-provider) as in my mobile it opens SAF and I do not know if it related with the download online which should not use SAF.

### Cloudstream version and commit hash

3.1.5 9bbe3d6

### Android version

Android 10

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
See if this is fixed in latest pre release

**Comment by Blatzar** [comment]
This should be fixed now https://github.com/recloudstream/cloudstream/commit/1e83d21db469fa68c3edad836b197093cf005dd3

**Comment by Blatzar** [comment]
That's not the issue. You simply lack a file manager, download a handful on play store and one ought to work.

**Comment by Blatzar** [comment]
Thats why I said a handful, some might not work. People with the same issues as you have solved it by simply finding a working file manager.

> Should I make any specific setting?

Not afaik

**Comment by ShareASmile** [comment]
You can also try Material Files file manager available on fdroid store

https://f-droid.org/packages/me.zhanghai.android.files
