### ISSUE TITLE
M3U in Cloudstream 

### ISSUE THREAD

**Issue by Moviellect** [recloudstream/cloudstream#1147]
### Describe your suggested feature

Please add an option in Cloudstream to add **m3u** _file_ and _url_ .

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by keyiflerolsun** [comment]
You can clone my plugin by creating your own m3u8 list ; https://t.me/KekikAkademi/1756
