### ISSUE TITLE
Add a subtitle site subsorce : an alternative to subscine

### ISSUE THREAD

**Issue by OtakuArab** [recloudstream/cloudstream#1148]
### Describe your suggested feature

The Subscine translation website was closed and came back with a new name called Subsource 
Website link :
https://subsource.net

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
Subscene database already in SubDL which is supported in CS

Subsource has no documented API but I will work on supporting it.

Accepted

**Comment by OtakuArab** [comment]
> Subscene database already in SubDL which is supported in CS
> 
> Subsource has no documented API but I will work on supporting it.
> 
> Accepted

This is their advertisement. They have recovered 95% of subscine translations

✅ Missing subtitles are back!

💎 It is a great honor to announce that we’ve been able to recover more than 95% of the subtitles from subscene database (Animes, K-Drama and other.) Users should be able to find the recovered subs in their profiles now. 
Also, it should be stated that we still have a few thousand unprocessed subtitles in the database which will be added gradually.

⏳ We did our part. And now it’s your turn to help SubSource. To do that:
🔴 Submit support tickets to report missing subtitles and page errors.
🔴 Try to fill the gap by uploading subtitles for missing titles.   

So, once again everyone can have a perfect subsource for all languages.

🟣 After subscene's shutdown, SubSource is now the pioneering subtitle website with the highest upload count & user activity.
