### ISSUE TITLE
Add support for "Play in MX Player"

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#1151]
### Describe your suggested feature

I personally like MX Player more than VLC (it has audio boost, etc... and is just easier to use) and I think it would be nice to support it as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
https://github.com/recloudstream/cloudstream/issues/586

**Comment by Luna712** [comment]
> #586

Ah sorry my bad. Thanks for pointing that out. I wonder why that didn't show up in my search.

**Comment by Luna712** [comment]
The rational provided for declining that is understandable as well. I didn't actually consider that when making this issue but it makes sense.
