### ISSUE TITLE
Save backups in a subdirectory

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#1152]
### Describe your suggested feature

At the very least if we aren't doing a separate location selection, it would be nice if it saved backups in a subdirectory (such as "Backups") since everything else saves in sub directories. It would keep things more organized for me anyway.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by iswac** [comment]
I have already opened this issue https://github.com/recloudstream/cloudstream/issues/1106

**Comment by Luna712** [comment]
> I have already opened this issue #1106

This is a different issue. This isn't asking for a custom directory just saving to a sub directory in selected downloads directory similar to how other download types do.

**Comment by iswac** [comment]
yeah i missed up but both of us want similar feature

**Comment by DestroyerBDT** [comment]
I like this
