### ISSUE TITLE
Please just like CS works when you search 🔎 in the phone 📱, update the same version (update) in TV (android) as well.

### ISSUE THREAD

**Issue by sonutiwari94** [recloudstream/cloudstream#1154]
### Describe your suggested feature

Movies✔️
TV SERIES✔️
ANIME✔️
ASIAN DRAMA✔️
CARTOON✔️
LIVE STREAM✔️
OTHER ✔️
All tick done ok In📍 all such ticks, the search gets done well in the phone 📱 but it is not like this in TV, you will have to remove all the ticks, you have to keep only one which creates problem

### Other details

World 🌍 best app CS❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
It is the exact same code on phone as on mobile.
Click the top right button to select the providers used, that's likely the issue.
