### ISSUE TITLE
Download Custom..

### ISSUE THREAD

**Issue by yusiqo** [recloudstream/cloudstream#1172]
### Describe your suggested feature

There is 1 source in the movie and 2 dubbings in the source. When downloading, it automatically downloads to English. But I want to download it in another language. There are no features.  

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Long hold the button.

**Comment by yusiqo** [comment]
> Long hold the button.

Source can be selected but audio track cannot be selected
