### ISSUE TITLE
Amoled splash screen

### ISSUE THREAD

**Issue by iswac** [recloudstream/cloudstream#1173]
### Describe your suggested feature

Selecting app theme to amoled doesn't apply to splash screen. If it can matched, it will nice for devices has amoled screen.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
The splash screen is before any code is ran and is therefore impossible to fix afaik. 

A12 might have changed some things for splash screens, but I dont know if possible to change them dynamically.

**Comment by iswac** [comment]
I saw this feature on youtube revanced. They are injecting some codes into youtube app, here is the patch which i am talking about: https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemePatch.kt

I don't know if it's possible to integrate this codes into cloudstream. Maybe this patch can help you.

**Comment by fire-light42** [comment]
> I first saw this feature on youtube revanced. They are injecting some codes into youtube app, here is the patch which i am talking about: https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemePatch.kt
> 
> I don't know if it's possible to integrate this codes into cloudstream. Maybe this patch can help you.

This is not applicable to us as we dont change the XML at runtime. While it is theoretically possible like revanced, doing any sort of self patching is just bruh and can lead to a lot of bugs.

**Comment by iswac** [comment]
> > I first saw this feature on youtube revanced. They are injecting some codes into youtube app, here is the patch which i am talking about: https://github.com/inotia00/revanced-patches/blob/revanced-extended/src/main/kotlin/app/revanced/patches/youtube/layout/theme/ThemePatch.kt
> > 
> > I don't know if it's possible to integrate this codes into cloudstream. Maybe this patch can help you.
> 
> This is not applicable to us as we dont change the XML at runtime. While it is theoretically possible like revanced, doing any sort of self patching is just bruh and can lead to a lot of bugs.

No problem, this was just a suggestion for a screen that lasts one second. Maybe in the future it will be easier to do this.
