### ISSUE TITLE
Feature Request - Long Press for 2x Playback Speed

### ISSUE THREAD

**Issue by Moviellect** [recloudstream/cloudstream#1186]
### Describe your suggested feature

I hope this message finds you well. I've been thoroughly enjoying using _Cloudstream_ **video player** and have a suggestion that I believe could enhance user experience significantly.

Currently, when watching videos, I often find myself wanting to quickly double the **playback speed** during certain sections where I need to grasp content faster. To streamline this process, I propose implementing a feature where users can simply **long-press** on the screen during playback to instantly switch to **2x speed**. This would not only improve efficiency but also make the app more versatile for various learning and viewing preferences.

I believe such a feature would be a valuable addition and would greatly appreciate your consideration in incorporating it into **future updates**. Please let me know if you need any further details or feedback regarding this suggestion.

Thank you for your continued dedication to improving the app.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Jetliarm** [comment]
yes i want that feature too

**Comment by Moviellect** [comment]
Atleast reply something devs 🥺

**Comment by ABHIRAJ770** [comment]
They said they won't appl this feature cuz it will worsen watching
experience. DON'T KNOW HOW

**Comment by Moviellect** [comment]
After all, how can this feature spoil the user experience, in fact this feature is also available in **YouTube** and other _video players_(Playit).

**Comment by Moviellect** [comment]
After all, how can this feature spoil **watching experience**, in fact this feature is also available in **YouTube**.

**Comment by Moviellect** [comment]
Hey Devs I am waiting for your reply 🥺

**Comment by fire-light42** [comment]
This has been requested many times, read https://github.com/recloudstream/cloudstream/issues/862 https://github.com/recloudstream/cloudstream/issues/569

**Comment by Moviellect** [comment]
So can I wait for this feature in the upcoming updates?
