### ISSUE TITLE
Crashes after playing video

### ISSUE THREAD

**Issue by Jetliarm** [recloudstream/cloudstream#1188]
### Steps to reproduce

1. Click TV Series Episode
2. After Clicking 
3. Crashes Auto Restart
4. Safety Mode
5. Repeat

### Expected behavior

this should be fix 

### Actual behavior

.

### Cloudstream version and commit hash

4.3.2 145c42f

### Android version

Android 13

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
This does not provide enough details. I can not reproduce with those steps. Please post the error log you get from safe mode.

**Comment by Jetliarm** [comment]
![Screenshot_20240707-115015](https://github.com/recloudstream/cloudstream/assets/171421185/45ff00a4-a826-4591-bb62-aeecaa21545a)
![Screenshot_20240707-115021](https://github.com/recloudstream/cloudstream/assets/171421185/61655a0e-1c88-4455-986f-6a5d96269c57)

**Comment by Luna712** [comment]
I believe this an extension issue not a CloudStream issue

**Comment by Jetliarm** [comment]
this happened after I updated the app

**Comment by Luna712** [comment]
Yes but still an extension issue I believe.

**Comment by Jetliarm** [comment]
: ( it often crashes when I stream with the codestream extension

**Comment by epireyn** [comment]
> : ( it often crashes when I stream with the codestream extension

Then you should open an issue on [their repository](https://github.com/Rowdy-Avocado/Rowdycado-Extensions).

**Comment by C10udburst** [comment]
Extension issue
