### ISSUE TITLE
Auto caption/subtitles button

### ISSUE THREAD

**Issue by Devaraj10** [recloudstream/cloudstream#1189]
### Describe your suggested feature

As soon as I play either series or movie caption button should be present with respect to the same. If I add subtitles sometime it is not loading as expected, need an another repo for education purpose(Coursera, udacity etc). Expecting both the features to be added at earliest.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
This sounds like an extension issue, and is therefore not related to the development of the app. Ask the extension devs for these sites.
