### ISSUE TITLE
Video Controls With Their Name

### ISSUE THREAD

**Issue by Moviellect** [recloudstream/cloudstream#1190]
### Describe your suggested feature

The controls appearing at the bottom of the video player are scrolling due to being more controls. This is affecting both the UI and UX negatively.

![Screenshot_2024-07-08-08-10-45-93](https://github.com/recloudstream/cloudstream/assets/124981470/5296f3e2-d77a-49d6-9825-bc05bf6071eb)

I suggest adding a toggle button in [Settings > Player > Player features] labeled "**Show control's name**" to address this issue.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Uvdon** [comment]
What would make it better is just to have settings button on top right; then have all settings options like sub, zoom, video speed, etc. Just like sflix (another great app to stream movies and show)

**Comment by Moviellect** [comment]
I have used many amazing features of Video Players like **Playit** and **Splayer**. But they will not make much changes in their app for us, so I only want this small feature from them and they are unable to provide that too.

What's more, neither does anyone reply.
