### ISSUE TITLE
Two terms, "extension" and "plugin", are used to describe the same feature.

### ISSUE THREAD

**Issue by DucksInParks** [recloudstream/cloudstream#1191]
### Steps to reproduce

In the settings, there's a section called "extensions", where repos can be added and extensions can be installed. But when an extension is installed or deleted, a toast appears that says "Plugin loaded" or "Plugin deleted". Trying to delete a repo will warn users that doing so will delete all _plugins_. In the "Updates and Backup" section of the settings, there's a section titled "Extensions", where the two options "Automatically download plugins" and "Automatic plugin updates" can be changed. In most cases, the feature is referred to as "extension"

### Expected behavior

All text in the app should refer to the feature using a single name to not confuse users (I think using "Extensions" is better).

### Actual behavior

Extension and plugin are both used interchangeably and inconsistently.

### Cloudstream version and commit hash

All recent versions

### Android version

All

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
While the terminology might seam ambiguous they do in fact mean different things.

A repository (repo) is a collection of plugins.

A plugin is a collection of both extractors and extentions, but most of the time is just focus on a single extension. For example both SoraStream and SoraStream-Lite is in the same plugin. Plugins also does not have to include any extensions, for example a plugin might just be an child password lock, but this is quite rare. 

An extension is a single source of information, so each extension may have a homepage and show up in search. Most of the time these are a reflection of a site/app/api or uses several of these combined with TMDB. 

An extractor is a single transformator for links, so it transforms a link like https://www.youtube.com/watch?v=EJ3A-PRUnc0 to something playable in the app or an external app like vlc.


So when you install/update/load a plugin it means *all* extensions and extractors in that plugin.
