### ISSUE TITLE
Using Cloudstream plugin in Stremio

### ISSUE THREAD

**Issue by Ledenav** [recloudstream/cloudstream#1192]
### Describe your suggested feature

A method has been developed to use Stremio add-ons in cloudstream. But I want to use cloudstream add-ons on stremio. Can you suggest a method for this? Because Stremio also supports the Windows and iOS ecosystem.

https://recloudstream.github.io/csdocs/integrations/stemiorelated/

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by C10udburst** [comment]
That is impossible because of the way our extension system works. If you want cloudstream in windows you can use WSA.
