### ISSUE TITLE
Chillix Keys donot fetch 

### ISSUE THREAD

**Issue by 0x86e3x4** [recloudstream/cloudstream#1193]
### Steps to reproduce

making a call and fetching to get Keys from https://raw.githubusercontent.com/rushi-chavan/multi-keys/keys/keys.json

### Expected behavior

json response of key to decrypt the base64EncryptedData

### Actual behavior

{ { " Chillix " : " redactedKey"  },{ "aniwave" : "some redacted key"}}

### Cloudstream version and commit hash

2.8.6

### Android version

12

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
current cloudstream version is 4.4.0. If you really are on such an old version please consider updating
