### ISSUE TITLE
Subtitles scrapping gone bad

### ISSUE THREAD

**Issue by stojkovskistefan** [recloudstream/cloudstream#1200]
### Steps to reproduce

1. Open any movie/tv show on SoraStream. Just did this with the planet of the apes movie.
2. Sub issue as presented bellw
![17209062777316417382437883588942](https://github.com/user-attachments/assets/3616ccad-74f0-4155-8264-ee87c2e319b2)

### Expected behavior

show be as before, where you see english 1, english 2 etc

### Actual behavior

actual behavior explained in the picture

### Cloudstream version and commit hash

4.3.2 8be8e54

### Android version

fire tv

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Provider issue, create an issue on the extension repo as this is the app repo.

**Comment by stojkovskistefan** [comment]
@fire-light42 can you try please adding a subtitle to any of your movies using the feature add from the internet? select any language and add the subtitle. Simply the subtitle feature does not work also with an external subtitle.

**Comment by stojkovskistefan** [comment]
If it's only a provider issue, i should have been able to see a subtitle, but i can't even with the add from internet feature.
