### ISSUE TITLE
Add https://animixplay.to/ this site pls

### ISSUE THREAD

**Issue by Light7654** [recloudstream/cloudstream#121]
### Describe your suggested feature

Add AnimixPlay site 
https://animixplay.to/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Please do not ask for providers here.
