### ISSUE TITLE
There should be a membership login system

### ISSUE THREAD

**Issue by turbetfur** [recloudstream/cloudstream#1225]
### Describe your suggested feature

When you install Cloudstream on another device, the favorites should come

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by C10udburst** [comment]
Duplicate. Relevant issues:
- #549
- #548
- #623
