### ISSUE TITLE
Upstream extractor doesn't work

### ISSUE THREAD

**Issue by Memexurer** [recloudstream/cloudstream#123]
### Steps to reproduce

1. open any video from upstream
2. it doesn't work

### Expected behavior

it should work

### Actual behavior

but it doesn't...

### Cloudstream version and commit hash

asd

### Android version

asd

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [x] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
There is a billion providers, I cannot go hunt down where upstream is used. Send me which video on which provider if you want me to look at it.

**Comment by Memexurer** [comment]
yeahy
