### ISSUE TITLE
"Crucial Feedback and Enhancement Ideas for CloudStream"

### ISSUE THREAD

**Issue by DiscoDeanse** [recloudstream/cloudstream#1235]
### Steps to reproduce

👋 **Hello!** As a dedicated user of both the CloudStream and CloudStream Beta apps, I’ve encountered some bugs and have a few suggestions. Here’s a detailed account of my experience:

---

### 🐞 **Bug Reports:**

1. **Extension Download Issue:**
   Post-update, the extensions tab shows 47 extensions as undownloaded, despite them being downloaded before the update. Re-downloading and repository searches haven’t resolved this. 🐛

2. **Subtitle Search Issue:**
   Searching for subtitles within the app yields no results. This issue needs addressing. 🎥📝

3. **Download Crash Issue:**
   Downloading two large files (around 2.5 GB each) simultaneously results in one download crashing after 200-300 MB. This issue persists and seems to be a bug. 📥💥

4. **Inconsistent Search Results:**
   Searching for the same content in CloudStream Blue and CloudStream Beta provides different results. This inconsistency persists across updates. 🔍🤔

---

### 💡 **Suggestions:**

1. **Disable Extensions Option:**
   Add an option to disable extensions to speed up searches and save data. Currently, only a fraction of extensions connect due to my network limitations. 📡⚙️

2. **Download Scheduler:**
   Introduce a scheduler for downloads to align with specific unlimited internet time windows. For example, I have unlimited access from 12 Noon to 6 A.M., and my sister has access from 9 A.M. to 5 P.M. 📅⏰

3. **Movie Sharing Feature:**
   Enable sharing of movies between CloudStream apps to streamline finding content in preferred languages and quality. A shared library feature would be valuable. 🎬🔗

4. **Automatic Tagging:**
   Enhance the tagging system to automatically update based on viewing status—mark movies as completed, watching, or dropped accordingly. 🏷️✅

---

🙏 **As a fan of your app,** I appreciate its user interface and superior download options compared to alternatives. I’m confident your team can implement these improvements over time. 

**Thank you for your attention!** 😭❤️

### Expected behavior

📝 **Everything is written in steps to reproduce** for clarity. 👍

📌 **Version Information:**
I have included the type of the CloudStream app for each issue to avoid any confusion. Each bug and suggestion is clearly labeled with whether it pertains to the Beta or the standard app. 👍

👉And In Cloudstream version and commit hash I have put Version of CloudStream Beta.(I Use Both).

### Actual behavior

📝 **Everything is written in steps to reproduce** for clarity. 👍

📌 **Version Information:**
I have included the type of the CloudStream app for each issue to avoid any confusion. Each bug and suggestion is clearly labeled with whether it pertains to the Beta or the standard app. 👍

👉And In Cloudstream version and commit hash I have put Version of CloudStream Beta.(I Use Both).

### Cloudstream version and commit hash

"4.4.0 ab379ab"

### Android version

Android 14

### Logcat

```java
https://drive.google.com/file/d/1FPbIq4M4ErHkqcINzId4RsiZ_pMhTuyk/view?usp=drivesdk
```

### Other details

No Other Details.

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Please do not create issues with multiple problems, as it makes it hard for us to track progress. Each problem should be a new issue.
