### ISSUE TITLE
Categories Movies and Series

### ISSUE THREAD

**Issue by showmidelo** [recloudstream/cloudstream#124]
### Describe your suggested feature

Thanks for your great app, i have suggestion.
While we hold our finger on a poster of a movie or a series it would be great if it shows us different categories of watched, plan to watch, etc to make the way easier for us to add them.
Right now we must click on the poster and go to page of a movie and select in the right bottom of the app to add them to the categories we want.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
no
