### ISSUE TITLE
Search by IMDB ID 

### ISSUE THREAD

**Issue by trustosas** [recloudstream/cloudstream#1247]
### Describe your suggested feature

For example tt0301935 should return search results for the movie 3 days (2001)

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by KingLucius** [comment]
Depends on the provider

**Comment by fire-light42** [comment]
^
