### ISSUE TITLE
Dns

### ISSUE THREAD

**Issue by Mrunknow3** [recloudstream/cloudstream#1250]
### Describe your suggested feature

Can you add 1.1.1.1 app dns pls. 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by FUSIONOF** [comment]
> ### Describe your suggested feature
> Can you add 1.1.1.1 app dns pls.
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  My suggestion is **NOT** about adding a new provider
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

Already In App With Name Cloudflare In Settings,General,DNS Over Https.👍

**Comment by Mrunknow3** [comment]
Yes that has but some repo working with an app called 1.1.1.1 dns app and not working with app dns.

**Comment by C10udburst** [comment]
1.1.1.1 is cloudflare
