### ISSUE TITLE
Show download source options

### ISSUE THREAD

**Issue by Protonosgit** [recloudstream/cloudstream#1254]
### Describe your suggested feature

When pressing the download button there should be a menu where the user can select the **source** and the **audio track** and maybe even subtitles.
When playing a show/movie directly the user can sometimes pick between different audio tracks and sources to find the best one.

### Other details

Maybe show a bottomsheet popup when download is pressed and multiple options are available to choose from.
Also a _default behavior_ could be implemented in the settings to skip this step.

### Acknowledgements

- [x] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Already exists, hold the download button to select the source.
