### ISSUE TITLE
Local Videos Selector UI

### ISSUE THREAD

**Issue by Moviellect** [recloudstream/cloudstream#1260]
### Describe your suggested feature

The feature of selecting and playing local videos in Cloudstream is great, but it still selects videos from the default storage UI. Please make it like **Next Player's** UI.

![2](https://github.com/user-attachments/assets/a1224d88-e8e7-434d-b590-bcbca20a2763)

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Scoped storage in android is impossible to get right, and as such there are no plans to add it just to make the UI a bit nicer.
