### ISSUE TITLE
hold down 2x speed on player

### ISSUE THREAD

**Issue by yusiqo** [recloudstream/cloudstream#1263]
### Describe your suggested feature

Press and hold on the player to play at 2x speed, like on YouTube 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Moviellect** [comment]
But why this feature is denied. It's a cool feature. Please Add a **toggle** in players settings.

**Comment by fire-light42** [comment]
#1186
#862
#237
