### ISSUE TITLE
Share links to cloudstream

### ISSUE THREAD

**Issue by aneesh1122** [recloudstream/cloudstream#1296]
### Describe your suggested feature

There are sites like luxmovies where we can't search for anything because of cloudflare. Could you please make it possible to share links from browser to cloudstream?

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by C10udburst** [comment]
Already a feature, use share sheet to open in app.

**Comment by aneesh1122** [comment]
> Already a feature, use share sheet to open in app.

There's only 'Play with CloudStream' and that doesn't work. I'm getting this error

![Screenshot_2024-09-08-10-33-04-712_com.miui.gallery-edit.jpg](https://github.com/user-attachments/assets/db4995e8-fd2f-45c2-aa5d-0ad7138e93f2)

Getting streaming links if I open the movie page from the app itself works fine. Sharing page links to the app doesn't.

**Comment by C10udburst** [comment]
it means that the given website is not supported
