### ISSUE TITLE
Add Support external Downloader

### ISSUE THREAD

**Issue by excalibur1010** [recloudstream/cloudstream#130]
### Describe your suggested feature

For this apps 1DM, 1DM+, 1DM lite, ADM, FDM
And support select sources

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jpants36** [comment]
pretty sure you can just hold down play, click open in browser then you can select apps such as 1dm.

**Comment by excalibur1010** [comment]
![Screenshot_2022-10-01-17-32-51-044_com lagradost cloudstream3 prerelease](https://user-images.githubusercontent.com/58497792/193405351-a335883a-df8f-4c4b-8438-f7c23bc5580f.jpg)

Owh
thanks for telling me
