### ISSUE TITLE
Don't ask again option add plesae

### ISSUE THREAD

**Issue by xcbly** [recloudstream/cloudstream#1302]
### Describe your suggested feature

![Screenshot_3](https://github.com/user-attachments/assets/5032ca95-c69c-4942-89b8-89aaa2cb20e8)

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by zzjjaayy** [comment]
No one seems to be working on this, taking this up!
