### ISSUE TITLE
can't update app (android)

### ISSUE THREAD

**Issue by Gamefire238** [recloudstream/cloudstream#131]
### Steps to reproduce

i pressed the update app button, but only a popup message appears (download starts) but nothing happens after that and the app is not updated.

### Expected behavior

bug fixed 

### Actual behavior

in-app update not working 

### Cloudstream version and commit hash

all

### Android version

Android 11 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by imurreflection** [comment]
Some trouble shooting steps
1. Using file manager check in download folder if the file is already downloaded. If yes, install from there manually
2. Check if CS 3 has been given storage permission
3. Check if unknown sources are allowed
4. Manually install CS 3 from GitHub Repo and check if future updates are geting installed. Make sure update to pre-release option is selected.

**Comment by Gamefire238** [comment]
does the app really not have download notifications?

**Comment by Blatzar** [comment]
It does not yet.

**Comment by Gamefire238** [comment]
it might be good if it was added, so as not to cause confusion :)

**Comment by Blatzar** [comment]
That's a given, it's just a matter of allocating the time to do that.

**Comment by C10udburst** [comment]
> does the app really not have download notifications?

It does now, try the latest prerelease
