### ISSUE TITLE
stuck on 99%

### ISSUE THREAD

**Issue by Turhvjbufv** [recloudstream/cloudstream#1311]
### Steps to reproduce

Download a bunch of episodes

### Expected behavior

Will show as completed download and not be stuck on 99%

### Actual behavior

sometimes the downloads will get stuck on 99%(even tho the download is shown and is completed when I check downloaded episodes) which wouldn't really be a problem but it takes the third simultaneous download so the episodes download much slower 

### Cloudstream version and commit hash

prerelease commit-6601291

### Android version

android 14

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Is it the notification or download icon that is stuck, and if you reload the app is it still stuck at 99%?
