### ISSUE TITLE
Removed from IzzyOnDroid?

### ISSUE THREAD

**Issue by Handrail9** [recloudstream/cloudstream#1313]
### Steps to reproduce

Hi, I was wondering if there was a reason CloudStream was removed from IzzyOnDroid? I noticed it recently. Was there an issue that came up with a recent update? or a mistake? Something else?
Thanks
https://apt.izzysoft.de/fdroid/index/apk/com.lagradost.cloudstream3
@IzzySoft

### Expected behavior

``

### Actual behavior

``

### Cloudstream version and commit hash

``

### Android version

``

### Logcat

```java
``
```

### Other details

``

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by IzzySoft** [comment]
https://github.com/LagradOst/QuickNovel/issues/223#issuecomment-2289503318 and the following comments.

**Comment by Handrail9** [comment]
This is really sad to hear as I only give droidify permissions for installing other apps. This impacts my personal threat model and I hope it is changed in the future

**Comment by C10udburst** [comment]
> This is really sad to hear as I only give droidify permissions for installing other apps. This impacts my personal threat model and I hope it is changed in the future

My fdroid repo contains cloudstream and cloudstream prerelase https://c10udburst.github.io/fdroid/
