### ISSUE TITLE
Streaming issue in my region

### ISSUE THREAD

**Issue by FarisArabia** [recloudstream/cloudstream#132]
### the issue 

the app doesn't let me watch anything without a vpn, i assume it's an IPS issue but i don't know how to fix it except using a vpn but this also is an issue because it drains my internet speed which makes using a vpn kinda counterproductive

### Expected behavior

this issue need to be fixed, i live in the middle east and testing other similar services it works well but cloudstream offer everything good i want not existent in other apps

### Actual behavior

it doesn't let me stream without a vpn

### Cloudstream version and commit hash

all

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
bruh complain to your isp not us

we have no way to fix that
