### ISSUE TITLE
Request to add a website

### ISSUE THREAD

**Issue by MRS73694** [recloudstream/cloudstream#133]
### Describe your suggested feature

Hi
There is a website by the url: https://anime-world.in/

This website has anime and cartoon in Hindi, original dubs not any fan-made ones. It would be great to implement this website as well, for the Indian users. Thank you

### Other details

https://anime-world.in/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
that provider seems to exist somewhere already
