### ISSUE TITLE
Providers don't work

### ISSUE THREAD

**Issue by KilianB2010** [recloudstream/cloudstream#1337]
### Steps to reproduce

Open app
Go to settings 
Click on providers
Click on test all

### Expected behavior

17 succes

### Actual behavior

7 succes
10 failed

### Cloudstream version and commit hash

4.4.0.apk

### Android version

Android 9.0

### Other details

I'm using all German providers.
I randomly saw that I'm not able to continue watching my series.
When I test all providers The Error for the most providers says that the provider doesn't return any search requests.
I would like to that be fixed as fast as possible.
Thank you.

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CranberrySoup** [comment]
> I have updated the app to pre-release version.

4.4.0.apk is not the latest pre-release 

> I am sure my issue is related to the app and NOT some extension.

Read Acknowledgements before you make issues, they exist for a reason. 
This github repository is for the **app only**, we can not and will not help with extension issues. Make a detailed and informative issue in the appropriate github repository for extensions you use.
