### ISSUE TITLE
Please add others french sources or providers for the Tvshow and movies

### ISSUE THREAD

**Issue by lucvs29** [recloudstream/cloudstream#135]
### Describe your suggested feature

Hello, 
I want to congratulate you for the great app, nice job.
Please, could you add other French sources or provisers for watching tvshow and movies, because French-stream does not work.Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
bruh idk why it runs multiple times

**Comment by C10udburst** [comment]
but dont ask for providers here
