### ISSUE TITLE
A possible Tizen app/module using TizenBrew

### ISSUE THREAD

**Issue by Adithyan007hack** [recloudstream/cloudstream#1355]
### Describe your suggested feature

Hello,
So I'm just pulling this issue up again
https://github.com/recloudstream/cloudstream/issues/332

If anyone want to contribute , or want to check if Cloudstream can be made possible in Samsung Tizen os TV's using TizenBrew :

https://github.com/reisxd/TizenBrew
https://github.com/reisxd/TizenBrew/blob/main/docs/MODULES.md

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by KingLucius** [comment]
I think it's for web applications only

**Comment by ThatOneCalculator** [comment]
It is. This issue should be closed as invalid.

**Comment by C10udburst** [comment]
cloudstream od Android only
