### ISSUE TITLE
Subtitle Edge

### ISSUE THREAD

**Issue by sakib2k23** [recloudstream/cloudstream#1369]
### Describe your suggested feature

I want subtitle like Crunchyroll 
Like little bit more bold edge

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Not possible in exoplayer.

**Comment by sakib2k23** [comment]
> Not possible in exoplayer.

I thought you could do the (Option to Increase Subtitle Outline Thickness(
