### ISSUE TITLE
Kodi cloudstream addon

### ISSUE THREAD

**Issue by pluzman** [recloudstream/cloudstream#1375]
### Describe your suggested feature

Re cloudstream kodi addon please 

### Other details

Kodi omega update addon

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
This is the repo for the app, not extensions.
