### ISSUE TITLE
Material you theme on Android phone request.

### ISSUE THREAD

**Issue by Uvdon** [recloudstream/cloudstream#1384]
### Describe your suggested feature

I have the app on Android TV and really like the material you theme on it, so I would like to request that feature on android phones. 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by C10udburst** [comment]
It exists on phones. If you don't see it it means your phone is running Android <12 and doesn't support monet.

**Comment by Uvdon** [comment]
Got it. Thanks

**Comment by Uvdon** [comment]
Didn't know an and android version can't handle themes/colors
