### ISSUE TITLE
 Torrent stream 

### ISSUE THREAD

**Issue by ShoaibKhanali** [recloudstream/cloudstream#1385]
### Describe your suggested feature

Add torrent stream like Kuukiyomi

https://github.com/YouROK/TorrServer?tab=readme-ov-file

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Moviellect** [comment]
I just want to know if you will add torrent stream feature in future?

**Comment by fire-light42** [comment]
In prerelease
