### ISSUE TITLE
Add support to play torrents

### ISSUE THREAD

**Issue by Moviellect** [recloudstream/cloudstream#1398]
### Describe your suggested feature

Hello,
I am a huge fan of your work and follow your application for a long time. 
There is a *StreamioX* extension in **Hexated's repository**, to use which you will need a subscription to _Debrid_. It will be better if you add torrent stream support to cloudstream.
Huge request sir.

### Other details

I think it will be helpful :-

https://github.com/YouROK/TorrServer

https://xdaforums.com/t/app-4-0-3-amnis-torrent-player.3779592/

https://www.apkmirror.com/apk/nir-halay/amnis-torrent-player/amnis-torrent-player-1-0-11-release/amnis-torrent-player-1-0-11-android-apk-download/

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Moviellect** [comment]
> Duplicate #1385

Sir what do you think about my request.

**Comment by fire-light42** [comment]
Closed due to duplicate.

**Comment by infojoe** [comment]
Can we get a separate fork without this torrenting nonsense integrated? Now with Real-debrid having to basically shut down, it makes no sense to have this useless code bloating the app.

**Comment by fire-light42** [comment]
Why do you think torrenting has anything remotely to do with real-debrid? CS3 is an open source project that has never acknowledged or supported paid services. The essence of torrenting is just a distributed file system, so it is only natural that a media player like cs3 would be able to support it.

**Comment by infojoe** [comment]
Can we at least have the option to disable it? Most people that use torrents are using Stremio, Weyd, etc... I prefer to not use torrents and that is why I prefer cloudstream.

**Comment by infojoe** [comment]
I've seen the popup and find it annoying. I have selected to hide torrents in settings -> providers -> preferred media, yet I am still getting the pop-up. Please just allow us to disable the torrent backend with a simple off switch.
