### ISSUE TITLE
Download quality preference 

### ISSUE THREAD

**Issue by RaknaroK4LifeBRuv** [recloudstream/cloudstream#140]
### Describe your suggested feature

It would be nice to have preferred download quality like the preferred watch quality.So we don't have to wait a long time for big quality movies for 2gb and download 420mb episode of an anime instead we can select the preferred quality and download.it would be nice to have it bruv. Peace ✌️🕊️ . RaknaroK over n out

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AbdulSamadMalik** [comment]
+1

**Comment by KillerDogeEmpire** [comment]
Just hold the episode you want to download and click download mirrors.......

![image](https://user-images.githubusercontent.com/87155550/195496784-a043a2fb-1fc1-4a20-983d-7967c7fbab6b.png)

![image](https://user-images.githubusercontent.com/87155550/195496930-d7d6026f-acdf-4a61-b482-a3a84cec6ebb.png)

**Comment by RaknaroK4LifeBRuv** [comment]
It's just showing only one mirror which is the highest quality ...

**Comment by LagradOst** [comment]
download rework in progress

**Comment by RaknaroK4LifeBRuv** [comment]
Thanks, I'll check it out.

**Comment by soredake** [comment]
@LagradOst sorry bothering, but this rework is still planned?

**Comment by LagradOst** [comment]
yes, check the aria2c branch

**Comment by soredake** [comment]
Shouldn't it stay open until it's implemented?
