### ISSUE TITLE
Cloudstream for mac

### ISSUE THREAD

**Issue by vijaydev2019** [recloudstream/cloudstream#1400]
### Describe your suggested feature

Do we have this app for mac?
If not is there any way we can use in browser or any other way?

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by C10udburst** [comment]
No, this is an android app. Only way is to use an emulator.
