### ISSUE TITLE
Add system time when pause video. 

### ISSUE THREAD

**Issue by muichunlim** [recloudstream/cloudstream#1401]
### Describe your suggested feature

When pause the video, it shows essential information on screen. It will be nice if it can show current time in 12 o clock position. 

This should let the user know it is late and time to stop watching. 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Not planned, the system clock is easily accessible with a swipe.
