### ISSUE TITLE
StreamioX videos are not streaming.

### ISSUE THREAD

**Issue by Moviellect** [recloudstream/cloudstream#1404]
### Describe your suggested feature

With your hard work we can now stream torrents(magnet link) in Cloudstream. But we are still not able to stream videos from *StremioX*(hexated) plugin. Please fix the issue of playing videos of *StremioX* also.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by LagradOst** [comment]
Provider issue, they have the wrong type.
