### ISSUE TITLE
Option to disable torrenting 

### ISSUE THREAD

**Issue by ITron-Legends** [recloudstream/cloudstream#1413]
### Describe your suggested feature

Seems pretty obvious 
It's super annoying. 

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by asahibeer666** [comment]
yeah, ddl-only option would be great

**Comment by infojoe** [comment]
Hi. Is there any chance of getting an update to the pre-torrent enabled 4.2 version? Many TV stick devices only have 8gb of storage and about 6gb is used by OS. Storage space is very limited and the torrent enabled version is more than double in size. 60mb install package translates to over 120mb installed size. It would be greatly appreciated by those of us that don't use torrents.
