### ISSUE TITLE
VOE ne fonctionne pas sur plusieurs provider

### ISSUE THREAD

**Issue by DZFOORT** [recloudstream/cloudstream#1419]
### Steps to reproduce

le lecteur VOE

### Expected behavior

VOE

### Actual behavior

VOE PLAYER

### Cloudstream version and commit hash

4.4.0

### Android version

Android 12 

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
1. English
2. This is the app repo, we do not maintain extensions

**Comment by DZFOORT** [comment]
extractor voe marche pas toujours
