### ISSUE TITLE
cda.pl player support if possible

### ISSUE THREAD

**Issue by Jacob1Tm** [recloudstream/cloudstream#142]
### Describe your suggested feature

In Poland cda is very popular player, and it may be very useful to add for Polish users.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the discord.

**Comment by Jacob1Tm** [comment]
i don't mean provider just player many providers use it to upload videos

**Comment by C10udburst** [comment]
ah, mb then

**Comment by LagradOst** [comment]
no, not open soruce
