### ISSUE TITLE
External Player Support 

### ISSUE THREAD

**Issue by TheAymen** [recloudstream/cloudstream#1420]
### Describe your suggested feature

First of all, thank you for all the great work.

Currently, there is no simple way to do this on android tv other than copying the link and pasting it on the external player. Why limit the options to a few select ones when you can have them all as external players?

Some say that "open in browser" works, and perhaps it does so on phone, but doesn't really work on my Chromecast with Google TV. It just opens the browser and doesn't show me the option to select other apps as other posts seem to suggest. 

Thanks.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
What external players are missing? We are only natively supporting *open source* video players out of principle, however if there are some popular open source video players that are missing then we can add it. Moreover extensions have the ability to add more video players options, so you or anyone else can add it without doing a PR.

**Comment by TheAymen** [comment]
Thank you for the reply. 

Unfortunately, the players I normally use aren't open-source. My suggestion would be something like an "external" option that allows any app installed capable of playing the content/links to play the content, rather than supporting explicitly supporting each new player.

Similar to how the "Open in Browser" option lets you choose your browser if you have multiple installed.

Regarding the extension that supports external players, I haven't come across such, and it would certainly be useful. Are you aware of any specific projects that have achieved this? 

Thanks.

**Comment by asl97** [comment]
I mentioned "share link" before on numerous occasions.

Here is the share link feature on firefox, it contain almost everything anyone might want and also a lot of irrelevant apps but that's fine.
![Screenshot_2024-12-09-11-49-20-493_android](https://github.com/user-attachments/assets/0aa6e62f-8037-4764-bac6-d5fbbfaa2f2b)

Cloudstream also has the share feature implement for sharing the show page but not for the individual episode.
![Screenshot_2024-12-09-12-05-19-904_com mi android globallauncher-edit](https://github.com/user-attachments/assets/9859f0f2-ad31-4468-969a-2f57544414b9)

@fire-light42 would it be that hard to either change "Copy to Clipboard" to "Share Link" or just add "Share Link" as another as another option using what was already implemented for the page share?
 
I am guessing just swap the clipboard line
https://github.com/recloudstream/cloudstream/blob/54df562b10170b476adf638e16afd859ae10aca1/app/src/main/java/com/lagradost/cloudstream3/actions/temp/CopyClipboardAction.kt#L25

with the share intent lines and changing a few variable names.
https://github.com/recloudstream/cloudstream/blob/54df562b10170b476adf638e16afd859ae10aca1/app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentPhone.kt#L759-L767

past requests:
https://github.com/recloudstream/cloudstream/issues/747#issuecomment-1791719328
https://github.com/recloudstream/cloudstream/issues/899#issuecomment-1901071880

**Comment by fire-light42** [comment]
ACTION_SEND is not the same as ACTION_VIEW. And Open in browser uses ACTION_VIEW meaning that is up to the receiving apps to declare that they can handle showing that media, however ACTION_SEND means that we "Deliver some data to someone else". Video links are by their very definition only for you (some are even ip locked), so it makes no sense for us to "share" links because some other app has not declared a valid ACTION_VIEW.

https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/actions/temp/PlayInBrowserAction.kt#L35

https://developer.android.com/reference/android/content/Intent#ACTION_VIEW
https://developer.android.com/reference/android/content/Intent#ACTION_SEND
