### ISSUE TITLE
Frame Rate Matching/Switching 

### ISSUE THREAD

**Issue by TheAymen** [recloudstream/cloudstream#1421]
### Describe your suggested feature

As it says in the title. As external video players aren't supported, having this option in the app is useful for TV, especially when watching a variety of content.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Can you explain what exactly frame rate matching is

**Comment by TheAymen** [comment]
Basically, it is a useful video-playing feature that allows the device to adjust the output refresh rate to match the native frame rate of the video being played. 

Devices like the Chromecast with Google TV allow for this automatic switching if the app asks for it. 

The benefits of this are multiple. The primary one is higher fidelity, as the TV need not add additional frames where there are none (e.g. a 24 fps video needing to adjust for a display set at 60 fps). When the native video frame rate and screen refresh rate mismatch, this can create judder.

While users can adjust this manually, it would certainly be a QoL feature to have it automatically adjust the refresh rate. 

Similarly, there's Resolution Matching, where the TV changes its resolution depending on the content being played, which has its own advantage of not needing to upscale content to fit the display (e.g. a 720p picture trying to adjust to a display set at 1080p). 

This is probably why TVs allow switch Resolution and Frame Rate. It boils down to trying to preserve fidelity: the conditions in which it is displayed so that it is close to what is intended.

I hope this helps. Although I would like to note that I'm no expert. This is just the way I understand the concept.

Thank you for all the great work.

**Comment by fire-light42** [comment]
It looks like exoplayer already uses it by default, but only on api30+ (VIDEO_CHANGE_FRAME_RATE_STRATEGY_ONLY_IF_SEAMLESS)

https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/ExoPlayer.java#L706

https://github.com/androidx/media/blob/df887a942222914836081f868067960eb0149547/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/video/VideoFrameReleaseHelper.java#L348

**Comment by fire-light42** [comment]
Anything more would require an upstream pull request, and that is not happening.
