### ISSUE TITLE
extensions repo not fully downloaded

### ISSUE THREAD

**Issue by MarshMeadow** [recloudstream/cloudstream#1424]
### Steps to reproduce

on my android 10 tablet from Samsung for some reason when i use the m repo it does not fully download or show all the sources and im not sure what that means..

### Expected behavior

for it to show them all or give an error when i go to them

### Actual behavior

just does not show them and acts normal ish

### Cloudstream version and commit hash

latest

### Android version

10

### Logcat

```java
n/a
```

### Other details

n/a

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Sounds like an connection error. However this is an issue for the extention developer instead.
