### ISSUE TITLE
volume boost

### ISSUE THREAD

**Issue by DZFOORT** [recloudstream/cloudstream#1426]
### Describe your suggested feature

the sound on the content sometimes is too good please add an option to boost the volume

### Other details

example like mx player

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by DZFOORT** [comment]
@IndusAryan @LagradOst @fire-light42

**Comment by fire-light42** [comment]
1. Dont ping, just because you dont get a comment within 10s
2. A basic search would have found #1086
3. Closing for duplicate
