### ISSUE TITLE
Download estimate decreasing 

### ISSUE THREAD

**Issue by MustXD** [recloudstream/cloudstream#1427]
### Steps to reproduce

1. Started download
2. The part where it show the estimated download start decreasing 

### Expected behavior

I think it should stay the same till the downloading end

### Actual behavior

I was trying to download the first ep of arcane and i found something strage the download started without issues then the part where it shows the downloading progress for exemple 
* 00mb/1.3gb*
The estimated 1.3Gb started decreasing while the progress was increasing until it matched at 400mb and stopped 

### Cloudstream version and commit hash

4.4.0

### Android version

Android 14

### Logcat

```java
N/A
```

### Other details

When i opened the downloaded ep it was incomplete so i don't it was showing how much was left to finish 

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MustXD** [comment]
![Screenshot_20241215_040853_CloudStream.jpg](https://github.com/user-attachments/assets/875d481d-95b7-466a-ba26-5b2fe196e9f3)

![Screenshot_20241215_040731_CloudStream.jpg](https://github.com/user-attachments/assets/056083a0-2f18-4a62-b56b-a717ae143327)

**Comment by fire-light42** [comment]
This is not a bug as m3u8 files simply do not contain the total amount of bytes. Instead we estimate the total amount of bytes in a m3u8 file by totalSegments * bytesDownloaded / downloadedSegments. However as you have noticed it might cause inaccurate reporting of the actual size. 

https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/utils/VideoDownloadManager.kt#L646
