### ISSUE TITLE
Dual subtitle support

### ISSUE THREAD

**Issue by Ughur** [recloudstream/cloudstream#1428]
### Describe your suggested feature

I would like to request a feature that allows selecting and displaying two subtitles simultaneously in the CloudStream player.

How it should work:

Users should have the ability to choose two different subtitle languages (e.g., English and Turkish).

Both subtitles will appear on the screen, one above the other or styled differently for clarity.

This feature will be extremely helpful for language learners who want to follow dialogues in two languages at once.

### Other details

Allow customization, like choosing the position or style of the dual subtitles.

### Acknowledgements

- [X] My suggestion is **NOT** about adding a new provider
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by fire-light42** [comment]
Extremely niche use case, and would only make the UI more confusing and unintuitive.
