### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by abel200734** [recloudstream/cloudstream#1436]
### Steps to reproduce

When i tried to play movies from diffrent sources none of them seems to load.For example suppose i try to watch movies from streamplay.It shows me the error cannot connect to moviesapi,when i tried to connect through sorastream cannot connnect to server

### Expected behavior

It was suppose to load

### Actual behavior

Its showing the error cannot connect to server

### Cloudstream version and commit hash

4.4.0

### Android version

Android 14

### Acknowledgements

- [X] I am sure my issue is related to the app and **NOT some extension**.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This repository is not responsible for extentions.
