### ISSUE TITLE
Latest Update?

### ISSUE THREAD

**Issue by imurreflection** [recloudstream/cloudstream#144]
Hi Dev, it appears that latest update (Turkish Translation One) has broken the CS3 completely on Android TV and TV box. The app is now crashing completely. Can you please fix this. For the time being, i have reverted to previous pre-release

**Comment by C10udburst** [comment]
Can you provide the logcat?

**Comment by imurreflection** [comment]
My apologies but i have already uninstalled the pre version. I will wait for next pre update and certainly provide you logcat if the issue persists. Meanwhile if others are not experiencing this event then there might be some issue with my setup though it never happened in the past. Closing the issue as for now.
