### ISSUE TITLE
recloudstream.github.io is down

### ISSUE THREAD

**Issue by morbidhound** [recloudstream/cloudstream#148]
### Steps to reproduce

recloudstream.github.io is down, and repositories are unable because of that.

### Expected behavior

Repositories should be available on recloudstream.github.io

### Actual behavior

404 Not found 

### Cloudstream version and commit hash

3.1.5 1db1baef

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Yes, yes it is.
Because of a complaint from SkyUK & Kopjra we're unable to provide links to repositories as some extensions can provide access to some uninteresting TV show which is not in public domain.
