### ISSUE TITLE
Public extension repository error 404.

### ISSUE THREAD

**Issue by usernamex** [recloudstream/cloudstream#149]
### Steps to reproduce

Install extension from freshly installed recloudstream app.

### Expected behavior

List of extensions should be there.

### Actual behavior

Error 404.

### Cloudstream version and commit hash

3.1.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by owl1x** [comment]
how can I download ripositories for the app?

**Comment by Donkey-Doug** [comment]
![Uploading Screenshot_20221011-161434_CloudStream.png…]()

**Comment by C10udburst** [comment]
read #148
