### ISSUE TITLE
Lagging on Android TV, please Optimize

### ISSUE THREAD

**Issue by rahaaatul** [recloudstream/cloudstream#15]
### Steps to reproduce

Open the app, and try to navigate UI.

### Expected behavior

Should run smoothly.

### Actual behavior

Lags, delays, freezes.

### Cloudstream version

3.1.2

### Android version

Android 5.1 (Smart TV)

### Other details

Other apps like, STN Beta, Nova Video Player, VLC, Chrome, Saikou, runs smoothly, only this app lags on my device. And it's just not now, it's been happening for since I've started using this app on tv. On the other hand, it runs smooth on my phone.

I hope you will fix this issue for me, thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by walterdure** [comment]
> ### Steps to reproduce
> Open the app, and try to navigate UI.
Lag is not a problem with the application. Any smart tv or smart box with any relatively recent 4 core SOC works fine. You should check which one comes with your TV with AIDA64.
It is true that the UI needs to be adapted to remote control operation. Something more Stremio style. But you have to give it time, the development will mature.

**Comment by ixiumu** [comment]
When the source exceeds 10 categories
It will be very slow when switching home tab
I have this problem on both my old phone and fire tv

**Comment by LagradOst** [comment]
should be fixed in pre
