### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by dotkeenan** [recloudstream/cloudstream#151]
### Steps to reproduce

Try to open the app

### Expected behavior

The app should stay open and be usable

### Actual behavior

Shows black loading screen with red logo for a second.
Crashes back to homescreen.

### Cloudstream version and commit hash

version 3.1.5-PRE 661f8c3

### Android version

11

### Logcat

```java
Can't get into the app
```

### Other details

Worked normally before this update.
Same issue was brought up previously but was incorrectly closed, as it was believed to be similar to another issue (which it is not.  The player doesn't crash during playback, the entire app crashes on launch).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Gottarocket** [comment]
Same issue happens on my end now. But doesnt happen on new install. Cant clear storage because I havent exported recent backup

**Comment by ITADORI-15** [comment]
Same issue with me as well
Device Samsung M30

**Comment by ITADORI-15** [comment]
I tried but didnt get any crash log....it says no crashes yet...
