### ISSUE TITLE
Long press on search button to show keyboard 

### ISSUE THREAD

**Issue by manaafi** [recloudstream/cloudstream#154]
### Describe your suggested feature

Would be a small but convenient change to the search button on the bottom bar, if the keyboard would show up on long press. Instagram, for example, does the same.

Currently, long pressing any button shows a toast of what the button does, which is redundant since it's already shown below the button icon. 

### Other details

![Screenshot_2022-10-15-18-53-07-42_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/18599175/195988742-07931dcb-3260-405d-b31a-862bb0863728.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No, the reason why not is because android and keyboard is fucked fr. doing any sort of action that brings up search will fuck over like 10% of the users with super random bugs. Autoshow search has already been tried, but was removed after a lot of bugs caused by fucked android versions.
