### ISSUE TITLE
Add Skip ED button on full screen player UI

### ISSUE THREAD

**Issue by rohan2000github** [recloudstream/cloudstream#159]
### Describe your suggested feature

Just like the Skip OP option appears for about the first 50% of the anime video length after that Next episode option appears. So my request is to add the Skip ED alongside the Next episode option after the Skip OP disappears

Suggestion: Just simply don't let it dissappear and rename it to " Skip OP/ED "

### Other details

![Screenshot_2022-10-16-09-23-30-97_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/62375786/196115925-08ba4cea-195a-4654-ac19-45fd75ee6adf.jpg)
![Screenshot_2022-10-16-09-23-36-07_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/62375786/196115935-ac70e9bf-7584-4e3a-a8c2-d22f67171bba.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No
