### ISSUE TITLE
Changing the size of the Posters

### ISSUE THREAD

**Issue by b0ogdan** [recloudstream/cloudstream#162]
### Describe your suggested feature

Hello.
First of wall thank you very much for this app !
It would be possible to add the option to choose larger posters on the home screen. I sometimes use the  app in my car`a headunit and the posters are a bit small...if it`s not too much trouble could you please add this option. 
Thank you very much!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
wdym your car? 🤨 you shouldn't watch movies while you drive

**Comment by LagradOst** [comment]
No
