### ISSUE TITLE
No longer works in Bluestacks/Android emulators?

### ISSUE THREAD

**Issue by Darthagnon** [recloudstream/cloudstream#166]
### Steps to reproduce

I used the previous Cloudstream3 in Bluestacks v5.5 Nougat32 without problems for ages. Attempting to install the new version leads to "Installation failed". Bluestacks is an Android emulator for Windows.

Is it now targeting a new API level or are errors expected when installing over the previous version?

### Expected behavior

Cloudstream should install in Bluestacks and other Android emulators, over or alongside the old version.

### Actual behavior

It does not, and installation fails.

### Cloudstream version and commit hash

570fdb5af4adcbc29b8943ea0c9373faa4685136

### Android version

Android 7 (Nougat32, Bluestacks v5.5)

### Logcat

```java
N/A, error is on installation
```

### Other details

Cloudstream3 (some old version) works fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
nope it still targets sdk 21, it may fail because the old prerelese had different signing keys.
