### ISSUE TITLE
Lack of unit testing

### ISSUE THREAD

**Issue by wyso-rdb** [recloudstream/cloudstream#173]
### Describe your suggested feature

Our application would work better if we've got a better set of tests. In order to do this I would recommend to use Spock for unit testing and integration test purposes

### Other details

I have a branch with this config but im not able to push the branch

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
I have already written unit tests, but no one uses them
