### ISSUE TITLE
لا يوجد سيرفرات في بلدي (العراق) يرجى حل المشكلة باسرع وقت وشكرا

### ISSUE THREAD

**Issue by haidariq** [recloudstream/cloudstream#174]
### Steps to reproduce

لا يوجد سيرفرات في بلدي (العراق) يرجى حل المشكلة باسرع وقت وشكرا

### Expected behavior

لا يوجد سيرفرات في بلدي (العراق) يرجى حل المشكلة باسرع وقت وشكرا

### Actual behavior

لا يوجد سيرفرات في بلدي (العراق) يرجى حل المشكلة باسرع وقت وشكرا

### Cloudstream version and commit hash

Cloudstream

### Android version

android 11

### Logcat

```java
لا يوجد سيرفرات في بلدي (العراق) يرجى حل المشكلة باسرع وقت وشكرا
```

### Other details

لا يوجد سيرفرات في بلدي (العراق) يرجى حل المشكلة باسرع وقت وشكرا

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [ ] I have written a short but informative title.
- [ ] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [ ] If related to a provider, I have checked the site and it works, but not the app.
- [ ] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
English
