### ISSUE TITLE
Add MXPlayer as a video player

### ISSUE THREAD

**Issue by emiljanododa** [recloudstream/cloudstream#175]
### Describe your suggested feature

Since MX PLAYER is a really great and stable video player , I would love to see it as an option in order to stream videos through the app .
Thanks

### Other details

Here is the mx player api usage : 
https://mx.j2inter.com/api

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Not open source
