### ISSUE TITLE
New amazing UI✨

### ISSUE THREAD

**Issue by MrConqueror** [recloudstream/cloudstream#177]
### Describe your suggested feature

This UI looks so Good it suits the apps well. Very neat.

### Other details

![Screenshot_2022-10-25-18-37-35-591_com bongngotv2](https://user-images.githubusercontent.com/102837820/197757879-3a56cead-4b1b-49ce-bc04-441ff6a5af09.jpg)
![Screenshot_2022-10-25-19-06-40-759_com bongngotv2](https://user-images.githubusercontent.com/102837820/197758837-32217a02-3346-4254-8145-b5df5649441b.jpg)
![Uploading Screenshot_2022-10-25-19-06-40-759_com.bongngotv2.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by MrConqueror** [comment]
This is Vietnam app (cs3 base) Anyway since it's Viet language i tried to set language into English, but still the same, I demand for a UI like this please...

**Comment by C10udburst** [comment]
this cloudstream clone is essentially breaking the GPL3 license because its not opensource

**Comment by MustardChef** [comment]
Looks too good, we need this layout to elevate Cloudstream to the next level!

**Comment by imurreflection** [comment]
Where do I get this Vietnamese CS apk?

**Comment by MustardChef** [comment]
> Where do I get this Vietnamese CS apk?

This app violates the GPL license as it is closed-source, and we will not allow it to be mentioned here until it is 100% fully open-source.

**Comment by imurreflection** [comment]
I just wanted to experience this interface myself but i completely understand it. Thank you
