### ISSUE TITLE
subtitles capslock

### ISSUE THREAD

**Issue by imxcr** [recloudstream/cloudstream#18]
little request if possible to have an option to turn on/off subtitles font all uppercase
![IMG_20220809_220351.jpg](https://user-images.githubusercontent.com/98096677/184907522-95d0a5e3-e8aa-4c5d-a8a8-90e7e36bafa1.jpg)
![Untitled568_20220816223947.png](https://user-images.githubusercontent.com/98096677/184907705-90d70055-c47a-4e52-af85-927c96db441b.png)

**Comment by Blatzar** [comment]
Sure, I can take a look
