### ISSUE TITLE
Add fullscreen button

### ISSUE THREAD

**Issue by red9350** [recloudstream/cloudstream#180]
I'm currently using CloudStream on Windows using WSA (Windows Subsystem for Android), a kind of android emulator native to Windows 11.
The app works flawlessly, the only problem i have is the video player is missing a Fullscreen button, so if I want to watch a movie in fullscreen i have to press F11.
So i'm asking if it would be possible to add a fullscreen button to the app's video player

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
I don't think that is possible.

**Comment by red9350** [comment]
I think it's automatically managed by windows, once it receives the "enter fullscreen" command from the video player. It should be tested though

**Comment by C10udburst** [comment]
well, the player already does this
