### ISSUE TITLE
Feature Request: old feature to new UI

### ISSUE THREAD

**Issue by JimZiii** [recloudstream/cloudstream#184]
### Describe your suggested feature

I really like the new UI, this is not my request but having it automatically scroll between top movies would be awesome, maybe even the possibility to scroll manually if you feel like it.

What I'm missing with this update is the search bar at the top that lets you search only on your chosen homepage provider. I prefer just searching on my main site and moving on to an advanced search on selected providers if i can't find it on my main.
Doesn't have to be a thin bar at the top, could be a floating magnifying glass (like the random button and homepage provider button) that opens a temporary search bar on-top.

I'd actually also like to request something similar for android tv, don't really care where it's located, could place a button in the sidebar all the way at the top that let's you search your selected home provider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
it is not finished
