### ISSUE TITLE
Extensions page is down

### ISSUE THREAD

**Issue by thanasistrisp** [recloudstream/cloudstream#186]
### Steps to reproduce

It gives a 404 error the github plugin page. 

### Expected behavior

To be able to download public extensions

### Actual behavior

No such thing happened 

### Cloudstream version and commit hash

latest

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Jirafey** [comment]
Completely the same issue here like for a week or so with 3.1.5 version.  I am also unable to search for anything to watch and to watch anything from the watch history

**Comment by C10udburst** [comment]
the website is [here](https://cloudstream.cf) now
