### ISSUE TITLE
Can't remember last position

### ISSUE THREAD

**Issue by tvnmguy** [recloudstream/cloudstream#188]
### Steps to reproduce

For example, I choosed latest uploaded movie list from home tab and scroll down very long to bottom and selected a movie, then 'Play' and 'Download' the movie option/page appeared. I changed my mind to select another movie next to the first selected movie, So I pressed the back button then It goes back to the Home page and doesn't remembering the last position. Seriously it's very inconvenient and also every time it makes the above procedure for selecting each movie/series.

### Expected behavior

For example;

https://user-images.githubusercontent.com/116799295/198956444-a3dd112a-a8f6-4cfc-9ba9-6e076c9a3801.mp4

### Actual behavior

https://user-images.githubusercontent.com/116799295/198955412-05749ef6-2726-43c8-ab31-951422e79837.mp4

### Cloudstream version and commit hash

3.1.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Not a bug, but I can understand

**Comment by Indranil012** [comment]
not completely fixed.

https://user-images.githubusercontent.com/48489074/211074380-8e6ae8fa-dc5c-4e9b-a8d7-a6852053ca9c.mp4

**Comment by venkat2305** [comment]
https://github.com/recloudstream/cloudstream/issues/301
