### ISSUE TITLE
Add Bookmark feature (Icon) for all thumbnail

### ISSUE THREAD

**Issue by tvnmguy** [recloudstream/cloudstream#189]
### Describe your suggested feature

Add Bookmark feature (Icon) on all thumbnail for convenient use.

### Other details

![IMG_20221031_133608](https://user-images.githubusercontent.com/116799295/198961146-17e06a61-2482-4f99-a05a-bb0e6786bdf1.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
no
