### ISSUE TITLE
Use `UPDATE_PACKAGES_WITHOUT_USER_ACTION` permission on android >=12

### ISSUE THREAD

**Issue by soredake** [recloudstream/cloudstream#190]
### Describe your suggested feature

By using this permission on >=a12 install prompts can be skipped and cloudstream can update itself silently in background.

### Other details

https://www.xda-developers.com/android-12-alternative-app-stores-update-apps-background/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Added in 751175b3f91abeef12d1504381ef0b1d4601f83e i think?

**Comment by Blatzar** [comment]
Yes :pray:
