### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by Vortex786** [recloudstream/cloudstream#191]
### Describe your suggested feature

The epsiode selection list and the series information tabs can be improved.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Vortex786** [comment]
> ### Describe your suggested feature
> The epsiode selection list and the series information tabs can be improved.
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

Like the synopsis looks odd just fading halfway.

**Comment by LagradOst** [comment]
no info
