### ISSUE TITLE
Subtitles Elevation?

### ISSUE THREAD

**Issue by imurreflection** [recloudstream/cloudstream#194]
Hi, with new updates both on Stable and Beta releases subtitles Elevation for "None" is not working. The position does not change. I revert back to 3.1.15 and there is no such issue. Thank you

**Comment by imurreflection** [comment]
This is strange..i asked a simple question yet there is no response..

**Comment by imurreflection** [comment]
As expected no response. Thank you

**Comment by C10udburst** [comment]
??? do u expect someone to respond 2 u within 2 days?

**Comment by imurreflection** [comment]
Dear @balatzar. Thank you for fixing this.
