### ISSUE TITLE
I keep finding Jesus everytime I click a nsfw video

### ISSUE THREAD

**Issue by ugaugabuga** [recloudstream/cloudstream#196]
### Steps to reproduce

Try to watch any video from any nsfw source

### Expected behavior

Should play the actual content

### Actual behavior

It shows quotes from bible instead of the actual video

### Cloudstream version and commit hash

3.2.1 stable

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
<img src="https://cdn.discordapp.com/emojis/961719827695829012.png?size=48" width=24> Leviticus 15:16-17
