### ISSUE TITLE
Allow to "Set default source"

### ISSUE THREAD

**Issue by Plawaan** [recloudstream/cloudstream#200]
### Describe your suggested feature

It would be great if one can set a source as default:
This is useful whenever the first source is in lower resolution than let say the third source.

Thank you so much LagradOst for making such a great app 👍

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by venkat2305** [comment]
This would be helpful with sites like tenshi in which dub and sub are not separated.

**Comment by NightHammer1000** [comment]
+1 on this.
