### ISSUE TITLE
Make second tap on the search button as a trigger of keyboard popup

### ISSUE THREAD

**Issue by tvnmguy** [recloudstream/cloudstream#208]
### Describe your suggested feature

https://user-images.githubusercontent.com/116799295/201117981-e9fcff0c-9fc3-40fa-9208-fc85ab847980.mp4

### Other details

Inspiration from Spotify android app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
no, tried and dont work
