### ISSUE TITLE
Chromecast Cast v1 Protocol

### ISSUE THREAD

**Issue by orbisvicis** [recloudstream/cloudstream#213]
### Steps to reproduce

1. Install [tubecast](https://github.com/enen92/script.tubecast) for Kodi which allows casting to Kodi with the Cast v1 protocol.
2. Verify that casting to Kodi from Google's Youtube app is working.
3. Notice that Cloudstream does not find any cast-compatible devices, so the cast button is hidden.

Can the Cast v1 protocol be enabled with a simple compile-time flag? Or does whichever library used by Cloudstream simply not support the Cast v1 protocol? Will this be fixed?

### Expected behavior

Cast button should not be hidden.

### Actual behavior

Cast button is hidden.

### Cloudstream version and commit hash

3.2.4 3e2c53af

### Android version

Android 12

### Other details

Read release notes so did not actually test latest pre-release version.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by walterdure** [comment]
Tubecast works only to cast from the youtube app to Kodi and nothing else.
I think that in your case you should look for a plugin to access movies and series from Kodi itself. Or get a cheap chromecast 2.

**Comment by orbisvicis** [comment]
> Tubecast works only to cast from the youtube app to Kodi and nothing else.

[Confirmed](https://github.com/enen92/script.tubecast/blob/d90ce77f3f83f4931fb455e58fdf1abd08c4ca33/resources/lib/tubecast/dial.py#L55), unfortunately. I also tested with BubbleUPnP and VLC.
