### ISSUE TITLE
Selected IPTV Country fails to show channels after being marked

### ISSUE THREAD

**Issue by Gthbacc** [recloudstream/cloudstream#214]
Steps to reproduce

1. Switch to IPTV-ORG
2. Select the country of your choice
3. Mark it as your wish (Completed, Plan to Watch, On-Hold, etc ...)
4. Return to the main screen or switch to another provider & select the recently marked Country Playlist.
5. Error

Expected behavior

It is supposed to show the proper list of channels.

Actual behavior

The following error is shown:

![](https://i.ibb.co/481MKJ4/Imagepipe-0.jpg)

Cloudstream version and commit hash

3.2.3 PRE

Logcat

Other details

Thanks in advance.

Acknowledgements

✓ I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open issue.
✓ I have written a short but informative title.
✓ I have updated the app to pre-release version Latest.
✓ If related to a provider, I have checked the site and it works, but not the app.
✓ I will fill out all of the requested information in this form.

**Comment by Gthbacc** [comment]
Not sure if this is related to the provider. Seems like a cloudstream issue.

**Comment by C10udburst** [comment]
> Not sure if this is related to the provider. Seems like a cloudstream issue.

I'm pretty sure this is a provider issue
