### ISSUE TITLE
Opening/Ending Anime

### ISSUE THREAD

**Issue by mormmi** [recloudstream/cloudstream#216]
### Steps to reproduce

You can't skip the ending, only the opening disappears, the option to skip, if you can fix that option

### Expected behavior

Skip the ending and opening

### Actual behavior

You can't skip the ending, only the opening disappears, the option to skip, if you can fix that option

### Cloudstream version and commit hash

3.2.4 3e2c53a5

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Skip OP button is intentionally removed to make room for the next episode button, not a bug.

**Comment by Indranil012** [comment]
> Skip OP button is intentionally removed to make room for the next episode button, not a bug.

The previous implementation was better, if there is an op show op button, else show next episode button.

**Comment by Blatzar** [comment]
> The previous implementation was better, if there is an op show op button, else show next episode button.

Meaning? That is not how it has ever been.

**Comment by Indranil012** [comment]
> Meaning? That is not how it has ever been.

Then I request you to make it like that.😁

**Comment by Blatzar** [comment]
We can't know for certain there's not an op hence we can't remove the op button haphazardly.

**Comment by Indranil012** [comment]
> We can't know for certain there's not an op hence we can't remove the op button haphazardly.

How doy check if there is a op?

**Comment by Blatzar** [comment]
It is like sponsorblock and it is not available on all providers due to cross referencing issues, and not all shows because no database is complete.

**Comment by Indranil012** [comment]
> It is like sponsorblock and it is not available on all providers due to cross referencing issues, and not all shows because no database is complete.

So, when video starts you know where are those op is isn't it?
Then you you can decide you should show op button or next button.

**Comment by Blatzar** [comment]
You can not make any assumptions like that, precisely because we cannot know anything for certain :neutral_face: 
No further input is wanted
