### ISSUE TITLE
Can't add extensions on Chromecast with Google TV

### ISSUE THREAD

**Issue by Weab-chan** [recloudstream/cloudstream#22]
### Steps to reproduce

Title pretty clear

### Expected behavior

Title pretty clear

### Actual behavior

Title pretty clear

### Cloudstream version

latest

### Android version

Android 10 TV

### Other details

There's no way to copy and paste manually.. I could likely use a bt keyboard maybe but is that a solution...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by walterdure** [comment]
I have TV BRO browser installed. When from the cloudstream app it redirects to the extensions web page, I simply click on the install option and it will automatically be added. No more copying and pasting like before.

**Comment by Weab-chan** [comment]
I'll try with tv bro, if it does work.. maybe suggest using it on that extension setting page...

**Comment by Weab-chan** [comment]
Looks like it's fine with TV Bro.. When you add the Extractors repository, you need to press the download button top right corner after the repo was added right? Also how does updating the source work? you just press download again on that repo?

**Comment by C10udburst** [comment]
> Also how does updating the source work
 
its automatic

**Comment by Blatzar** [comment]
Is this solved?
