### ISSUE TITLE
metadata view

### ISSUE THREAD

**Issue by Light7654** [recloudstream/cloudstream#226]
### Describe your suggested feature

![Screenshot 2022-11-17 232835](https://user-images.githubusercontent.com/87866912/204169263-4a562856-4c07-4f35-971f-7a17e3d64525.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
What?
