### ISSUE TITLE
Reminder of quicknovel

### ISSUE THREAD

**Issue by Light7654** [recloudstream/cloudstream#227]
### Describe your suggested feature

@LagradOst It's a reminder for you that you also have quicknovel app it's a great app but it doesn't get any updates since 3 months

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
<img src="https://cdn.discordapp.com/emojis/973302190670249984.gif" alt=":diesfromcringe:" width=24> I don't think you even realise how entitled you sound here.
