### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by fugkco** [recloudstream/cloudstream#230]
### Describe your suggested feature

It would be nice to add an option to play videos faster or slower (e.g. 1.25x, 1.5x, etc), similar to what YouTube and Netflix do on their mobile apps. This probably mostly makes for mobile apps, at least with Netflix, they don't have the option on TVs etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Already present in the app, explore settings before requesting stuff please.

**Comment by fugkco** [comment]
Aah interesting. I probably missed it because it's labelled "Eigengravy Mode". Is there a reason for this? Seems like it would be more user friendly if it is labelled as "playback speed" or something.

**Comment by C10udburst** [comment]
cc @eigengravy
