### ISSUE TITLE
Weblate Integration for Easy Translations

### ISSUE THREAD

**Issue by ShareASmile** [recloudstream/cloudstream#247]
Please consider Weblate Integration for Easy Translations.

Weblate is an opensouce web tool, helps to do Translations in an easy & organized way, Others can watch , correct Translations on weblate on the go in the languages they know.

**Comment by C10udburst** [comment]
isn't weblate paid if not selfhosted?

**Comment by ShareASmile** [comment]
It is free, https://hosted.weblate.org/
a lot of open source apps like NewPipe
https://github.com/TeamNewPipe/NewPipe
Droid-ify
https://github.com/Iamlooker/Droid-ify
devs use it.
You can read discussion to compare it with Crowdin.
mumble-voip/mumble#4641

**Comment by ShareASmile** [comment]
I don't understand why crowdin is being selected for translations in this repo inspite of better open source alternative Weblate ? 
cc @comradekingu

**Comment by LagradOst** [comment]
I dont care what translstion tool we use, just if it works, is easy and is free

**Comment by comradekingu** [comment]
Then Weblate or translatewiki it is. My preference is the former.

**Comment by ShareASmile** [comment]
I am just saying Read reviews by a trusted translators before deciding on which service to use

e.g read comment about Crowdin https://github.com/BrightDV/BoxBox/issues/21#issuecomment-1336158232

**Comment by comradekingu** [comment]
Crowdin is a non-starter.
It adds the wrong locales, pits good effort against the impetus to wait around for someone else to agree a translation should be changed… Between not getting any consistency for that reason and not being able to see more languages at once and span many strings at once, it all falls victim to the lack of community. This in turn is subject to the worst possible terms, which keeps people that know better away.

**Comment by C10udburst** [comment]
Sure, I've set up weblate trial and requested approval:

https://hosted.weblate.org/projects/cloudstream/app/

**Comment by ShareASmile** [comment]
As project on weblate is in trial setup period i think contributors should wait.

>This project is in a trial period, be cautious while contributing. Setup can still change before being approved as a libre project.

**Comment by C10udburst** [comment]
> Hello, I would like to collaborate with the Spanish translation of the app since it is currently incomplete and does not appear among the languages ​​available on weblate.

You can create a new translation on weblate
