### ISSUE TITLE
"All" button missing in search filters 

### ISSUE THREAD

**Issue by NR8124** [recloudstream/cloudstream#25]
### Describe your suggested feature

Option to select/deselect all the providers in one check

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Long press whatever tag you have selected and all providers become visible

**Comment by NR8124** [comment]
![Screenshot_2022-08-19-22-14-35-98_cfa2fd239c8cded9285432912d0e0818](https://user-images.githubusercontent.com/88180887/185667412-fde3363b-e769-4f49-9ff8-d644a59852a4.jpg)

I was asking to add a Button named "All" 
Above all these providers
So that i can select all of them by just one click

**Comment by Blatzar** [comment]
Rejected, you can long press all the buttons if you want all displayed.
We already have so many providers it'd be useless to make it a dedicated button.
