### ISSUE TITLE
Independent Brightness and Volume Settings and Remembered Settings

### ISSUE THREAD

**Issue by KazKaz90** [recloudstream/cloudstream#252]
### Describe your suggested feature

It would be much more convenient for users if CloudStream had its own brightness and volume settings, rather than relying on the phone's settings. It would also be really helpful if the app could remember these settings, so that users don't have to constantly adjust them every time they use the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
That is so shit and I choose to not do that because I hate that netflix does that. NO

**Comment by KazKaz90** [comment]
> That is so shit and I choose to not do that because I hate that netflix does that. NO

Would it be possible to make this feature optional, allowing users to enable or disable it whenever they want? I understand that not everyone may like this feature, but I think some people might find it useful.

**Comment by LagradOst** [comment]
No, bloat
