### ISSUE TITLE
Add Option for hide featured movies / serials

### ISSUE THREAD

**Issue by Ajtak** [recloudstream/cloudstream#253]
### Describe your suggested feature

Please add option into Providers options for hide featured moveis/serials.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
why???
