### ISSUE TITLE
Unable to install plugins from the extensions

### ISSUE THREAD

**Issue by AvAkanksh** [recloudstream/cloudstream#258]
### Steps to reproduce

1.  I have installed the cloudstream app on my Android TV(a smart tv with MI box 4k)
2.  Then i have gone to the extensions section and added the repositories which are mentioned in the official website
3.  Then I have restarted the app
4.  On launching the app I got the option to install the plugins
5. Then I have selected the download option beside each extension

### Expected behavior

It should prompt that it has started installing xx plugins.
Then I should prompt installed xx plugins

### Actual behavior

1. Instead i was begin prompted that all the plugins have been installed.(which was not the case)
2. So inorder to check if all the plugins were installed or not i went back to the extensions section but it still showed me 0 plugins download.

### Cloudstream version and commit hash

3.2.4

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
You are likely in India where they block raw.githubcontent links. This is not a bug, they are simply blocking the text files to read the repository (like wtf).

We'll probably add a fallback to the normal gh or something :shrug:

**Comment by Blatzar** [comment]
Use a VPN and try using DNS over HTTPS

**Comment by AvAkanksh** [comment]
Thanks a lot @Blatzar it did work. 

I have a small suggestion for the website maintenance person as you know that [raw.githubusercontent.com](raw.githubusercontent.com) is not working for every location you could use [raw.githack.com](raw.githack.com), then everyone can use the same link irrespective of the location.

Thank you for your quick response
