### ISSUE TITLE
Bottom Nav Bar UI buggy in Settings 

### ISSUE THREAD

**Issue by eigengravy** [recloudstream/cloudstream#26]
- Settings submenus don't update the nav bar to highlight settings, it stays in the previous state. Buggy when user switches from another screen like Home to a Settings submenu.
- Also when you are on a settings sub screen and tap settings in bottom bar, its expected to take you to settings page but it doesn't.

Proposed easy fix: Hide bottom nav bar when entering a settings submenu

cc: @LagradOst , @Blatzar

**Comment by eigengravy** [comment]
Proposed hard fix: Fix 🫠

**Comment by C10udburst** [comment]
![image](https://user-images.githubusercontent.com/18114966/185669415-b1267644-780e-4795-8d4b-934add23327d.png)

yeah
