### ISSUE TITLE
Problem with in app updater

### ISSUE THREAD

**Issue by venkat2305** [recloudstream/cloudstream#264]
### Steps to reproduce

Update the app to latest pre release. It's reproducible in miui 13

### Expected behavior

The app should be updated 

### Actual behavior

The app isn't updating 

https://user-images.githubusercontent.com/55329452/208838763-212261fd-a159-4851-8c1d-8fa5c46c03cc.mp4

### Cloudstream version and commit hash

3.3.0 

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by SCP-017** [comment]
Same, `Redmi 6a` `MIUI 11.0.5` (`Android 9`).

After the app download on background, the app doesn't update like it used to before...

**Comment by venkat2305** [comment]
Looks like it's specific to miui. Let's wait till Devs get time to fix it

**Comment by venkat2305** [comment]
Legacy installer option fixes this issue.

**Comment by SCP-017** [comment]
@venkat2305 

Thanks for the info, worked on me after I pressed update. You should now close the issue.

**Comment by venkat2305** [comment]
Maybe , they might fix the issue with the package installer option for miui devices when they have time.

**Comment by C10udburst** [comment]
Switch to legacy mode in settings > updates > apk installer
