### ISSUE TITLE
Restore settings file picker does not work on tv

### ISSUE THREAD

**Issue by AfromD** [recloudstream/cloudstream#268]
### Steps to reproduce

Use fire tv stick
Go to settings restore dialog
Try to navigate

### Expected behavior

The navigation cross should allow focus to the needed files and folders and then the center action button should select the file or folder 

### Actual behavior

The remote buttons do not work on this file picker dialog. The dialog is not compatible with the remote control

### Cloudstream version and commit hash

3e2c53a5

### Android version

Fire Tv os 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
You need to install a good file manager

**Comment by AfromD** [comment]
Cloudstream uses the default android file picker, which is not compatible with TV remotes. There is no option to configure another file picker.

**Comment by Blatzar** [comment]
You are incorrect.
It uses any compatible file picker, it's not hardcoded.
Download AnExplorer and see for yourself.

**Comment by AfromD** [comment]
AnExplorer is broken on Fire TV.
Found "Little File Explorer" on F-droid which works.
