### ISSUE TITLE
Virus found in app by quick heal.

### ISSUE THREAD

**Issue by upendra-bajpai** [recloudstream/cloudstream#269]
### Steps to reproduce

Just run quick heal 

### Expected behavior

Clean app

### Actual behavior

Virus found <b>kokbot.gen50113 </b>
![IMG-20221223-WA0002](https://user-images.githubusercontent.com/17337388/209355188-8346692a-99da-4927-9a4d-b378889f2b93.jpg)

### Cloudstream version and commit hash

3.2.4 3e2c53a5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
bad antivirus 🥱

**Comment by C10udburst** [comment]
look at the source if you are unsure of the fact that this app is safe
