### ISSUE TITLE
Add a Library option

### ISSUE THREAD

**Issue by himanshu8443** [recloudstream/cloudstream#294]
### Describe your suggested feature

Add a separate library option for where shows can be added  and to create own categories other than watching, plan to watch, completed. instead of showing on homepage

### Other details

![Screenshot_20221229-192651](https://user-images.githubusercontent.com/99420590/209963649-b30e5d0d-8065-4375-a313-14f850411fe7.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by shubham01015** [comment]
![unknown-1.png](https://user-images.githubusercontent.com/74341381/209970051-ffbcbd41-90cd-4686-834d-3df3e5835d8a.png)

**Comment by himanshu8443** [comment]
> ![unknown-1.png](https://user-images.githubusercontent.com/74341381/209970051-ffbcbd41-90cd-4686-834d-3df3e5835d8a.png)

Where to enable not showing in my device

**Comment by himanshu8443** [comment]
> ![unknown-1.png](https://user-images.githubusercontent.com/74341381/209970051-ffbcbd41-90cd-4686-834d-3df3e5835d8a.png)

Where to enable it  not show in my device
