### ISSUE TITLE
New major update

### ISSUE THREAD

**Issue by jackuars7** [recloudstream/cloudstream#302]
### Describe your suggested feature

How frequently are new updates being rolled out? The last major version (3.2.4) was released back in November. Since then there were certain beta updates but from what I have seen the beta updates doesn't upstream from an earlier update. For example in one of the big reports i had mentioned that mpv playback doesn't remember it's last position, which was corrected in a later update. But then another beta update released post that didn't have that feature anymore which is frustrating.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jackuars7** [comment]
Okay, let me test the latest beta then. Does the beta versions have the changes made from 3.2.4 as well?

**Comment by Blatzar** [comment]
> it doesn't save the progress of mpv playback

False, but I can see the confusion about it since MPV does not report back the duration and position sometimes, for example on family guy S1E1 on SuperStream, this is an MPV issue and not a cloudstream one. 

https://user-images.githubusercontent.com/46196380/212900707-0c60534c-6130-416e-a04f-630e59b44e88.mp4

**Comment by jackuars7** [comment]
I use Superstream primarily too and it happens for the THE Shield TV series. So is it an issue for Superstream, or it just happens on certain TV series
