### ISSUE TITLE
Currently version doesn't open on Android 11

### ISSUE THREAD

**Issue by LincCodes** [recloudstream/cloudstream#304]
### Steps to reproduce

Open I open it, it crashes (closes)

### Expected behavior

It should open

### Actual behavior

It crashes

### Cloudstream version and commit hash

3.40 36e780f (current pre version)

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
What is your language setting within the app

**Comment by LincCodes** [comment]
English
