### ISSUE TITLE
Arabic providers disappeared

### ISSUE THREAD

**Issue by Mua10** [recloudstream/cloudstream#306]
### Steps to reproduce

All Arabic providers disappeared suddenly

### Expected behavior

Providers should appear

### Actual behavior

Arabic providers not appearing

### Cloudstream version and commit hash

Version 3.2.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by TubaApollo** [comment]
Sadly the repo provider for the arabic repository got banned from github, with this also the repo got unavailable. You can expect it to be fixed soon, just update to the newest pre-release today/tomorrow.

**Comment by iyaz57** [comment]
me to a cant find them

**Comment by TubaApollo** [comment]
The repo is up again, please check the discord or the website

**Comment by Mua10** [comment]
>
