### ISSUE TITLE
Remove google admob

### ISSUE THREAD

**Issue by Donkey-Doug** [recloudstream/cloudstream#307]
### Describe your suggested feature

Google admob is present in this app. Please remove it for privacy reasons.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
There is no admod present, not sure where you got this information from
![image](https://user-images.githubusercontent.com/11805592/211764094-9c2f3539-86d4-4267-bab2-a603e3614d53.png)

**Comment by Donkey-Doug** [comment]
According to the Exodus project, admob is present in the latest version of the app:

![Screenshot_20230111-111847_Exodus](https://user-images.githubusercontent.com/50382414/211781008-8c49727b-6400-4ae5-81e4-18cd45c71cf3.png)

**Comment by Blatzar** [comment]
Open in browser and you'll arrive at
https://reports.exodus-privacy.eu.org/en/reports/231221/
Notably the app icon is different, signature fingerprint is also different and it links to a now dead play store link. Someone uploaded cloudstream to the play store with ads.

Please do some verification in the future.

**Comment by Donkey-Doug** [comment]
Oh wow! Does this mean that I have the clone with ads installed on my device?

**Comment by Blatzar** [comment]
It says nothing about the actual installed app as exodus only used package id, but install the apk from github and it'll prompt an update which will only succeed if the current app is ours.

**Comment by LagradOst** [comment]
> Oh wow! Does this mean that I have the clone with ads installed on my device?
> 
> I have the exodus app that scan my apps.

If you see ads then you are using the wrong version. This repo has no ads, nor tracking (besides crash logging that you can disable). Download the correct version here: https://github.com/recloudstream/cloudstream/releases and not from playstore
