### ISSUE TITLE
Hi can you please add the episode titles instead of it being episode 1 /2 etc... Thanks alot

### ISSUE THREAD

**Issue by Kivalkk** [recloudstream/cloudstream#308]
### Describe your suggested feature

The title of series episodes instead of the current episode 1 / 2 etc..

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
That is up to the provider, we cant simply do magic and get titles from nowhere.
