### ISSUE TITLE
New behaviour for long press/press and hold on a thumbnail

### ISSUE THREAD

**Issue by tvnmguy** [recloudstream/cloudstream#309]
### Describe your suggested feature

Make long press/press and hold on a thumbnail more practical instead of showing title only.

### Other details

Before;
![Screenshot_2023-01-13-16-43-43-471_com lagradost cloudstream3 prerelease](https://user-images.githubusercontent.com/116799295/212307315-2635c7c8-0588-4013-b236-2354be7a964e.jpg)

After;
![img_2023_01_13_16_38_29](https://user-images.githubusercontent.com/116799295/212307499-3f808dc3-e487-4957-a345-3765e693b527.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
duplicate + added + L + try prerelease

**Comment by AbdullahM0hamed** [comment]
+ RATIOOOOOOOOOOOOOOOOOOOOOOOOOO
