### ISSUE TITLE
Simkl integation

### ISSUE THREAD

**Issue by rollingmoai** [recloudstream/cloudstream#318]
### Describe your suggested feature

#122 but for Simkl. Ability to automatically sync watched shows to Simkl

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by dontseehereThomas** [comment]
+1

**Comment by edl2** [comment]
+1 would love to see this. Smkl tracking is already in aniyomi as well, and the API is really good
