### ISSUE TITLE
No option to cast a downloaded file 

### ISSUE THREAD

**Issue by SANCTI-afk** [recloudstream/cloudstream#32]
### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Cloudstream version

3.1.3

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Use vlc to cast downloaded files, the reason why this is not a standard feature is because of the shitty chomecast api. it will never be added, not because it is not possible, but because it would require a major coding effort to 1. decode it, 2. stream it

**Comment by SANCTI-afk** [comment]
Actually I didn't demand this for myself... I don't use casting usually since I have cs installed on my tv..I asked for the community but if it needs much efforts so anyone concerned with casting could go with any external app like vlc as you mentioned
