### ISSUE TITLE
versioncode

### ISSUE THREAD

**Issue by IzzySoft** [recloudstream/cloudstream#326]
### Describe your suggested feature

As it happened for the second time now I just wonder what causes two subsequent releases sharing the same `versionCode`. This happened with vc 51 and now again with vc 56. Is that something intentional, or a "misled workflow" that should be fixed?

### Other details

Updater at my repo always gets confused and wants to quarantine the app :wink:

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Not sure why but the versioncode somehow got rolled back when switching workflows or smth, I incremented right before release from 55->56, but the last update also has 56 for some reason.

**Comment by C10udburst** [comment]
It may have to do with this line:

https://github.com/recloudstream/cloudstream/blob/master/app/build.gradle.kts#L98
