### ISSUE TITLE
No media works of "egybest" provider.... it's the most important and common provider for arab as it has the most big subbed library... so quick fix would be a charm dream..the implementation looks good to me but it should be an error somewhere in the code 

### ISSUE THREAD

**Issue by SANCTI-afk** [recloudstream/cloudstream#33]
### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Cloudstream version

3.1.3

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the discord.

**Comment by SANCTI-afk** [comment]
@C10udburst 
I know it's... but this provider comes from the public repo you shared so I thought you are affiliated with ..sorry for that confusion you made it clear now keep the good work
