### ISSUE TITLE
Ability to use Kodi addons

### ISSUE THREAD

**Issue by Govind-Rajulu** [recloudstream/cloudstream#331]
### Describe your suggested feature

It would be a great feature if we could use Kodi addons in CS app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
infeasible
