### ISSUE TITLE
Support for Samsung tizen tv

### ISSUE THREAD

**Issue by Adithyan007hack** [recloudstream/cloudstream#332]
### Describe your suggested feature

Hello bro I love this app I am running it on two of my devices but it is not available on my tv.
My tv is Samsung and running Tizen os apks cannot be installed there 
It would be nice if there were a package for Tizen tv also

### Other details

Media servers streaming services like Emby media and jellyfin has packages for Tizen that you put the packages on a USB and the installation starts automatically 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by anotherduckling** [comment]
Not possible. Because it's not android. Buy an android box.

**Comment by ThatOneCalculator** [comment]
@anotherduckling your comment is misleading -- it would be possible to port to Tizen with fairly minimal effort with OACL.

**Comment by LagradOst** [comment]
> @anotherduckling your comment is misleading -- it would be possible to port to Tizen with fairly minimal effort with OACL. 

you are free to pr that

**Comment by Adithyan007hack** [comment]
So can i expect a tizen app in future?

**Comment by Cart1416** [comment]
never!!!!

**Comment by Adithyan007hack** [comment]
> @anotherduckling your comment is misleading -- it would be possible to port to Tizen with fairly minimal effort with OACL.

can do that?

**Comment by ThatOneCalculator** [comment]
If you want to do that, go ahead. I no longer use my Samsung TV's "smart" features as I got a dedicated Chromecast for CloudStream.

**Comment by Adithyan007hack** [comment]
So I'm just pulling this issue up again 
if anyone is willing to contribute 
https://github.com/reisxd/TizenBrew/blob/main/docs/MODULES.md
