### ISSUE TITLE
Homepage provider & search buttons

### ISSUE THREAD

**Issue by eightyy8** [recloudstream/cloudstream#335]
### Describe your suggested feature

I recommend moving the homepage's provider button to it's search button (top left), and putting that search button to the far right.

Something like:

≡ SoupSeam⠀⠀⠀⠀⠀⠀🔍

                 Show
           +   [ Play ]   i

### Other details

That's all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Understandable, but idk

**Comment by eightyy8** [comment]
Sorta like Netflix's top layout. And when you scroll it just follows.

It's annoying having the provider button sitting right there...

**Comment by Blatzar** [comment]
I think this is a good idea barring the "≡ SoupSeam" part
I very much prefer having the provider button in the corner always accessible easily.

**Comment by eightyy8** [comment]
It seems as accessible as it needs to be, because most people just set it and leave it. And I would say that it's easy to get to, not as easy as a button right under your thumb. But most UIs have to have a compromise for user appeal - evening out accessibility and appealability.

You should do a vote if you're not sure though

**Comment by LagradOst** [comment]
no, this issue is closed I changed my mind. the bottom bar is used across many pages so it makes sense + easy to reach, I like it

**Comment by eightyy8** [comment]
OK...

**Comment by eightyy8** [comment]
Those options using the button aren't like the provider button, and it definitely won't ruin anything.

But whatever, your the boss 🥲
