### ISSUE TITLE
Support Apple's devices.

### ISSUE THREAD

**Issue by rokejulianlockhart** [recloudstream/cloudstream#338]
### Describe your suggested feature

This would allow targeting iOS, iPadOS, ARM-based macOS, and potentially tvOS. I believe that it is a significantly untapped market.

Additionally, with the EU's mandate that Apple deregulate its devices and 3rd-party application stores finally maturing, sideloading is reaching a point where it is almost as easy as on Android.

### Other details

https://github.com/recloudstream/cloudstream/issues/171#issuecomment-1405917910

### Acknowledgements

It separates something technically previous requested and provides additional rationale. I suppose that I'm just being a pedant by clarifying this, though.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by rokejulianlockhart** [comment]
@recloudstream, quite confident that I didn't mention ramen.

**Comment by anotherduckling** [comment]
Not going to happen. Devs dont have time. Also i dont think they care about the market.

**Comment by C10udburst** [comment]
Will not happen as it would require a whole rewrite of the app

**Comment by rokejulianlockhart** [comment]
Shame, but understandable.

However, I believe that due to the significant market that it would afford, such a decision shall be regretted.

Additionally, if this were to occur, it would have to be soon lest it become entirely infeasible.

**Comment by kvn1351** [comment]
> Shame, but understandable.
> 
> However, I believe that due to the significant market that it would afford, such a decision shall be regretted.
> 
> Additionally, if this were to occur, it would have to be soon lest it become entirely infeasible, whereas if focussed upon soon, it would provide a significantly more adaptive foundation to the codebase.

This greedy moron made my day. Thanks.
