### ISSUE TITLE
automatic dark/light mode switch on android 11 and lower

### ISSUE THREAD

**Issue by soyelmismo** [recloudstream/cloudstream#341]
### Describe your suggested feature

ik theres monet support but theres no system auto dark and light support for older android versions

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
duplicate

**Comment by soyelmismo** [comment]
> duplicate

Sorry, i couldnt find the og issue of this so i created it

**Comment by rokejulianlockhart** [comment]
@LagradOst, of which issue? (@soyelmismo, probably worth closing the issue since it's duplicate)

**Comment by soyelmismo** [comment]
> it's duplicate
![Screenshot_20230214-141758_Kiwi_Browser](https://user-images.githubusercontent.com/123757457/218835754-83a43ce9-5283-4470-b8af-a266ce7c7777.png)

**Comment by rokejulianlockhart** [comment]
The alternative issue was closed in favour of this one, so it's not duplicate anymore.

**Comment by b3il0** [comment]
I'd welcome a feature like this. It also seems also essential nowadays.

**Comment by MonuGit9** [comment]
Can you assign this task to me
