### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ITADORI-15** [recloudstream/cloudstream#353]
### Steps to reproduce

Open the app wait for 3 seconds

### Expected behavior

To open and stay still

### Actual behavior

Crashes

### Cloudstream version and commit hash

4.0.0-PRE

### Android version

Android 10

### Logcat

```java
Crashes before I am able to open this page
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
@Blatzar

**Comment by LagradOst** [comment]
does it crash if you have no internet access aka airplane mode?

**Comment by ITADORI-15** [comment]
No ...now it's fine
Idk why it happened before
I cleared data and cache and it started working

**Comment by papi028** [comment]
> does it crash if you have no internet access aka airplane mode?

yes im having same issue and it crashes when i have no internet access, sometimes i just wanna go and watch my downloaded stuffs
