### ISSUE TITLE
Don't reload video after subtitle change

### ISSUE THREAD

**Issue by eightyy8** [recloudstream/cloudstream#354]
### Describe your suggested feature

Currently cs3 will reload the subtitles _and_ the video whenever you make changes to a sub's source or syncing. This removes the video's loaded cache, so you have to wait for the video to unnecessarily load. And yes, I know, first world problems. But these minor problems add up and get really damn annoying.

So, if this isn't a bug, my recommendation would be to just load the subs by itself... if that's possible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
cant be done due to exo problem

**Comment by eightyy8** [comment]
> exo problem

Could you give a short explanation?

**Comment by LagradOst** [comment]
We have a custom subtitle renderer and parser, that needs to be reloaded to work, hence video reload upon delay change or lang change

**Comment by eightyy8** [comment]
> custom subtitle renderer/parser, that needs to be reloaded to work

Can you not customize it to fix this? Even though it's a small problem and seems larger to fix, it's not any less as a problem. _Sorry if that sounds aggressive_

@LagradOst
