### ISSUE TITLE
Some design changes for new library section

### ISSUE THREAD

**Issue by tvnmguy** [recloudstream/cloudstream#357]
### Describe your suggested feature

New 'Open with' icon

![IMG_20230204_095808](https://user-images.githubusercontent.com/116799295/216752090-902b296f-f76d-43f6-b7cf-aca05e9254d7.jpg)

New library logo like Spotify library logo

![IMG_20230204_113551](https://user-images.githubusercontent.com/116799295/216752110-19598aac-cb29-4937-a18e-f8aecfa22a6d.jpg)

### Other details

Like Search page design for consistency

![IMG_20230204_114206](https://user-images.githubusercontent.com/116799295/216752192-efc21509-91d1-4d27-bcdd-a4acb0b30029.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by eightyy8** [comment]
It should have a library icon, but the profile icon is fine when you're signed in with trackers.

**Comment by oathzed** [comment]
Disagree. Why would you make reachability worse?

**Comment by eightyy8** [comment]
> Why would you make reachability worse?

It's not moving anything, he's saying to change the icon (which currently is the extension icon for some reason).

**Comment by oathzed** [comment]
> > Why would you make reachability worse?
> 
> It's not moving anything, he's saying to change the icon (which currently is the extension icon for some reason).

Uhm, yes it is. Look at the top photo he's saying move the buttons to the top.

**Comment by eightyy8** [comment]
> > > Why would you make reachability worse?
> > 
> > It's not moving anything, he's saying to change the icon (which currently is the extension icon for some reason).
> 
> Uhm, yes it is. Look at the top photo he's saying move the buttons to the top.

Just realized... definitely not the way to go🫣

**Comment by oathzed** [comment]
That's just not good design sorry

**Comment by C10udburst** [comment]
Rotated text is terrible UX
