### ISSUE TITLE
Someone Stops reversing the layout for arabic language 

### ISSUE THREAD

**Issue by SANCTI-afk** [recloudstream/cloudstream#36]
### Describe your suggested feature

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
duplicate of #34?

**Comment by SANCTI-afk** [comment]
Seems like I'm cursed with that reverse for the end of my life
