### ISSUE TITLE
Follow System Theme

### ISSUE THREAD

**Issue by xmha97** [recloudstream/cloudstream#373]
### Describe your suggested feature

Please add the feature below:
- Follow the system theme (dark/light)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by wrightwriter** [comment]
Yeah most apps support this, would be very nice

**Comment by not-programmer98** [comment]
An essential feature nowadays
