### ISSUE TITLE
MPV playback resume issue

### ISSUE THREAD

**Issue by jackuars7** [recloudstream/cloudstream#374]
### Steps to reproduce

While playing episodes of a show on MPV, the latest played video doesn't appear under "Continue watching"  on homepage. Instead it just shows the last played episode on internal player.

Also when adding a show to the "Watching" list, and the resume button when opening the TV show only opens the last played episode on internal player. It doesn't take into account if we watched the latest episode on MPV

In short the Continue watching page as well as Resume TV show episode should track the progress of playback on MPV.

Can someone please fix this 

### Expected behavior

"Continue watching" page and resume TV show on "Watching" should take us to the latest played episode on MPV

### Actual behavior

Only the last played episode on internal player shows up under both these sections

### Cloudstream version and commit hash

4.0.0

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
I've already explained it's an mpv issue to you before: https://github.com/recloudstream/cloudstream/issues/302#issuecomment-1385363552
We can't track progress on something we don't get progress on.

**Comment by jackuars7** [comment]
Can adding a different player fix this?

**Comment by eightyy8** [comment]
> Can adding support for a different player fix this?
> 
> 

Settings > Player > Preferred video player

**Comment by jackuars7** [comment]
That's how I changed to an external player in first place. The aspect ratio options for built in player for manh TV shows isn't good enough, so that's the main reason I use an external player. Also subtitles search is average at best

**Comment by C10udburst** [comment]
mpv issue
