### ISSUE TITLE
Season drop-down arrow

### ISSUE THREAD

**Issue by eightyy8** [recloudstream/cloudstream#375]
### Describe your suggested feature

Alike netflix's, adding a simple arrow next to the season selector box can help the average new user understand where to find other seasons and to indicate more than one season. Even I at first didn't realise.

__CloudStream:__

![CS3 Season selection](https://user-images.githubusercontent.com/64216434/219372089-e3cf768d-7fb2-46dc-aefd-421385788a47.png)

__Netflix:__

![NFLX Season selection](https://user-images.githubusercontent.com/64216434/219372152-d568e692-795d-46a1-a7f0-ae61df30d93d.png)

### Other details

Extremely minor improvement but it's worth it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by wrightwriter** [comment]
yeah i didn't understand this either, thank you for the commit!
