### ISSUE TITLE
CloudStream Repositories 

### ISSUE THREAD

**Issue by briantgosling** [recloudstream/cloudstream#378]
### Describe your suggested feature

The Cloudstream repositories should be updated or replaced with new sources since some sources doesn't even have links it's just pure shit

### Other details

the repositories are so slow and some are disabled thus indicates they should be updated 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Guess why the testing feature was added 💀
Also clearly you haven't tried sorastream

**Comment by Blatzar** [comment]
Please use the repository pages for these issues.
