### ISSUE TITLE
Olgply not working

### ISSUE THREAD

**Issue by tonystank420** [recloudstream/cloudstream#38]
None of the movies/shows on olgply are working

When I hit play, it just opens and closes

A lot of the movies I want are on there

**Comment by SANCTI-afk** [comment]
There should be something with the extractors
Fix,,
Olgply : English provider
Egybest: Arabic provider

**Comment by C10udburst** [comment]
Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the discord.
