### ISSUE TITLE
Feature to clear the search query 

### ISSUE THREAD

**Issue by allenbaby** [recloudstream/cloudstream#381]
### Clear search query from the search bar

It would be great if we had a feature to remove the search query from the main search so that when we type in a big movie name, we don't have to long press the backspace button for soooo long. I have implemented it and has been using this feature on my phone and TV for a couple of days now. I found it very useful, and would love it if it went into the main application!

![photo_2023-02-18_19-24-00](https://user-images.githubusercontent.com/64322605/219869580-f6f3f57e-e744-4918-9f9b-bbf06cf79b2e.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
![image](https://user-images.githubusercontent.com/46196380/219871144-dff995e2-9864-465a-9698-31c632133e3c.png)
Already exists, albeit hidden, just click here

**Comment by Luna712** [comment]
> ![image](https://user-images.githubusercontent.com/46196380/219871144-dff995e2-9864-465a-9698-31c632133e3c.png) Already exists, albeit hidden, just click here

Would it be possible to add this to the UI as an icon to make it more clear that this is possible?
