### ISSUE TITLE
Black bar in PIP when using internal player

### ISSUE THREAD

**Issue by asl97** [recloudstream/cloudstream#386]
### Steps to reproduce

1. Check that PIP (Picture In Picture) is enable
2. Check internal player is used
3. Find content that isn't the same aspect ratio as the screen, in most cases, it be 4:3 (640x480)
4. Play the content in "Fit to Screen" and then press the home button to enter PIP mode
5. See black bar still showing in PIP mode

### Expected behavior

No black bar, such as when using VLC or Chrome (web browser)

### Actual behavior

Black bar is still shown despite in PIP mode

### Cloudstream version and commit hash

4.0.0 33aecfb

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
exo issue

**Comment by LagradOst** [comment]
The problem is that the vid probs has black bars in its encoding and aspec ratio change is not preserved in pip

**Comment by asl97** [comment]
> The problem is that the vid probs has black bars in its encoding
That doesn't really explain why using the long press > play in VLC/Web browser's PIP doesn't have black bar, I did test it without VLC custom PIP

To ensure both player are playing the same file, I tired using the download feature and it shows black bar in both internal and VLC, it did not play in chrome, just result in a .ts download, but there was no black bar in Just Player and Mi Video, I am guessing that's a separate issue due to combining the source streams from the m3u8 together into an mp4

>and aspec ratio change is not presearved in pip
I assume you mean the aspect ratio wasn't updated for the PIP to reflect the source aspect ratio, which I agree is most likely the issue

**Comment by asl97** [comment]
tested with the same video I had issue with, the black bar issue is fixed.

I assume #525 fixed it.
