### ISSUE TITLE
Homepage issues 

### ISSUE THREAD

**Issue by MrConqueror** [recloudstream/cloudstream#389]
### Describe your suggested feature

1 To have readability Movie Title in main Poster
2 To Clear the duplicate and unnecessary features 

### Other details

![IMG_20230222_105113](https://user-images.githubusercontent.com/102837820/220510130-56b8e1a3-ba70-431a-b2fb-76cc461612ef.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
If we increase the space for the main poster vertically then people will complain that it takes too much space. If we zoom out there will be black bars. The current view is a good compromise we won't change.

Continue watching is far from duplicate feature. Removing it for library is ludicrous. 

The only valid point is viewing your library from homepage being duplicate. That barely takes any vertical real estate given that you can close it and I am very sure that a lot of people prefer that over having to go to library.

**Comment by eightyy8** [comment]
@Blatzar I agree, but could you remove the watch status section? (not the continue watching section) Because you can access them in the new tab entirely dedicated for it.

**Comment by Blatzar** [comment]
Read the last paragraph

**Comment by eightyy8** [comment]
> Read last paragraph 

Sorry about that.

> last paragraph 

But could it by default be closed? By default meaning when you open cs3. This makes more sense to me @Blatzar

**Comment by MrConqueror** [comment]
> Read the last paragraph

Can you at least add an option in setting to turn it off because having it (plan to watch) in the homepage makes those icon blocking the main poster even more.

**Comment by MrConqueror** [comment]
I just wanted the movie title in Main Poster to be visible, like  
https://hdo.app/  

Try using this app and see how clean it is. The only problem is their Player. It's showing the Video quality and there's no option for it to disable.
