### ISSUE TITLE
Backup and Restore?

### ISSUE THREAD

**Issue by imurreflection** [recloudstream/cloudstream#39]
Hey Devs..thanks again for amazing Repo Download feature and bringing back "Plan to Watch" function.  

May i know how to use "Backup and Restore" functions.? When i tried restoring data from the successfully taken backup..it says "No Application can handle it."

Kindly help as with latest updates,it is sometime mandatory to reinstall CS completely. I am using latest pre release 3.1.3

**Comment by C10udburst** [comment]
this is not really a place for support. Please ask on the discord: https://discord.gg/5Hus6fM
