### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by Leonidios** [recloudstream/cloudstream#392]
### Describe your suggested feature

Like netflix, cloudstream could have a profile function. When the user opens the app, he should be able to choose between different profiles options that have names and/or pictures. This feature is useful for families that want for every person to have different libraries. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by eightyy8** [comment]
I'm sure the community and the devs would agree of the benefits... but it's a pretty big bloat of a feature to add, if you want those custom preferences and profile pictures. But who knows. I'm sure if the development continues consistently with enough users it's more likely to happen.

**Comment by LagradOst** [comment]
duplicate https://github.com/recloudstream/cloudstream/issues/84
