### ISSUE TITLE
A switch to make the app run as a foreground service

### ISSUE THREAD

**Issue by ZooNooU** [recloudstream/cloudstream#404]
### Describe your suggested feature

for some devices, Android handles background apps in a terrible way, so I think adding an option to make the app runs in realtime despite being in background would fix the issue (something similar to "Run as foreground service" option in Stremio)

I hope my idea is clear enough.

### Other details

🦍

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
"make the app runs in realtime despite being in background" in what way is this preferable? what use case is there to make the priority of the program higher?

**Comment by ZooNooU** [comment]
as I've said, terrible handling by some OEMs, the app soft-relaunches when switching apps (in my case). (I've sent a vid on the discord server elaborating the issue)

**Comment by LagradOst** [comment]
Then that issue applies to all apps and is not an issue with cs3 but with your phone
