### ISSUE TITLE
Switching apps resets Subs Sync to 0

### ISSUE THREAD

**Issue by ZooNooU** [recloudstream/cloudstream#405]
### Steps to reproduce

1. Start a movie/episode and select a subtitle.
2. Set Subs Sync to whatever value (400ms for example).
3. Watch abit (it works fine).
4. Switch apps and do smt else for 2 seconds, or just go home screen for 2secs then back to cs.
5. Go back to cs, the Subs Sync is set back to 0.

### Expected behavior

Subs Sync shouldn't reset. (stay 400ms in this case)

### Actual behavior

Subs Sync is back to default value 0.

### Cloudstream version and commit hash

4.0.0-PRE ab324b9

### Android version

Android 12

### Logcat

```java
🗿
```

### Other details

🦍

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [x] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
It's simply not saved with savedInstance @LagradOst
All temp things should be 💀
