### ISSUE TITLE
[FR] Option to download the whole season 

### ISSUE THREAD

**Issue by not-programmer98** [recloudstream/cloudstream#413]
### Describe your suggested feature

I hope you add an option for downloading a whole season or extracting download links in a file that can be but on a download manager.
yt-dlp did this in the past by scraping but it's dead now and the repo is gone.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by not-programmer98** [comment]
I don't think it's duplicated

**Comment by Blatzar** [comment]
https://github.com/recloudstream/cloudstream/issues/399 :pensive:

**Comment by not-programmer98** [comment]
Ok, it's duplicated to #399 but I will add that generate a file with download links is better.
