### ISSUE TITLE
Fuzzy and realtime search

### ISSUE THREAD

**Issue by Fruehwirth** [recloudstream/cloudstream#418]
### Describe your suggested feature

I would like to request the addition of a fuzzy search feature to the search functionality of our streaming app. Currently, the app's search function requires exact matches to return results, which can be frustrating if the user makes minor typos or omits certain words.

With fuzzy search, the app would be able to recognize and correct minor typos and omissions in search queries, making it easier for users to find the content they're looking for. This feature would greatly improve the search experience and lead to a more positive overall user experience.

I suggest using a combination of client-side and server-side processing to deliver fast and accurate results in real time. This could involve using techniques such as character replacement, insertion, deletion, and transposition to expand the scope of the search and return relevant results.
 
In addition a real time search would also be very nice. So that when you start typing the search query it automatically searches and shows you the results based on the search.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Some provider already have real time search tho

**Comment by Fruehwirth** [comment]
Fair enough
