### ISSUE TITLE
Arabic subtitle problem 

### ISSUE THREAD

**Issue by Mojahed878** [recloudstream/cloudstream#419]
### Steps to reproduce

 thank you very much for this app you are talented but please can fix the arabic subtitle problem when I play the arabic subtitle it's writing some unknown codes like @(#^$£÷¥!₩+₩#& something like this and thank you 

### Expected behavior

writing some unknown codes like @(#^$£÷¥!₩+₩#& something like this

### Actual behavior

It should write something like 
العطلة الصيفيه جميلة not like 
^$*#&^$^#*#

### Cloudstream version and commit hash

İm using the pre release 7b47f93 . 4.0.0.0

### Android version

Android 11

### Other details

I tried to fix it it didn't work because it's online streaming

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
change subtitle encoding

**Comment by Mojahed878** [comment]
I don't know how to encod teache me

في الاثنين، ١٣ مارس ٢٠٢٣ ٣:٥٤ م Osten ***@***.***> كتب:

**Comment by Blatzar** [comment]
![Screenshot_20230313_192126_CloudStream Beta](https://user-images.githubusercontent.com/46196380/224794426-7f45b52e-c6a1-4950-8ba8-bc05a6444dd9.jpg)

**Comment by Mojahed878** [comment]
I'm going to check

في الاثنين، ١٣ مارس ٢٠٢٣ ٩:٢٢ م LagradOst ***@***.***> كتب:

**Comment by Mojahed878** [comment]
في الاثنين، ١٣ مارس ٢٠٢٣ ٩:٢٢ م LagradOst ***@***.***> كتب:

**Comment by Mojahed878** [comment]
Look there in codes not subtitle

في الاثنين، ١٣ مارس ٢٠٢٣ ٩:٢٢ م LagradOst ***@***.***> كتب:

**Comment by Mojahed878** [comment]
I updated to the latest version and I put it on auto and nothing happend

في الاثنين، ١٣ مارس ٢٠٢٣ ٩:٢٢ م LagradOst ***@***.***> كتب:

**Comment by Mojahed878** [comment]
Okay I pressed it and choosed the arabic subtitle but it didn't work

في الاثنين، ١٣ مارس ٢٠٢٣ ١٠:٥٢ م LagradOst ***@***.***> كتب:
