### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by Light7654** [recloudstream/cloudstream#425]
### Describe your suggested feature

**Dark theme (dark blue theme)**
![iPhone 13 mini - 1](https://user-images.githubusercontent.com/87866912/225444360-c2798e9d-bda7-4606-a219-5a9f58b3722e.png)
**light blue theme**
![iPhone 13 mini - 2](https://user-images.githubusercontent.com/87866912/225444441-67c5066e-0445-42f1-b0c8-73b9a9b1f45f.png)
**light theme**
![iPhone 13 mini - 3](https://user-images.githubusercontent.com/87866912/225444513-256a7128-9c08-4606-bdbf-3d675a5e3704.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
looks shit

**Comment by C10udburst** [comment]
That objectively looks worse than the current app
