### ISSUE TITLE
The app crashes when I try to switch providers after latest release 

### ISSUE THREAD

**Issue by SANCTI-afk** [recloudstream/cloudstream#43]
### Steps to reproduce

I GOT THE MESSAGE I will not report providers again

### Expected behavior

.

### Actual behavior

.

### Cloudstream version and commit hash

3.1.3 a49f466

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
please send the logcat

**Comment by SANCTI-afk** [comment]
> please send the logcat

[logcat.txt](https://github.com/recloudstream/cloudstream/files/9386644/logcat.txt)

**Comment by C10udburst** [comment]
try clearing application data

**Comment by SANCTI-afk** [comment]
> try clearing application data

Yup that was a way to go thanks
