### ISSUE TITLE
Icon adjust 

### ISSUE THREAD

**Issue by MrConqueror** [recloudstream/cloudstream#430]
### Describe your suggested feature

Please adjust/place those icon like this and I will assure you that we will be able to read title in the poster properly.

### Other details

![IMG_20230318_070801](https://user-images.githubusercontent.com/102837820/226067346-adcf694c-ab42-474a-9d36-8caffb748c3c.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by eightyy8** [comment]
entirely dependent on the show's poster
