### ISSUE TITLE
remove the anti-function "tracking" in izzyondroid

### ISSUE THREAD

**Issue by Wjxfi** [recloudstream/cloudstream#431]
### Describe your suggested feature

remove the anti-function "tracking" in izzyondroid

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
We have no control over fdroid
