### ISSUE TITLE
Cs3-repo.error installing repo's links not found. App shows nothing or says all plugins already installed 

### ISSUE THREAD

**Issue by sxnjey** [recloudstream/cloudstream#436]
### Steps to reproduce

I have updated the hexated provider link: https://rentry.org/cs3-update
Open the link and install from here. Note to dev's please update the repo links i think the last raw links must have been reported and taken down. Thus it might not be working for new user. 

### Expected behavior

Installing and downloading Libraries 

### Actual behavior

Nothing 

### Cloudstream version and commit hash

4.0, 3.5

### Android version

12

### Logcat

```java
Nan
```

### Other details

Nan

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Terkyz** [comment]
Same here.

**Comment by WtfIa-m** [comment]
update this >>> 
eng - https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/eng.json

Multi L- https://codeberg.org/cloudstream/cloudstream-extensions-multilingual/raw/branch/builds/repo.json

Kronch- https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/kronch.json

Storm- https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/storm.json

Arab- https://codeberg.org/Mark_Eshia/arab/raw/branch/builds/repo.json

Likdev- https://codeberg.org/JakeWasHere7/likdev256-tamil-providers/raw/branch/builds/repo.json

**Comment by MhmdIbrahim1** [comment]
Does anyone work for me?

**Comment by MhmdIbrahim1** [comment]
Is it working for anyone?

**Comment by MhmdIbrahim1** [comment]
How to add CloudStream Extensions

Go to CloudStream's settings

Go to Extensions.

Add your favoured language by clicking "Add repository".

Put the url(s) below into the "Repository URL" section.

[DOWN] MEANS NOT WORKING

[UP] MEANS WORKING

CONTACT ME IF THEY DO/DONT WORK, OR IF YOU HAVE MORE LINKS

[down] Arabic: https://raw.githubusercontent.com/redtrillix/cloudstream-extensions-arabic/builds/repo.json

[down] English: https://raw.githubusercontent.com/redtrillix/cloudstream-extensions/builds/repo.json

[down] Multiligual: https://raw.githubusercontent.com/redtrillix/cloudstream-multiligual/builds/repo.json

[down] Hexated: https://raw.githubusercontent.com/redtrillix/cloudstream-extensions-hexated/builds/repo.json

[down] Darkdemon: https://raw.githubusercontent.com/redtrillix/cloudstream-darkdemon/builds/repo.json

[down] Likdev: https://raw.githubusercontent.com/redtrillix/cloudstream-likdev/builds/repo.json

[up] English: https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/eng.json

[up] Multi: https://codeberg.org/cloudstream/cloudstream-extensions-multilingual/raw/branch/builds/repo.json

[up] Hexated: https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/hexa.json

[up] Storm: https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/storm.json

[up] Kronch: https://codeberg.org/Stormunblessed/storm-ext/raw/branch/main/kronch.json

[down] DSH: https://gitlab.com/dontseehere/cs3-repos/-/raw/main/repo.json

[up] Arab: https://codeberg.org/Mark_Eshia/arab/raw/branch/builds/repo.json

[up] Storm: https://pastebin.com/raw/7YRxz84P

[up] Kronch: https://pastebin.com/raw/4d6S0gVU

[up] Hexated: https://pastebin.com/raw/mjDBFX3R

[up] English: https://pastebin.com/raw/tX6F1aKt

**Comment by DraKeN404** [comment]
![Screenshot_20230326-092302.jpg](https://user-images.githubusercontent.com/121651413/228426637-251940e8-682a-4536-9efe-93d843e09a71.jpg)

Someone in discord recommended this. Just copy the link given in the post and NOT inside it. You may use the text feature in google lens to copy it.

Credits to whomever suggested this fix.

**Comment by eightyy8** [comment]
😂

**Comment by vdbhb59** [comment]
None of the repos work anymore. Please check team.

**Comment by Eurothopia** [comment]
For those that don't know, this is actually due to the latest DMCA takedown notice from MPA, check discord (#updates) for more info

**Comment by vdbhb59** [comment]
> For those that don't know, this is actually due to the latest DMCA takedown notice from MPA, check discord (#updates) for more info

Don't have or use discord. Can you share any update?

**Comment by Eurothopia** [comment]
> Don't have or use discord. Can you share any update?
![Screenshot_2023-04-04-19-29-25-942_com.aliucord.jpg](https://user-images.githubusercontent.com/90931142/229871282-23115f11-4776-4d40-9d56-f68a4650a64f.jpg)
![Screenshot_2023-04-04-19-29-32-052_com.aliucord.jpg](https://user-images.githubusercontent.com/90931142/229871378-169dc271-5160-4ef3-98c1-8c3dfaa54a00.jpg)
