### ISSUE TITLE
PIP subtitle issue

### ISSUE THREAD

**Issue by asl97** [recloudstream/cloudstream#438]
### Steps to reproduce

1. Play a video with subtitle in PIP
2. Notice how subtitle isn't showing

### Expected behavior

Subtitle should show up in the PIP

### Actual behavior

subtitle isn't showing in PIP

### Cloudstream version and commit hash

4.0.0 67b0549

### Android version

Android 12

### Other details

While there are other ways of working around the issue, they aren't ideal.

Such as:
1: use the phone's floating window feature
  - cons include but not limited to "black bars", messed up aspect ratio, not freely resizable

2: use external players
  - cons include possible players issue with stream, having to download the subtitle separately and select it during playback

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
not an issue nor bug. This is how it is intended and how google/exo (like youtube) handle subtitles.

**Comment by asl97** [comment]
> not an issue nor bug. This is how it is intended and how google/exo (like youtube) handle subtitles.

Kind of disappointing if that is how it is, VLC and newspipe support soft subtitles in their PIP implementation.

**Comment by asl97** [comment]
> not an issue nor bug. This is how it is intended and how google/exo (like youtube) handle subtitles.

I reread your comment, it seem like you are merely stating the reason of why it is what it is, and not out right rejecting this potential feature.

So what should I do now?  create a separate feature request or should this be reopened as a feature request?

Honestly from my point of view, anybody who has subtitle enabled probably also want them in PIP, if they don't want it, they would have turn it off within the player menu.


The issue that causes this behavior seem to be due to `subtitle_holder` being within `player_holder` and it get hidden in PIP

https://github.com/recloudstream/cloudstream/blob/6e9b1cb855fa298f0df3c8b015a4cd8583821ddc/app/src/main/res/layout/player_custom_layout.xml#L4-L12

https://github.com/recloudstream/cloudstream/blob/c10ec34ab8ccac2fd34874d83422c4860029525e/app/src/main/java/com/lagradost/cloudstream3/ui/player/AbstractPlayerFragment.kt#L185-L187
