### ISSUE TITLE
Offline subtitles

### ISSUE THREAD

**Issue by hairy-tortoise** [recloudstream/cloudstream#440]
### Describe your suggested feature

Download subtitles for offline playback

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by asl97** [comment]
Subtitle got automatically downloaded with video for me, there also the option to press and hold specific episode to download subtitle for that specific episode, assuming the provider support subtitle

Subtitle playback support depends on the player though and you might need to manually select it within the player

**Comment by eightyy8** [comment]
Pretty sure it already downloads it alongside the video file.

**Comment by rokejulianlockhart** [comment]
@hairy-tortoise, not planned or completed? Pretty sure this already works, right? https://github.com/recloudstream/cloudstream/issues/440#issuecomment-1491939632

**Comment by asl97** [comment]
> @hairy-tortoise, not planned or completed? Pretty sure this already works, right? [#440 (comment)](https://github.com/recloudstream/cloudstream/issues/440#issuecomment-1491939632)

Probably pressed the wrong option when closing, but in case it's the other reason I thought of,

I just tested it in more detail, only the default subtitle is downloaded by default, maybe they want other language or all subtitles to be downloaded?

Or maybe they disabled the setting and forgot about it and since nobody is pointing out that's a possible reason why it isn't working for him, he closed this as not-planned assuming everyone is ignoring the issue he's having.

@hairy-tortoise you can select the multiple downloaded language within settings > player > subtitle settings > download languages

**Comment by hairy-tortoise** [comment]
Sorry for the late answer. I was new to the app and only watched movies and for some reason the subtitles didn't always download. For series you can just long press and choose download subtitles, but for movies you can't.

**Comment by asl97** [comment]
> Sorry for the late answer. I was new to the app and only watched movies and for some reason the subtitles didn't always download. For series you can just long press and choose download subtitles, but for movies you can't.

You can press and hold "Play Movie" to get the same menu options, if the "Download subtitles" is empty, then ether the provider you are using doesn't have any subtitle or the extension doesn't support retrieving the subtitle from the provider, ether way it's not a issue with cloudstream itself.

<details> 
  <summary>Screenshot showing empty download subtitles for a CC licensed Blender movie, with the provider blacked out</summary>

   ![obscura1682304449378](https://user-images.githubusercontent.com/4752645/233889352-fd9e5467-f17c-49ab-976d-7d4040f7898f.jpg)
</details>
