### ISSUE TITLE
can't change outline colour on depressed and raised edge type

### ISSUE THREAD

**Issue by cmwonn** [recloudstream/cloudstream#45]
### Steps to reproduce

![IMG_20220820_211030](https://user-images.githubusercontent.com/111416424/185747819-d24ec573-52ed-4156-9449-72272ec4940b.jpg)
![IMG_20220820_211038](https://user-images.githubusercontent.com/111416424/185747825-a29c0f7d-d6db-44de-89d3-f33744c7f8fb.jpg)

### Expected behavior

ㅤ

### Actual behavior

ㅤ

### Cloudstream version and commit hash

3.1.3 • a84af97

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [x] I will fill out all of the requested information in this form.

**Comment by cmwonn** [comment]
![Screenshot_2022-08-20-21-20-13-01](https://user-images.githubusercontent.com/111416424/185748049-3858ffd7-10fa-4609-ad71-7bcbe527ee71.jpg)

**Comment by LagradOst** [comment]
This is exoplayer fault, not cs3
