### ISSUE TITLE
Download video in different resolutions

### ISSUE THREAD

**Issue by Imon24** [recloudstream/cloudstream#459]
### Describe your suggested feature

Download video in different resolutions. Like 480p,720p 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
hold

**Comment by asl97** [comment]
What @LagradOst means is to press and hold on either the `play movie` or the specific episode button and a menu should pop up, from the menu, there is an option labeled `Download mirror` from which you can select which resolution you wish to download,  the options available will depend on the provider, some provider might only have one resolution available.
