### ISSUE TITLE
allow the boundary of subtitles to be thickened

### ISSUE THREAD

**Issue by arxhiebro** [recloudstream/cloudstream#476]
### Describe your suggested feature

basically the width of outline of subtitles should be customisable and should have the option to make them wider

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
this is a duplicate question, and tldr
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/CaptionStyleCompat.html does not exist as an option, so no. ask exoplayer to add that not me.

check out https://github.com/recloudstream/cloudstream/blob/0d431fd508cb893add78d95e8ebbbddc122f05db/app/src/main/java/com/lagradost/cloudstream3/ui/player/NonFinalTextRenderer.java if you want to try to force it yourself
