### ISSUE TITLE
Please remove search for update and  auto update feature on izzyondroid

### ISSUE THREAD

**Issue by Justauser0** [recloudstream/cloudstream#478]
### Describe your suggested feature

Because of this it is showing  "Tracks or reports your activity" on izzyondroid 

![IMG_20230602_225102](https://github.com/recloudstream/cloudstream/assets/135147872/11706ef3-913a-43dd-9bc9-290abf922a56)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
this is probably cuz of acra, which is a tool for reporting crashes, literally one of the first screens lets you turn on/off crash reporting.

**Comment by Blatzar** [comment]
Pretty sure ACRA is off by default now
