### ISSUE TITLE
subtitles window

### ISSUE THREAD

**Issue by jnhvvi** [recloudstream/cloudstream#481]
### Describe your suggested feature

please add where you can adjust the subtitle’s window/background corners radius. thank u devs, great app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by jnhvvi** [comment]
@LagradOst same issue? check this https://github.com/google/ExoPlayer/issues/11171

**Comment by jnhvvi** [comment]
@Blatzar @LagradOst

**Comment by RokeJulianLockhart** [comment]
> https://github.com/recloudstream/cloudstream/issues/481#issuecomment-1582501734 https://github.com/google/ExoPlayer/issues/7521#issue-641046189
