### ISSUE TITLE
Add Firebase with Google Authenication to Backup Data

### ISSUE THREAD

**Issue by LincCodes** [recloudstream/cloudstream#487]
### Describe your suggested feature

Honestly, backing up data everytime from one device and sending it to another when I want to switch phones can be a big problem if you want all the phones to have the same watch history.

Would appreciate adding Firebase Realtime/ Firestore database to this project with Google Authenication so that it will backup that BACKUP JSON file to the UID (Google Authenication UID) of a person.

This will make sure that a person has the same watch history and will make sure that it's secured (because it's online)

One can back up and restore their information on a click of a button (Firebase backup)

Alternatively, if you do NOT plan to use Firebase, you can use Google Drive were you can back it up to a person's Google Drive folder.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
https://github.com/recloudstream/cloudstream/pull/442
