### ISSUE TITLE
Add support for Brazilian Portuguese

### ISSUE THREAD

**Issue by Heus-Sueh** [recloudstream/cloudstream#491]
### Describe your suggested feature

when creating providers for some repository there is only the option of declaring that provider as Portuguese and not as Brazilian Portuguese and this is bad because there are differences between these languages as well as in dubbing and subtitles

### Other details

the best would be like this:
`override var lang = "pt-br"
`

and it should appear like this in the app:
🇧🇷 example.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
![image](https://github.com/recloudstream/cloudstream/assets/46196380/57cb29e7-b9d3-44bb-a8b0-02be7b09c24e)
```kt
    override var name = "Test provider"
    override var lang = "pt-br"
```
:raised_eyebrow:

**Comment by Heus-Sueh** [comment]
> ![image](https://github.com/recloudstream/cloudstream/assets/46196380/57cb29e7-b9d3-44bb-a8b0-02be7b09c24e)
> ```kt
>     override var name = "Test provider"
>     override var lang = "pt-br"
> ```
> :raised_eyebrow: It works

🤨so some providers are wrong, because they are brazilian content but they are listed as Portuguese

**Comment by Blatzar** [comment]
> > ![image](https://user-images.githubusercontent.com/46196380/248882702-57cb29e7-b9d3-44bb-a8b0-02be7b09c24e.png)
> > ```kotlin
> >     override var name = "Test provider"
> >     override var lang = "pt-br"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > :raised_eyebrow: It works
> 
> :raised_eyebrow:so some providers are wrong, because they are brazilian content but they are listed as Portuguese

:raised_eyebrow: yes, talk to the provider maintainers

**Comment by Heus-Sueh** [comment]
> > > ![image](https://user-images.githubusercontent.com/46196380/248882702-57cb29e7-b9d3-44bb-a8b0-02be7b09c24e.png)
> > > ```kotlin
> > >     override var name = "Test provider"
> > >     override var lang = "pt-br"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > :raised_eyebrow: It works
> > 
> > :raised_eyebrow:so some providers are wrong, because they are brazilian content but they are listed as Portuguese
> 
> :raised_eyebrow: yes, talk to the provider maintainers 

🤨ok
