### ISSUE TITLE
select a default source each providers

### ISSUE THREAD

**Issue by jnhvvi** [recloudstream/cloudstream#500]
### Describe your suggested feature

‎ 

### Other details

‎ 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
check the priority update

**Comment by jnhvvi** [comment]
> check the priority update

priority update?
