### ISSUE TITLE
Choose player by show selected

### ISSUE THREAD

**Issue by jackuars7** [recloudstream/cloudstream#511]
### Describe your suggested feature

Across some tv shows especially the olden ones, the aspect ratio is pretty bad, it covers only half the screen. Even if I try to change it within the player which gives only 3 options in total, the one which fills the screen cuts the subtitles out.

I have to always manually switch to a different player that stretches and fits to the screen perfectly for those shows. However everytime I have to come back to internal player for recent shows.

Can you provide an option to choose video player by show or by video instead of only the settings menu.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
bloat option, you do know that you already can select the player by holding the play button
