### ISSUE TITLE
"You don't have an app that can do this" message when attempting to create or restore a backup from a Chromecast with Google TV

### ISSUE THREAD

**Issue by kratoz29** [recloudstream/cloudstream#515]
### Steps to reproduce

Go to settings
Backup and updates
Tap on either create or restore a backup.

### Expected behavior

To be able to create a .txt file as a backup or restore one.

### Actual behavior

I get the following message:

"You don't have an app that can do this" I think this is because the Chromecast is lacking from the files system app, is it even possible a workaround for this? like picking up an alternative file manager, a smb/ftp share or even a cloud system?

### Cloudstream version and commit hash

4.0.1 c3296f3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
This is not a bug, you need to install a file manager

**Comment by kratoz29** [comment]
> This is not a bug, you need to install a file manager

Hi, what do you mean? I have two installed, X-Plore File Manager and FX File Explorer and Cloudstream picks none of them as they are not system apps.

**Comment by LagradOst** [comment]
use ac file manager

**Comment by kratoz29** [comment]
> use az file manager

I ended up using Cx File manager and it worked! I thought you needed a file system app for that, well, thanks a lot dude.

**Comment by az51blog** [comment]
> > use az file manager
> 
> I ended up using Cx File manager and it worked! I thought you needed a file system app for that, well, thanks a lot dude.

Thx. This helps me
