### ISSUE TITLE
SHA-256 checksums file for each new release

### ISSUE THREAD

**Issue by Penknife0915** [recloudstream/cloudstream#520]
### Describe your suggested feature

It would be great if every new release on Github could include a SHA-256 checksum, allowing users to verify the integrity of the downloaded app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
android already have a signature, so you already know it is a trusted source????

**Comment by C10udburst** [comment]
Sure

Prerelease cert hash:
```
C2:75:5B:1F:BC:6C:EF:A6:AA:20:73:9F:52:7D:09:24:65:25:61:8A:7E:16:ED:B2:E2:17:1C:2C:9D:E7:0C:72
```

Release cert hash:
```
9B:4F:6C:87:EE:B7:0B:25:7C:7F:96:8E:65:B1:56:16:82:4B:CE:33:E9:CC:74:A0:7A:D3:DD:26:63:2A:1D:B7
```
