### ISSUE TITLE
Does not remember saved settings 

### ISSUE THREAD

**Issue by Onmyosama** [recloudstream/cloudstream#53]
### Steps to reproduce

I choose a specific preferred quality
I choose a specific site to load from whenever i enter the app 

### Expected behavior

It's supposed to remember those settings and load them whenever i use the app
Cloudstream 3 was very good at this 

### Actual behavior

It doesn't remember any of the settings i previously set so i have to keep changing it manually all the time

### Cloudstream version and commit hash

 a3f4c0b

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
I am very sure this is fixed. Re-open if not.
