### ISSUE TITLE
NSFW and Password Protection

### ISSUE THREAD

**Issue by Ultimatinium** [recloudstream/cloudstream#54]
### Describe your suggested feature

- Add option in settings to enable NSFW.

- Add the selection of NSFW in the home tab and in search tab when the NSFW enabled.

- Add an option to enable or setup a password protection to the Cloudstream app when opening.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
> Add option in settings to enable NSFW.

> Add the selection of NSFW in the home tab and in search tab when the NSFW enabled.

these are already features, you need to enable NSFW in preferred media (`settings > language > preferred media`) and install some nsfw extensions ofc

**Comment by C10udburst** [comment]
> Add an option to enable or setup a password protection to the Cloudstream app when opening.

And this could probably be an extension

**Comment by C10udburst** [comment]
@Ultimatinium you can get the said extension [here](cloudstreamrepo://raw.githubusercontent.com/C10udburst/cloudstream-misc/builds/repo.json)

**Comment by CuongBa956** [comment]
> @Ultimatinium you can get the said extension here:
> 
> `https://raw.githubusercontent.com/C10udburst/cloudstream-misc/builds/repo.json`

Hey bro can you tell me the password of this repo?

**Comment by C10udburst** [comment]
whatever u typed first

**Comment by Lolipay** [comment]
> > @UltimatiniumAnda bisa mendapatkan ekstensi tersebut di sini:
> > `https://raw.githubusercontent.com/C10udburst/cloudstream-misc/builds/repo.json`
> 
> Hai gan, bisa kasih tau saya password repo ini?
