### ISSUE TITLE
Cast Horizontal Recycler is not working

### ISSUE THREAD

**Issue by IndusAryan** [recloudstream/cloudstream#547]
### Steps to reproduce

go to any movie or series result page and try swiping cast items 

### Expected behavior

Actor items should scroll horizontally

### Actual behavior

the swipe opens up recommendation fragment instead

### Cloudstream version and commit hash

Latest PreRelease

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
This doesn't appear to be fixed. It is only fixed the first time you enter a movie, if you go back and back in it is broken again and doesn't scroll.
