### ISSUE TITLE
SkipOP button doesn't disappear.

### ISSUE THREAD

**Issue by IndusAryan** [recloudstream/cloudstream#551]
### Steps to reproduce

watch any anime or a show on a provider that suppoerts SkipOP
either skip the opening or don't do anything

### Expected behavior

Skipop button should disappear is skipped or if the opening segment passes

### Actual behavior

It remains in the player in whole episode.

### Cloudstream version and commit hash

Latest PreRelease

### Android version

A13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
unable to replicate

**Comment by LagradOst** [comment]
give example provider + series + episode

**Comment by LagradOst** [comment]
If you mean the button called "Skip OP" in the bottom right that is visible for 50% of the episode instead of "Next Episode", that is intentional

**Comment by LagradOst** [comment]
yup, as anime intros are around 85s
