### ISSUE TITLE
subtitles framework 

### ISSUE THREAD

**Issue by jnhvvi** [recloudstream/cloudstream#553]
### Describe your suggested feature

customising the subtitles window/background

### Other details

   • height
   • width
   • x-offset
   • y-offset

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Not possible, everything that can be customizable already is

**Comment by jnhvvi** [comment]
> Not possible, everything that can be customizable already is

no solution and it cant be done?

**Comment by jnhvvi** [comment]
well thanks brother

**Comment by LagradOst** [comment]
> > Not possible, everything that can be customizable already is
> 
> no solution and it cant be done?

blame exoplayer. here is everything I can edit https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/CaptionStyleCompat.html

**Comment by jnhvvi** [comment]
> > > Not possible, everything that can be customizable already is
> > 
> > 
> > no solution and it cant be done?
> 
> blame exoplayer. here is everything I can edit https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ui/CaptionStyleCompat.html

have u/ur team contacted the devs yet?

**Comment by jnhvvi** [comment]
how bout different extensible player? if it were that easy...

**Comment by LagradOst** [comment]
bro asks for an entire player rework that will take hundreds of hours just because his subtitles looks somewhat bad 💀
