### ISSUE TITLE
Add setting to switch the position of the back button

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#556]
### Describe your suggested feature

It would be nice if we could use a setting to switch the back button in the player to the other side. On my phone, I always end up accident clicking it or something and that gets quite annoying. If there is another, better way to prevent that, that would be nice as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
nope, wont get added

**Comment by Luna712** [comment]
How come? I can understand why I supposed just would like a reason why not, as this gets quite annoying to accidentally hit the back button 10 times per hour.

**Comment by LagradOst** [comment]
1. you can lock it
2. adding an option will bloat the settings, take time for me, and that settings will have to be translated into 48 languages
