### ISSUE TITLE
Can't download movies/shows

### ISSUE THREAD

**Issue by b1bradders** [recloudstream/cloudstream#575]
### Steps to reproduce

1. Install a repository.
2. Find a show/movie
3. Download should fail (it says download started, but nothing happens)

### Expected behavior

The download should actually start

### Actual behavior

It shows a Toast saying "Download started" but no download starts.

### Cloudstream version and commit hash

4.1.7 5570038

### Android version

Android 13

### Other details

I tried different providers but that still didn't work

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Check your storage location and change it to something custom as andorid scoped storage is ass

**Comment by DarkCrypt** [comment]
Did you try latest pre-release?

I don't usually download movies/videos but it worked for me on Android 13 with default download location. Download notification was present from start to finish as expected.

**Comment by Shibe32** [comment]
i also have the same problem, i have the message at the bottom "download started" for a few seconds but nothing is happening and the only thing i get is a 0 bite .mp4 file of the movie

**Comment by Shibe32** [comment]
> Yeah sometimes I get a 0 byte .mp4 for certain episodes. I just try redownloading the episode after deleting the .mp4 and it works. Very strange tbh.

When i try redownloading by clicking on "watch" then "download from mirror" after deleting the file, it does the same thing again and when i change the download path to a custom one, i don't even get the 0 byte mp4. Man, i just wannna watch Chris Pratt mario.

**Comment by DarkCrypt** [comment]
Download location on scoped storage does matter. Download/ isn't working for you guys?

**Comment by Shibe32** [comment]
> Download location on scoped storage does matter. Download/ isn't working for you guys?

nope, at least not for me, when i use the default location, i get a 0 byte .mp4 file of the movie i try to download and when i use another custom location, there is not even the 0 byt mp4.

**Comment by DarkCrypt** [comment]
> nope, at least not for me, when i use the default location, i get a 0 byte .mp4 file of the movie i try to download and when i use another custom location, there is not even the 0 byt mp4.

Well shit, I guess I don't understand why it's not working for some users. I also have to retract my previous statement about "download location on scoped storage does matter" because CloudStream just turned me into a liar, haha!

I made this claim because awhile back I was providing feedback to the dev of Musify for downloading music on Android 13. He was struggling with permissions and scoped storage. The only way downloads seemed to work was by utilizing certain top level folders.

This doesn't appear to be true since I'm able to download with CloudStream by utilizing any of the 3 download path options without issue. I also have background activity set to off and battery optimization set to always ask.

I apologize to all for not being of any help.

**Comment by LagradOst** [comment]
> This doesn't appear to be true since I'm able to download with CloudStream by utilizing any of the 3 download path options without issue. I also have background activity set to off and battery optimization set to always ask.

Scoped storage is a major pain in the ass frfr and is unreliable af, the ppl that made the scoped storage api have shit for brains. You can send this to the dev https://github.com/LagradOst/SafeFile as it is an attempt to fix it but I have no idea if the problems ppl are having in this thread is due to scoped stoage or not.

**Comment by DarkCrypt** [comment]
> You can send this to the dev https://github.com/LagradOst/SafeFile as it is an attempt to fix it but I have no idea if the problems ppl are having in this thread is due to scoped stoage or not.

Okie dokie! I'll send that link to the dev and see what he thinks, thank you for the kind recommendation friend.

I'm not sure what the underlying issue in this thread is either, might not have anything to do with scoped storage like you said. It's just weird that downloading works great on Android 13 for some and not others. Downloading also works great for me on WSA (PC) running Android 13. Just damn confusing.

Do the different operating systems cause conflict? (Ex. OnePlus OS, One UI, etc.)
Does the file manager matter for some reason?
Does a VPN cause conflict?
Or is it something else?

I just have no good answers for anybody.

**Comment by Shibe32** [comment]
Ok guys, so it finally worked, since i'm french, i use french repos so i used one called FStream which gives me the 0 byte file but when i switch to another repo like Wiflix, it works, i can now download and watch super mario.

**Comment by DarkCrypt** [comment]
> when i switch to another repo like Wiflix, it works

I didn't even consider the download source, duh.

> can i download an entire serie in one shot instead of downloading each one manually

Not at this time, see #399.

> is there a way to choose the quality

Yes, see #140.

Hold down Play or Download button -> Download mirror -> select quality

> is it normal that the files don't have any metadata even on the resolution

This is more than likely a provider issue. You can experiment by trying different providers.

> will we ever see a pc version of the app

Not likely, see #171.

I recommend using WSA, works great. Then you can run any Android apps you want. Or if you want to go way beyond you can use VirtualBox and run any OS you want.

**Comment by Shibe32** [comment]
> > when i switch to another repo like Wiflix, it works
> 
> I didn't even consider the download source, duh.
> 
> > can i download an entire serie in one shot instead of downloading each one manually
> 
> Not at this time, see #399.
> 
> > is there a way to choose the quality
> 
> Yes, see #140.
> 
> Hold down Play or Download button -> Download mirror -> select quality
> 
> > is it normal that the files don't have any metadata even on the resolution
> 
> This is more than likely a provider issue. You can experiment by trying different providers.
> 
> > will we ever see a pc version of the app
> 
> Not likely, see #171.
> 
> I recommend using WSA, works great. Then you can run any Android apps you want. Or if you want to go way beyond you can use VirtualBox and run any OS you want.

thanks
