### ISSUE TITLE
to request

### ISSUE THREAD

**Issue by AdnanAlami** [recloudstream/cloudstream#576]
### Describe your suggested feature

It will help me a lot if you extract a video link from this link
https://zyy.vidpro.net/embed-scapzgte2o4q.html

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Hello, this is not a place for help/discussion. Please consider joining the Discord server
