### ISSUE TITLE
whenever I click on a movie from any provider it doesn't play

### ISSUE THREAD

**Issue by froghunter3** [recloudstream/cloudstream#577]
### Steps to reproduce

I click on the play button for most movies on most providers and it just doesn't play with a message "no links found"

### Expected behavior

it should play the video normally as these providers such as aniwatch are up

### Actual behavior

it doesn't open

### Cloudstream version and commit hash

4.0.1 ded96dd9

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Provider issue, this github repo is about the app not the providers
