### ISSUE TITLE
Sing up option

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#584]
### Describe your suggested feature

Add a sign-up option to sync bookmarks, watch history from different device. 
It will also help to prevent losses of bookmarks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
duplicate #549

**Comment by EHMilon** [comment]
I can't understand anything why it has been closed.
