### ISSUE TITLE
English Subtitle breaks into multiple files .

### ISSUE THREAD

**Issue by SaurabhKaperwan** [recloudstream/cloudstream#599]
### Steps to reproduce

Already tried all subtitle encoding and Subtitles are working fine in external player like vlc

### Expected behavior

Subtitle should not break into multiple files

### Actual behavior

Subtitle breaks into multiple files

### Cloudstream version and commit hash

4.1.8  8fe34d3

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
wdym, how can a subtitle split???

**Comment by Luna712** [comment]
This is because there are multiple subtitle sources found for English, that's why there is English 1, English 2, etc... each is the full subtitles, but different sources or different versions. The subtitles themselves don't split. Or at least unless I didn't understand, but not sure how it could.

**Comment by LagradOst** [comment]
that is intended behavior as one many not work so we download at least 3 or so
