### ISSUE TITLE
Seperate search history and downloads by local account

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#602]
### Describe your suggested feature

While bookmarks, etc... is seperated by account, search history and downloads are not. It would be nice if search history and downloads could also be seperated. For downloads I understand they would still exist on the device but it would be nice if you could potentially seperate what ones display, with some sort of switch in settings (or in downloads page) to show all downloads or account specific downloads.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
the account system was setup LONG before it was implemented in the UI. so what was designated as account specific was not considered with much care

**Comment by LagradOst** [comment]
I agree that search might be personal to an account, I wont place downloads in the same category as I dont want ppl deleting accounts or switching them confusing it with deleting the files and/or confusing it with a bug

**Comment by Luna712** [comment]
> I agree that search might be personal to an account, I wont place downloads in the same category as I dont want ppl deleting accounts or switching them confusing it with deleting the files and/or confusing it with a bug

This is understandable and after posting this I thought that would probably be true.
