### ISSUE TITLE
Add a setting to disable downloads and fix downloads support for TV

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#603]
### Describe your suggested feature

Some devices such as Fire TV have very little storage by default and attemptting to download something could cause storage to run out immediately which causes othee issues if you aren't using an external storage. To prevent issues, it would be nice if it could be a setting to disable downloads completely. I do notice, there is a download page on TV but there is no button to actually download as well. It would be nice if support for downloads could be added to TV as well to support if you are indeed using an external storage device. It would be nice if this could just be reworked a bit, or at the very least remove downloads page button from TV if downloads are not going to be supported on TV at all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
ye, the navigation rail for tv should not have downloads

**Comment by Luna712** [comment]
Download path from settings also I think?

**Comment by LagradOst** [comment]
after a user complained about downloads missing on tv, it was readded

**Comment by LagradOst** [comment]
download on tv is supported, but you have to long hold

**Comment by KingLucius** [comment]
It should be disabled by default with an option to add it back.
