### ISSUE TITLE
Add support for profile locks in local accounts

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#604]
### Describe your suggested feature

I am not sure if this is something can really be done, but I am just postinfg a few my thoughts I have been thinking for a while, but it would be nice if you could set something like a profile pin for local accounts. Since it would likely be stored locally, it would not be something meant to be extremely secure, but just a way to have a little extra control on profiles.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
The idea is accepted, but low priority so no ETA
