### ISSUE TITLE
Opening an external video in "Open with..." using CloudStream breaks things

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#605]
### Steps to reproduce

1) Open an external video using CloudStream Beta
2) Click the back button to close the video
3) Open the CloudStream Beta app
4) Search for a movie on the search panel or click one from the home screen

Note: to reproduce CloudStream Beta must already be opened when you open the external video

### Expected behavior

It should be able to handle this case, and still work like normal when the external video is closed.

### Actual behavior

Nothing happens; click event is not functioning, you can not play anything at all. You have to restart CloudStream to get it working properly.

### Cloudstream version and commit hash

4.1.8 2bed79b

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Rayforest** [comment]
Do you mean external video player? Like VLC

**Comment by Luna712** [comment]
> Do you mean external video player? Like VLC

No, I mean opening a video in cloudstream from file manager directly.

**Comment by Rayforest** [comment]
I tried it in the latest 4.1.9 beta release. It is true. You can not choose a single title. In short words, if cs is running in the background and we play a video from our phone storage on cs, then after closing this video cs won't work as expected and nothing won't play on cs. For it to work again you need to restart the app

**Comment by Luna712** [comment]
It appears that even if the second window (the external video) is closed CloudStream itself still tries to do events on its view, so clicking a movie for example actually does open it, you just don't notice it because it is in the other view that is not open anymore.

**Comment by Luna712** [comment]
My PR fixes the issue where it uses the wrong activity instance. But I am not sure if thats the best way to fix it or not.
