### ISSUE TITLE
Update Tab animations.

### ISSUE THREAD

**Issue by TeaOwO** [recloudstream/cloudstream#610]
### Describe your suggested feature

The animation on cloudstream should look better.

### This is what it looks like now:

https://github.com/recloudstream/cloudstream/assets/123305689/41be239e-c307-42ca-acc3-97ac4aac6808

### What it should look like: (example by battery guru)

https://github.com/recloudstream/cloudstream/assets/123305689/71451dcf-256d-4e12-a912-613d4308fa31

### Or: (example by [Tap, tap](https://github.com/KieronQuinn/TapTap))

https://github.com/recloudstream/cloudstream/assets/123305689/897b18de-b84d-4e39-a49a-e04c90485739

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Rayforest** [comment]
I think the current one is nice. Although the outer circle while selecting an icon could have been a bit more subtle. And also animating the icons while selecting them might look good too 😜

**Comment by TeaOwO** [comment]
> I think the current one is nice. Although the outer circle while selecting an icon could have been a bit more subtle. And also animating the icons while selecting them might look good too 😜

I believe the circle should be removed completely. But the animations would look really good! ^⁠_⁠^
