### ISSUE TITLE
Ask for ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION

### ISSUE THREAD

**Issue by erik9012** [recloudstream/cloudstream#617]
### Describe your suggested feature

Downloading movies or using  the extension aniyomi compat sometimes annoys. Allow people to give cloudstream the permission to manage all files and cloudstream will have less trouble finding the extension connected to aniyomi compat and to store movies with the download button in cloudstream. Together with this it could even become a option to store movies on a preffered location 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by erik9012** [comment]
This can be requested directly. Revanced manager  does too: https://developer.android.com/training/data-storage/manage-all-files..i can't  provide cloudstream the permission as it doesn't ask for it. Not from.my privacy section in settings app, not in tbe app info section. It has to be asked for

**Comment by erik9012** [comment]
Thank you very much. It was somewhat different in my settings app due to customizations of phone brand bit I found it. Seems i enabled it already but everything is good now. I still would like a pop-up like revanced manager does but your help was very useful. Appreciated

**Comment by CranberrySoup** [comment]
Aniyomi compat does not need any file privileges and you can already change the download location :confused:
