### ISSUE TITLE
Trailers don't show anymore 

### ISSUE THREAD

**Issue by Onmyosama** [recloudstream/cloudstream#62]
### Expected behavior

Trailers should show in the interface before you play the movie as that's the thing that would give you an idea of what the movie you're about to watch is and leave on you an impression of the movie so as to know whether or not it's worth the watch 

### Actual behavior

Trailers doesn't show anymore..two updates before this one it was showing but now after this update it doesn't show

### Cloudstream version and commit hash

 5636bf2 

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
This is a bug with the YT lib, not the app
