### ISSUE TITLE
Video stream quality

### ISSUE THREAD

**Issue by mileymehak77** [recloudstream/cloudstream#620]
### Steps to reproduce

Earlier there was a setting in player with which you can decide the default resolution on mobile data and wifi. Has that been removed ? Kindly bring it back.

### Expected behavior

Video player resolution

### Actual behavior

Not able to select resolution

### Cloudstream version and commit hash

4.2.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
it was never removed, just upgraded in quality profiles

**Comment by mileymehak77** [comment]
> it was never removed, just upgraded in quality profiles

Yes. I found it out.
