### ISSUE TITLE
Duplicate title warning when adding a title to library (from another source)

### ISSUE THREAD

**Issue by imDusht** [recloudstream/cloudstream#622]
### Describe your suggested feature

If i have a title already in library like '"the blacklist" & i try to add it again from different source than add option to skip it and replace it (with existed) other than adding another one with same title.

A screenshot of same thing added from tachiyomi manga app

### Other details

![Screenshot_20230922-144320_Tachiyomi](https://github.com/recloudstream/cloudstream/assets/79660867/0e4e736e-c9a4-4aa3-a27f-2f42cd0f0633)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
This would be a great idea, something I've thought of before as well, if something is already in library (either bookmarks or subscriptions, separately), it would be nice if an alert dialog appeared telling you that as I have accidentally added a lot of duplicates to library and that is quite annoying.

**Comment by Luna712** [comment]
This should be done with my PR if it is merged.
![Screenshot_20231014_215107_CloudStream Debug](https://github.com/recloudstream/cloudstream/assets/142361265/bf24aa16-7b1d-4b9e-8be4-746446714c84)
![Screenshot_20231014_215046_CloudStream Debug](https://github.com/recloudstream/cloudstream/assets/142361265/59f587cc-9c06-4576-bee9-bcedfbf03d8b)
![Screenshot_20231014_215030_CloudStream Debug](https://github.com/recloudstream/cloudstream/assets/142361265/8831237b-41ee-4d15-9f6c-ab7d50dc1477)

Messages might need some improvement but the general idea is there and functional, again, if my PR is merged that is. I might have done it a wrong way also.
