### ISSUE TITLE
Settings sometimes unresponsive

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#625]
### Steps to reproduce

Sometimes if you go to downloads.and then settings, settings becomes unresponsive (nothing can be clicked) and tab still appears as if downloads is open. You have to restart the app to get it working again.

### Expected behavior

Settings should work as expected.

### Actual behavior

Settings becomes unresponsive.

### Cloudstream version and commit hash

4.2.0 d4fff7c

### Android version

Android 13

### Other details

The screenshot is from CloudStream Debug but happens on CloudStream Beta and CloudStream apps.as well.
![Screenshot_20230922_133836_CloudStream Debug~2](https://github.com/recloudstream/cloudstream/assets/142361265/9c7245bc-29d0-42c8-a779-4fd02b020d9d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
This seems to be the relevant log:

```
10-02 16:13:44.243 13596 13596 D ApiError: -------------------------------------------------------------------
10-02 16:13:44.243 13596 13596 D ApiError: safeApiCall: Navigation action/destination com.lagradost.cloudstream3.prerelease.debug:id/action_navigation_settings_to_navigation_settings_extensions cannot be found from the current destination Destination(com.lagradost.cloudstream3.prerelease.debug:id/navigation_settings_account) label=Settings class=com.lagradost.cloudstream3.ui.settings.SettingsAccount
10-02 16:13:44.243 13596 13596 D ApiError: safeApiCall: Navigation action/destination com.lagradost.cloudstream3.prerelease.debug:id/action_navigation_settings_to_navigation_settings_extensions cannot be found from the current destination Destination(com.lagradost.cloudstream3.prerelease.debug:id/navigation_settings_account) label=Settings class=com.lagradost.cloudstream3.ui.settings.SettingsAccount
10-02 16:13:44.243 13596 13596 W System.err: java.lang.IllegalArgumentException: Navigation action/destination com.lagradost.cloudstream3.prerelease.debug:id/action_navigation_settings_to_navigation_settings_extensions cannot be found from the current destination Destination(com.lagradost.cloudstream3.prerelease.debug:id/navigation_settings_account) label=Settings class=com.lagradost.cloudstream3.ui.settings.SettingsAccount
10-02 16:13:44.244 13596 13596 W System.err: 	at androidx.navigation.NavController.navigate(NavController.kt:1663)
10-02 16:13:44.244 13596 13596 W System.err: 	at androidx.navigation.NavController.navigate(NavController.kt:1595)
10-02 16:13:44.244 13596 13596 W System.err: 	at androidx.navigation.NavController.navigate(NavController.kt:1577)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.lagradost.cloudstream3.utils.UIHelper.navigate(UIHelper.kt:181)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.lagradost.cloudstream3.ui.settings.SettingsFragment.onViewCreated$navigate(SettingsFragment.kt:168)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.lagradost.cloudstream3.ui.settings.SettingsFragment.onViewCreated$lambda$3$lambda$2$lambda$1$lambda$0(SettingsFragment.kt:200)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.lagradost.cloudstream3.ui.settings.SettingsFragment.$r8$lambda$5LLBUIZUvZv1S-Niq9vdtbX2-cQ(Unknown Source:0)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.lagradost.cloudstream3.ui.settings.SettingsFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.view.View.performClick(View.java:7892)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.widget.TextView.performClick(TextView.java:16220)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.view.View.performClickInternal(View.java:7869)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.view.View$PerformClick.run(View.java:30891)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.os.Handler.handleCallback(Handler.java:942)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.os.Looper.loop(Looper.java:313)
10-02 16:13:44.244 13596 13596 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8762)
10-02 16:13:44.244 13596 13596 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
10-02 16:13:44.244 13596 13596 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by Luna712** [comment]
So from my understanding it seems to sometimes think you are still in a specific navigation panel, in this case navigation_settings_account, so it tries to load the new setting panel you click, in this case, navigation_settings_extensions, from this context, and can find it there, when you go back, it seems to not know you are actually in the settings, and thinks you are still in the former location. I might be reading it wrong though.

Here's a simplified breakdown from my understanding:

* You are currently in the navigation_settings_account panel.
* When you click to navigate to the navigation_settings_extensions panel, the app tries to load it from the context of navigation_settings_account, which is not what you intend.
* When you go back (using the Back button), CloudStream doesn't correctly recognize that you're in the settings and thinks you're in the previous location, causing confusion in the navigation.

This issue seems, in a sense, somewhat similar to an issue I am having on TV, when you go to the next episode, or even back, and play it manually, sometimes it then overlaps, the previous episode still playing in the background while the new episode is as well, and the only way to fix is either restart the app or restart the TV. Oddly, sometimes it even keeps playing in the background when you go home, or put the TV to sleep. But that is another issue I'll have to create later.

**Comment by Luna712** [comment]
> overall it just forgets the graph of navigation

That simplifies my way over complex explanation above, but yes this is what I meant.

**Comment by LagradOst** [comment]
afaik this is an android issue

**Comment by Luna712** [comment]
This is now fixed with the upstream bump you did.

**Comment by Luna712** [comment]
The bump was reverted so this is broken again.

**Comment by LagradOst** [comment]
> The bump was reverted so this is broken again.

Android 14 fuck cs3 up on a fundamental level, so it is a nogo

**Comment by Blatzar** [comment]
https://github.com/recloudstream/cloudstream/blob/master/app/src/main/res/navigation/mobile_navigation.xml#L377-L383

If the action is moved to a global action this will very likely be fixed

**Comment by Luna712** [comment]
> > The bump was reverted so this is broken again.
> 
> Android 14 fuck cs3 up on a fundamental level, so it is a nogo

I just noticed, and understand. Thanks!

**Comment by Luna712** [comment]
@LagradOst @CranberrySoup this does not appear to be fixed. It seems to have not worked.

**Comment by Luna712** [comment]
The only way I have been able to fix this is bumping to android 14 and the navigation package but like already mentioned that causes a whole bunch of other problems. There might be another way to fix it that I have not yet found though
