### ISSUE TITLE
Adding "Drop Shadow" to edge type

### ISSUE THREAD

**Issue by gregorio0h** [recloudstream/cloudstream#629]
### Describe your suggested feature

Sometimes with "shadow" option to the edge type in subtitle, there's some flaws when I'm watching films where the lights just going bright and then the subtitle is blending to those white lights and It become unreadable. So I'm thinking if you would like to consider adding a "Drop Shadow" with provide light dark shadow to the upper-left and lower-left which can prevent the subtitles become unreadable when the lights goes flashing again

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
not possible, everything relating to subs are already maxed out. create an issue on exoplayer not here
