### ISSUE TITLE
Add a next episode popup button on TV UI

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#639]
### Describe your suggested feature

It would be nice if we could add a "Next Episode" popup button to TV (maybe with setting to enable it) it could appear by say using [UPDATE_SYNC_PROGRESS_PERCENTAGE](https://github.com/recloudstream/cloudstream/blob/1d90858f64bd113df71dc68fa8e03f9be640c542/app/src/main/java/com/lagradost/cloudstream3/ui/player/AbstractPlayerFragment.kt#L72), or completing that TODO and making it a settint and use that also.

This is just an idea that could be consistent with some streaming services. Not sure if it is something that may be added or not though.

We might be able to do some even more complex, by using some sort of mechanism that can actually detect when credits start and using that. For example, the OpenCV Android SDK might be able to do this, but this might complicate the code and not sure if it was worth it, but doing something like this would make CloudStream one more step closer to becoming an even greater media player with more consistency between streaming services.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
next episode button already appear on both tv and phone if that metadata exist along with skip op

**Comment by LagradOst** [comment]
if you want to add some more timestamps then add it here https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/utils/AniSkip.kt#L44

**Comment by Luna712** [comment]
> next episode button already appear on both tv and phone if that metadata exist along with skip op

Hmm, I apologize, I knew it had some functionality, but I have never seen anything popup, so I was talking about some more advanced implementation that actually detects when credits start rather than relying on timestamps. But this is most like not worth the work I guess. Thanks for your response.

**Comment by LagradOst** [comment]
> > next episode button already appear on both tv and phone if that metadata exist along with skip op
> 
> Hmm, I apologize, I knew it had some functionality, but I have never seen anything popup, so I was talking about some more advanced implementation that actually detects when credits start rather than relying on timestamps. But this is most like not worth the work I guess. Thanks for your response.

I dont have the time nor does phones have the processing power to do advanced image recognision to be able to detect op/ed
