### ISSUE TITLE
Implement haptic feedback and lock on to current location to seekbar

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#643]
### Describe your suggested feature

That way when you seek by dragging, you can find your current location again through haptic feedback and lock on to current location when within a few seconds around it, similar to how Netflix does as an example (though not asking it to be exact, that just explains it a bit better than I can).

This might be tricky to implement, I am not sure.

It would also be nice if you could lock on to a specific time, seeking to a specific time with my finger, the time does lock on the screen display but then I remove my finger from the screen and then the video jumps to a few seconds before or after the locked on time which is really annoying.

Sorry if I am not explaining good, this is a bit hard to explain and may be hard to implement. I'm just not sure.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
I find that very annoying

**Comment by Luna712** [comment]
@LagradOst Is there another way to just make it easier to find your previous location again when dragging the seekbar? I somewhat agree haptic feedback can be annoying, but its also annoying when are seeking and can't find where you started at. Anyway, I understand if not. Thanks anyway.
