### ISSUE TITLE
SIMKL integration

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#644]
### Describe your suggested feature

Many times many person requests to add Cloud Sync option. What is your headache about our problem? If you don't add the sing In / Sing Up option or think that you won't do it in the future, then remove the built-in Library and add SIMKL or other Service provider.
You can't understand how hard it to operate from multiple Device.
![Screenshot_20231003-175535~2](https://github.com/recloudstream/cloudstream/assets/107425940/7ecfb423-13f9-4a91-97fd-84c2f4a9383a)
Please be considered. It's my humble request. And if you don't then make me sure why it is not possible.
Thank you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
Simkl is already there with personal lists and sync option

**Comment by KingLucius** [comment]
The whole library is not supported "for now" in TV layout as far as i know.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/recloudstream/cloudstream/issues/644#issuecomment-1745025642

@Rayforest, per https://github.com/recloudstream/cloudstream/issues/644#issuecomment-1745563243, that's worth a separate issue if you want that.
