### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by AdnanGo1** [recloudstream/cloudstream#65]
### Describe your suggested feature

Hello, can you do a web scraping of this site please
https://www.animeiat.tv/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Hello, please do not create requests for websites on this repository. It does not contain and will not contain any providers.
