### ISSUE TITLE
Library doesn't reload when switching accounts

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#650]
### Steps to reproduce

* Open library (with account1)
* Switch account
* Open Library again (with account2)

### Expected behavior

The library should now be from account2

### Actual behavior

The library is from account1 still, only restarting the app correctly gives library from account2 again.

### Cloudstream version and commit hash

4.2.0 3f51195

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
known issue

**Comment by Luna712** [comment]
> known issue

Ah thanks, I can probably PR a fix for this one later.

**Comment by Luna712** [comment]
My PR appears to fix it (when doing basic tests in a new install of CloudStream Debug anyway).
I apologize if that was not the correct way to do it afterall.
