### ISSUE TITLE
Remove border in Emulator layout

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#654]
### Describe your suggested feature

I am using Cloud Stream on my laptop. I like the emulator layout. But the border surrounding is very annoying. Remove the border layout or make an option on layout Sitting to turn on/off border layout.
If the heading Movie image switch automatically after a certain period of time, then the app will look more beautiful.
And I found that Movie's **icon** and **name** too small. It is hard to see. Make it some bigger or add zoom in zoom out option.

<img width="960" alt="image" src="https://github.com/recloudstream/cloudstream/assets/107425940/c56afe93-6928-47c1-83b0-0a9a2ca3a2b7">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
I agree, this is kinda annoying in TV layout as well. At least it shouldn't look so bright if we need something to show what is selected it should blend a bit better.
