### ISSUE TITLE
From Aniyomi

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#658]
### Describe your suggested feature

I am searching for **Cloud Stream 3** Alternatives. I found that everyone suggest **aniyomi** is the most competitor. As usual, I download then install **aniyomi** on my device. Pretty good app. But not good as **Cloud Stream**. **Anioyomi** is the best app for anime lover. 
However, there are some beautiful features in this application that are not present in **Cloud stream 3**. Such as, **App Them**, it's offer lot of app them.

![Screenshot_20231006-234442](https://github.com/recloudstream/cloudstream/assets/107425940/e84ffabc-f324-4f69-a856-6aadd3189e1a)

 **Extension pinning & Extension disabling** 
It helps to search only from pin extension.

![Screenshot_20231006-232904](https://github.com/recloudstream/cloudstream/assets/107425940/3cfb3b96-6acc-4816-8244-5e3e4b537dc6)

**Filter Search** 
Anioyomi offer filter search,

![Screenshot_20231007-001343](https://github.com/recloudstream/cloudstream/assets/107425940/b0020461-1692-402c-9f4e-2556c3f06e5a)

**Lot of extension**
Anioyomi offer a lot of extension. Many extensions are not work in Cloud stream but the same extension work excellent in Aniyomi. 

My question is that Aniyomi & Cloud Stream are both Open Source project and write in Kotlin. Then why not use some features copied from Anioyomi?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
you cant just grab code from one project and put in another one and expect it to work. This is very much the case with aniyomi as they use compose while we use xml, so at best we can take inspiration but none of the code. what you are asking is the equivalent of asking a baker to read a recipe for some very good meatballs, it is simply not applicable. 

all the features you asked for are duplicates

**Comment by LagradOst** [comment]
furthermore anioyomi is a fork of tachi, one of the most developed open source android projects, while cs3 is more or less just me writing all the UI and logic. you really cant expect netflix like quality from a hobby project developed mostly by just me. when it then comes to extentions is simply because anioyomi updates the extentions, while not as many actually maintain for cs3

**Comment by EHMilon** [comment]
I understand.
