### ISSUE TITLE
Library Sections

### ISSUE THREAD

**Issue by EHMilon** [recloudstream/cloudstream#659]
### Steps to reproduce

On library, there are many section Watching, On-Hold, Dropped, Plan to Watch. Suppose I have some Movies to Plan to Watch. If I click on a movie and then try to back than every time it goes Watching Section. It should be stayed in Plan to Watch Section.

### Expected behavior

After back from Movies/ TV Series from Plan to Watch or other section, it should be stayed in same section.

### Actual behavior

Every time try to back from a movie save to plan to watch and press the back button it goes Watching Section instead plan to watch section.

### Cloudstream version and commit hash

4.2.0 177b1e4

### Android version

Android 12

### Logcat

```java
--------- beginning of main
10-07 01:28:28.497 10513 18277 I gralloc4: register: id=24f00010284, vaddr=0x7ad997f000
10-07 01:28:28.509 10513 18277 I gralloc4: register: id=24f00010285, vaddr=0x7a73f8c000
10-07 01:28:28.548 10513 18277 I gralloc4: register: id=24f00010286, vaddr=0x7a73b15000
10-07 01:28:28.565 10513 18277 I gralloc4: register: id=24f00010287, vaddr=0x7a7369e000
10-07 01:28:31.687 10513 18277 I gralloc4: unregister: id=24f00010285, vaddr=0x7a73f8c000
10-07 01:28:31.687 10513 18277 I gralloc4: unregister: id=24f00010286, vaddr=0x7a73b15000
10-07 01:28:31.693 10513 10513 I gralloc4: unregister: id=24f00010284, vaddr=0x7ad997f000
10-07 01:28:31.694 10513 10513 I gralloc4: unregister: id=24f00010287, vaddr=0x7a7369e000
10-07 01:28:31.991 10513 10513 W MediaRouter: Ignoring invalid provider descriptor: null
10-07 01:30:13.977 10513 18277 I gralloc4: register: id=24f000102d2, vaddr=0x7ad997f000
10-07 01:30:13.994 10513 18277 I gralloc4: register: id=24f000102d3, vaddr=0x7a73f8c000
10-07 01:30:14.022 10513 18277 I gralloc4: register: id=24f000102d4, vaddr=0x7a73b15000
10-07 01:30:14.038 10513 18277 I gralloc4: register: id=24f000102d5, vaddr=0x7a7369e000
10-07 01:30:18.759 10513 10513 E Dialog  : show dialog view = DecorView@ba5fce9[MainActivity]
```

### Other details

<figure class="video_container">
  <video controls="true" allowfullscreen="true" poster="path/to/poster_image.png">
    <source src="/storage/emulated/0/Movies/screen-20231007-014430.mp4" type="video/mp4">
    <source src="path/to/video.ogg" type="video/ogg">
    <source src="path/to/video.webm" type="video/webm">
  </video>
</figure>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
known issue
