### ISSUE TITLE
Reload links not working

### ISSUE THREAD

**Issue by SANCTI-afk** [recloudstream/cloudstream#661]
### Steps to reproduce

Reload links not working

### Expected behavior

Reload links not working

### Actual behavior

Reload links not working

### Cloudstream version and commit hash

1w1h1o1k1n1o1w1s

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by SANCTI-afk** [comment]
Who on earth  "reload links"is similar to " subtitles not working " , mr. Intelligent ?

**Comment by LagradOst** [comment]
I need a bit more info than that

**Comment by SANCTI-afk** [comment]
> I need a bit more info than that

Believe me this time not necessary, reload links never worked on any phone of mine or my tv , when all links are timed out , doing reload links doesn't solve the issue I have to close the app and relaunch to get new refreshed links,
To experience it yourself you need to play some movie then take a 7hours nap and when you wake up , all links should be timed out as they are not permanent from the source, try doing reload links , and I'm sure you won't get new links

**Comment by Luna712** [comment]
@LagradOst If I understand the issue correctly then yes I've noticed this issue as well. If links expire while CloudStream is still open they don't ever refresh, I'm not sure if that's a provider issue or a CloudStream issue though.
