### ISSUE TITLE
PC App?

### ISSUE THREAD

**Issue by TheStxfan** [recloudstream/cloudstream#664]
### Describe your suggested feature

I would really like to have a PC version of the CloudSteam app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
This will most certainly not happen. Use an emulator for PC, like BlueStacks, or what is mentioned above.

**Comment by LagradOst** [comment]
out of scope for this repo
