### ISSUE TITLE
Custom Watchlists

### ISSUE THREAD

**Issue by Codytech30** [recloudstream/cloudstream#67]
### Describe your suggested feature

Just a suggestion. What if we could create watchlists that we name ourselves just to organize everything. I’m a bit of a clean freak. But it’s not a super big deal for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
No
