### ISSUE TITLE
Save states for title scroll positions

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#670]
### Describe your suggested feature

It would be nice if states could be saved. It is saved on the homepage popup, but unless you open the popup it isnt saved for homepage sections if you select a title and go back you have to start the scroll from the beginning again. Additionally the same is the case for the library, if you select a title in the library and then go back it should resume your previous state rather than having to scroll all the way down again. This is especially annoying to have to do for large libraries and for the homepage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
ui is recreated, not smth we control

**Comment by Rayforest** [comment]
It is not possible for some reason. Idk why but that is the way it is. Really hope this was possible tho, as on tv this would be quite useful

**Comment by Luna712** [comment]
> ui is recreated, not smth we control
@LagradOst 
How come it works for the popup then, is there a way to do something similar for library and home page without popup?

**Comment by LagradOst** [comment]
the popup is not actually recreated, it is only hidden and then unhidden when the user comes back
https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/ui/home/HomeFragment.kt#L451

**Comment by LagradOst** [comment]
if you want to actually save the states, then you must have android figure out it is the same scroller somehow or implement it programmatically and that is tricky as recyleviews has not absolute scrollx

**Comment by Luna712** [comment]
> if you want to actually save the states, then you must have android figure out it is the same scroller somehow or implement it programmatically and that is tricky as recyleviews has not absolute scrollx

@LagradOst 

Maybe this can't be done on the homepage or even search very easily, but I wonder if it would be easier to do it for the library since it is just a single page scroll view, rather than multiple scrolls?

**Comment by Luna712** [comment]
@LagradOst is it just me or is this actually fixed (on the homepage anyway, not library or search) (sometimes anyway, it doesn't work 100% of the time but about 70% this seems to work now, which is an amazing improvement!)

**Comment by LagradOst** [comment]
only did homepage, and that should be working 100% of the time

**Comment by Luna712** [comment]
> only did homepage, and that should be working 100% of the time

@LagradOst 

That's an amazing improvement thanks a ton! It actually does seem to work 100% of the time, except for continue watching, which doesn't.

**Comment by LagradOst** [comment]
> That's an amazing improvement thanks a ton! It actually does seem to work 100% of the time, except for continue watching, which doesn't.

Yes, that is what it is supposed to do. It is not a bug, simply what I did

**Comment by Luna712** [comment]
> > That's an amazing improvement thanks a ton! It actually does seem to work 100% of the time, except for continue watching, which doesn't.
> 
> Yes, that is what it is supposed to do. It is not a bug, simply what I did

@LagradOst 

It makes sense, sorry if I wasn't being clear, I wasn't complaining about that behavior, it's fine, it was just me not realizing I was on continue watching the first message here, and that's why I mistakenly said it didn't work 100% of the time.

**Comment by Luna712** [comment]
Thanks a ton for all the work with this @LagradOst, this is an amazing improvement!

**Comment by Luna712** [comment]
Although not a huge deal, this is still a huge improvement, it still doesn't work for vertical scroll in library.
