### ISSUE TITLE
OK.ru Dosn't work after recent updates

### ISSUE THREAD

**Issue by LyuboA31** [recloudstream/cloudstream#672]
### Steps to reproduce

1. choose source that uses OK.ru like Anichi
2. choose OK.ru as source
3. Dosn't work anymore after recent updates 

### Expected behavior

OK.ru Dosn't work after recent updates 

### Actual behavior

to start episode like normal

### Cloudstream version and commit hash

4.2.0 33eb3a3

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is a provider issue, this is the wrong repository for that. Make the issue on the corresponding extension repository.
