### ISSUE TITLE
Utilize IMDb ID when available when saving items to the library

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#684]
### Describe your suggested feature

If it is available for specific entries, I think using the IMDb ID to save items to bookmarks/library would be a good idea. This would help prevent duplicates if they are the same entry. For providers that don't use the IMDb ID something like #622 would be a very useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
ye, duplicate id checking might be possible, but I don't see how that is useful

**Comment by Luna712** [comment]
> ye, duplicate id checking might be possible, but I don't see how that is useful

I mean so if you add it to the library once from one source and the IMDb ID matches then it shows as in the library on other providers supporting IMDB ID as well. And the duplicate title check would be used as an alternative so you can not accidentally add duplicates. I spent two hours yesterday clearing up duplicates in my library is why I created this to make it easier to prevent that from happening on accident.

**Comment by Luna712** [comment]
Now that I think about that there is problems with doing so, maybe just checking and giving an alert dialog if title or imdb id matches to confirm if you want to add it to library again. As there are reasons to add multiple sources I suppose.

**Comment by Luna712** [comment]
> ye, duplicate id checking might be possible, but I don't see how that is useful

@LagradOst 

#691 now does what I meant with this. Sorry if I was not being clear on what I meant.
