### ISSUE TITLE
New provider

### ISSUE THREAD

**Issue by TheStxfan** [recloudstream/cloudstream#729]
### Describe your suggested feature

Could you please add a provider for this bulgarian movies site?
https://filmisub.cc/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
this is the wrong repo

**Comment by TheStxfan** [comment]
> this is the wrong repo

What do you mean?

**Comment by LagradOst** [comment]
this repo is for the app only, not what extentions you want to include in it
