### ISSUE TITLE
Add a site please

### ISSUE THREAD

**Issue by Alannnnnnnnnnnnnnn** [recloudstream/cloudstream#73]
### Describe your suggested feature

hello, I am French and I use the CloudStream application a lot, unfortunately only French-Stream.re works, can you add other sites in French? 

here is a list of streaming sites you could add: wiflix.zone 
french-manga.net 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
please do not ask about provider related enhancements here
