### ISSUE TITLE
Please add or fix those bangladeshi server.

### ISSUE THREAD

**Issue by DiscountProttoyHeron** [recloudstream/cloudstream#745]
### Steps to reproduce

In your app, there is some extension like banglaPlex and flbd. But its not working. In our country people has a lot of demand for Bangladeshi movie series cartoon etc. So please fix those as soon as possible. 

### Expected behavior

BanglaPlex and FLBD should work properly 

### Actual behavior

![Screenshot_2023-11-02-01-22-50-023_com lagradost cloudstream3](https://github.com/recloudstream/cloudstream/assets/148486794/b8abc13b-863c-4372-8183-894f27e10b55)

![Screenshot_2023-11-02-01-22-43-068_com lagradost cloudstream3](https://github.com/recloudstream/cloudstream/assets/148486794/4a0111fa-728e-4c6e-b034-b0a6c2c42484)

BanglaPlex and flbd server showing this

### Cloudstream version and commit hash

15333123

### Android version

Android 10

### Other details

If u can plz add many more extensions or server for Bangladeshi people. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
This is the wrong repo, create an issue on the repo with this provider
