### ISSUE TITLE
Video sources list on clicking 'play with VLC' 

### ISSUE THREAD

**Issue by Rayforest** [recloudstream/cloudstream#747]
### Describe your suggested feature

It would be nice to have this useful feature added on clicking the 'play in VLC' button. It is mostly useful in TV layouts as it easily let's us choose which source we want. This dialogue box is already present for 'play in browser' and also 'play in mpv'

### Other details

![Screenshot_2023-11-02-11-54-12-59_cfa2fd239c8cded9285432912d0e0818](https://github.com/recloudstream/cloudstream/assets/124686957/d429671f-33f5-4971-b33e-f876cbe0425d)
![Screenshot_2023-11-02-11-54-26-63_cfa2fd239c8cded9285432912d0e0818](https://github.com/recloudstream/cloudstream/assets/124686957/b9d939ad-0fc7-4971-980d-d54ddec3213f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Rayforest** [comment]
> on the top right you should have a drop down menu with the sources.

@catnet23 Yes, I'm aware of that drop down menu. Still it would be good to have this feature for 'play in vlc' too like the others. It might not be hard to code as this is a feature that already exists in some way

**Comment by fire-light42** [comment]
> > on the top right you should have a drop down menu with the sources.
> 
> @catnet23 Yes, I'm aware of that drop down menu. Still it would be good to have this feature for 'play in vlc' too like the others. It might not be hard to code as this is a feature that already exists in some way

It is very easy to change, but it was decided on this because vlc has m3u8 support so you can choose the mirror directly in vlc instead

**Comment by asl97** [comment]
Honestly, I rather advocate for changing 'copy link' to 'share link' as the share menu include but not limited to 'copy to clipboard', vlc and other media players.

It would be a suitable substitute to this and other issues.

**Comment by Rayforest** [comment]
> Honestly, I rather advocate for changing 'copy link' to 'share link' as the share menu include but not limited to 'copy to clipboard', vlc and other media players.
>
> It would be a suitable substitute to this and other issues.

That is an excellent idea!

**Comment by Rayforest** [comment]
> It is very easy to change, but it was decided on this because vlc has m3u8 support so you can choose the mirror directly in vlc instead

I see. It's cool then. It is only a small problem, but if for example a source does not work and while we click on 'play in VLC' and the movie opens with this source then it is impossible to change the source on TV. The source change on vlc tv can only be done after the buffering has been completed for some reason, but it can be easily changed on phone even while buffering happens. So if there is some unlimited buffering and such like it then the movie becomes inaccessible through vlc. I know it is a niche problem, but if that video sources could be added then it won't remain useless

**Comment by fire-light42** [comment]
> The source change on vlc tv can only be done after the buffering has been completed for some reason, but it can be easily changed on phone even while buffering happens. So if there is some unlimited buffering and such like it then the movie becomes inaccessible through vlc. I know it is a niche problem, but if that video sources could be added then it won't remain

Create an issue on VLC then, but if that does not get fixed then we will change the behavior
