### ISSUE TITLE
Add this link in multilingual extension 

### ISSUE THREAD

**Issue by uzairhaider502** [recloudstream/cloudstream#75]
### Describe your suggested feature

Kindly add this link website link in multilingual extension coz other dubbed website link not giving a exact response like what i want....
so please add this link in multilingual extension
https://www.hindimoviestv.com/
ThankYou. 

### Other details

https://www.hindimoviestv.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
please do not ask for providers here
