### ISSUE TITLE
Most of the english repositories don't work

### ISSUE THREAD

**Issue by Dennis8095** [recloudstream/cloudstream#758]
### Steps to reproduce

I redownloaded both the app and the repositories and they do not work. There are only 3-4 ones that work and they are only with animes.

### Expected behavior

It should work as always, but now a few days it stopped working 

### Actual behavior

It doesn't work, I did the provider test+ I tried lots of movies to see if they work and they don't 

### Cloudstream version and commit hash

4.20

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is the wrong repository to report outdated extentions, try pre-release and report this on the repository hosting the extentions you use
