### ISSUE TITLE
 Can you please add webview 

### ISSUE THREAD

**Issue by Shoaib12564** [recloudstream/cloudstream#759]
### Describe your suggested feature

A lot of extensions require access to Google Drive, but there is no option to grant it. 

### Other details

Please add a webview option to Cloudstream 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Are you referring to Aniyomi extensions in Cloudstream? Please make an issue in the appropriate place: https://github.com/CranberrySoup/AniyomiCompatExtension

**Comment by Shoaib12564** [comment]
There is no option to address Google drive access to cloudstream 
Please add webvew option to cloudstream

**Comment by Blatzar** [comment]
Is this Google drive aniyomi extension or not?

**Comment by Shoaib12564** [comment]
There are no issues with Aniyomi's extension, the real problem is with Cloudstream and not any webview option

**Comment by Blatzar** [comment]
Cloudstream has no google drive integration. I do not understand what the issue is if it is not related to aniyomi extensions.

Show what you mean with a picture or something of the sort. Where do you want to login??? What needs webview???

**Comment by Blatzar** [comment]
Like I said at first: If this issue is about an Aniyomi extension which is used in Cloudstream then you should make an issue on https://github.com/CranberrySoup/AniyomiCompatExtension

The aniyomi extension might work in aniyomi but it is the responsibility of AniyomiCompatExtension to provide the login, not this app.

**Comment by Shoaib12564** [comment]
Aniyomi have webview
 option![Screenshot_20231110-234942_Aniyomi.png](https://github.com/recloudstream/cloudstream/assets/149332844/83c18385-bf45-4d8d-831c-3dcd2e2ec409)




There is no option for webview 
![Screenshot_20231110-235034_CloudStream Beta.png](https://github.com/recloudstream/cloudstream/assets/149332844/48c6a7a3-1019-4428-8a16-ab3c6938556b)
