### ISSUE TITLE
Please add webview option to cloudstream 

### ISSUE THREAD

**Issue by Shoaib12564** [recloudstream/cloudstream#761]
Please add webview option to the cloudstream 

Lot  of  extensions required for webview option

**Comment by Shoaib12564** [comment]
A lot of extensions need to be accessed by Google drive

But there is no such option to cloudstream

**Comment by Luna712** [comment]
> bruh, chatgpt doesn't know what is cs3,
> 
> edit this issue and explain thoroughly yourself, suppose i added a webview button on results page then clicking it should do WHAT???

@IndusAryan 

WebView just means open it in a browser within the app, using Android System WebView. At least from my understanding Nothing should require it unless you don't have another browser, just using open in browser should be the same thing for most purposes.

**Comment by Luna712** [comment]
Why did you close #759 and reopen again as this?

**Comment by Luna712** [comment]
> ik, but webview should land where(url) already there is open in browser

@IndusAryan 

Yes I know, that is what I meant I see no point of this since "Open in Browser" already exists, and there is WebView fallback functionality already existing for some things.

**Comment by Shoaib12564** [comment]
But there is no such option for Cloudstream

**Comment by Luna712** [comment]
> But there is no such option for Cloudstream to connect with the browser

@Shoaib12564 

Yes there is.

**Comment by Shoaib12564** [comment]
Please add a webview option to Cloudstream

**Comment by Shoaib12564** [comment]
Aniyomi already have a webview option

**Comment by Luna712** [comment]
Repeating the same thing does not help, if you mean something other than this please be more clear.
![image](https://github.com/recloudstream/cloudstream/assets/142361265/4a000494-8b2d-4030-99f4-201e7133413c)

**Comment by Shoaib12564** [comment]
Thanks for responding to my request. Could you please add a webview eview option to Cloudstream?

**Comment by Shoaib12564** [comment]
I'm sorry, but there doesn't seem to be an option like this available for Cloudstream.

**Comment by Shoaib12564** [comment]
![Screenshot_20231113-005017_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/149332844/1e0bdc3e-cd8c-4e21-9eac-9cd12eb82095)
 Webview is used to load links, reload if necessary
