### ISSUE TITLE
Provider can play videos but cloudstream won't start them

### ISSUE THREAD

**Issue by antonw51** [recloudstream/cloudstream#767]
### Steps to reproduce

Get two providers, one that both loads and starts videos and one that doesn't by erroring with "No links found" as well as fails the provider test. Here I'm using SoraStream (working) and VidSrc ("broken").
1. Make sure your "broken" provider doesn't work by playing any video.
2. Assuming that's the case, play the video with the working provider.
3. Switch to the "broken" provider to see it working.

### Expected behavior

The "broken" provider should just be able to load the video without anyother provider since the source is working.

### Actual behavior

The provider doesn't work but can be used as a source when playing from a different provider at first.

### Cloudstream version and commit hash

4.2.0

### Android version

Android 13, (Samsung) One UI 3.1

### Logcat

```java
https://pastebin.com/Ze11RYsC
```

### Other details

_On second thought_, this is could technically still be a provider issue (I think) but it still seems like the app should be able to let you play the movies with the broken provider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [x] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
VidSrc is a special case. When you use SoraStream it polls the VidSrc server correctly which makes your IP whitelisted for a small amount of time, which makes the VidSrc extension work during that time. VidSrc is outdated which is why it does not poll the server correctly.

This is not an app bug, just unintuitive video server behavior.
