### ISSUE TITLE
Add this site 

### ISSUE THREAD

**Issue by Rockymar11** [recloudstream/cloudstream#780]
### Describe your suggested feature

https://mc6.crichd.com/

### Other details

For better sports experience 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Don't request websites here, this is an issue tracker for the app itself
