### ISSUE TITLE
How to add the extension?

### ISSUE THREAD

**Issue by ZooNooU** [recloudstream/cloudstream#8]
### Steps to reproduce

it's not a problem, I'm just here to ask how to add repositories from within the app? I didn't know what link to copy and paste?

### Expected behavior

.

### Actual behavior

.

### Cloudstream version

3.1.2

### Android version

12

### Other details

💀

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
literally just read the first line of the readme

**Comment by C10udburst** [comment]
settings > extensions > add repository > paste repo link

**Comment by ghfs2** [comment]
1. Long-press the 'Testing Repositories' link
2.
![__METH1](https://user-images.githubusercontent.com/110763227/183980298-be11a891-4595-4b6e-9098-339d96175053.png)

(or similar option to open)


OR

1. Long-press link, then...
2. 
![2 right click - 2](https://user-images.githubusercontent.com/110763227/183980523-1159b8a8-52d0-4cfb-8168-255bb5dc4aee.png)

3. follow the steps provided by **C10udburst** above

4. Your URL link may contain `cs.repo/?`. Delete it 
   example:
                  edit   `https://cs.repo/?test.json`  
                   to make `https://test.json`
5. Give the Repo a name
6.  Click 'Add'
7. Now you have repository in your list
8. Click it again to open the repository for adding the plugins of your choice

**Comment by rubbean** [comment]
for the testing repo you first need to enable "Open supported links by default" under the app settings > Set as default > Supported web adresses then enable cs.repo, after that click the link on the repo's github page.

**Comment by ViVi93** [comment]
In my phone the link was not working so i manually pasted this link - https://raw.githubusercontent.com/recloudstream/cs-repos/master/test.json
