### ISSUE TITLE
Add Kurdish providers 

### ISSUE THREAD

**Issue by MohamadBayz** [recloudstream/cloudstream#80]
### Describe your suggested feature

Kurdish providers uses similar video hosts as other sites, like (fembed, sendvid, uqload, youpload, ok.ru, etc) every single of these providers has more than 2 Thousand Movies and thousands of TV Series
All Kurdish Providers (that I remember):
https://kurdsubtitle.net/
https://beenar.net/
https://www.kurdcinama.com/
https://kfilmone.com/
https://shafilm.vip/
https://www.kurddoblazh.com/
https://www.kurdmovie.net/
http://www.movieskurdish.com/

### Other details

Add them as an extension repository.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
as the bot said, please do not request providers here
