### ISSUE TITLE
Please add this Source in pinoymovieshub🇵🇭

### ISSUE THREAD

**Issue by Peigie** [recloudstream/cloudstream#800]
### Describe your suggested feature

Add new source flixembed for pinoymovieshub

### Other details

Video source

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is not the repository responsible for adding sites or updating them. Make an issue on the repo hosting that provider
