### ISSUE TITLE
Add live tv extension for india  "Jio Tv"

### ISSUE THREAD

**Issue by Scordop** [recloudstream/cloudstream#807]
### Describe your suggested feature

Login through a jio number
We should be able to watch
Live tv channels provided by jio tv
And watch past programs provided by jio tv (if possible)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is the wrong repository for adding sites. Create an issue on the repos that host providers.
