### ISSUE TITLE
Video player crashes after playing video for a minute

### ISSUE THREAD

**Issue by vivek1996** [recloudstream/cloudstream#809]
### Steps to reproduce

1. Choose sora stream
2. Play a movie
3. Player crashes 

### Expected behavior

Video should play 

### Actual behavior

Player crashing & extensions are disabled & goes to app home screen. 

### Cloudstream version and commit hash

3c152e0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by vivek1996** [comment]
[logcat.txt](https://github.com/recloudstream/cloudstream/files/13633895/logcat.txt)

**Comment by IndusAryan** [comment]
both logcat and image not uploaded properly, have you touched the buffering settings from player settings?

**Comment by fire-light42** [comment]
Out Of Memory, might be the preview that pushes it too far. However lower your buffer settings

**Comment by vivek1996** [comment]
> have you touched the buffering settings from player settings?

No

**Comment by vivek1996** [comment]
Both buffer size & buffer length is Auto

**Comment by IndusAryan** [comment]
> > have you touched the buffering settings from player settings?
> 
> No

the crash has occured in the preview generator tho, maybe the video quality was very high in both preview and player, out of memory is right by firelight

**Comment by IndusAryan** [comment]
tell provider name, movie and quality you are streaming or episode incase of series

**Comment by vivek1996** [comment]
> tell provider name, movie and quality you are streaming or episode incase of series

![Screenshot_20231211-162105](https://github.com/recloudstream/cloudstream/assets/15796694/36dbd1b3-7c4a-4b21-8c15-134e40ef147b)

![Screenshot_20231211-162230_CloudStream_Beta](https://github.com/recloudstream/cloudstream/assets/15796694/a0512bd6-95fb-47a1-9639-2e1144342f04)


`{"id":1046032,"type":"movie","aniId":null,"malId":null}`

**Comment by IndusAryan** [comment]
works perfectly fine here in my 5 year old redmi note 7, 4/64gb
device issue, 
only thing left is to clear cache of cs3 and then clear device cache then update software and then update apps components like webview, chrome etc from play store

**Comment by fire-light42** [comment]
This might be a problem by sorastream as doing .text on a video stream will "download" the entire movie and cause OOM. Will have to do some testing myself

**Comment by fire-light42** [comment]
Yup, this should not be happening when loading links
![image](https://github.com/recloudstream/cloudstream/assets/147925818/0b7774b2-b2fa-4f2c-b5c5-ed2fcfc2689f)

**Comment by vivek1996** [comment]
Shall I close the issue since this is tracked on https://github.com/hexated/cloudstream-extensions-hexated?

**Comment by IndusAryan** [comment]
ye solved there
