### ISSUE TITLE
Voice Typing for Search Functionality

### ISSUE THREAD

**Issue by opakholis** [recloudstream/cloudstream#814]
### Describe your suggested feature

Enable users to perform searches by using their voice as an input method.

### Other details

Writing using the remote is impractical.

This becomes annoying when the default keyboard app on Google TV doesn't support this feature and I don't want to add a second app just for the Keyboard.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is kinda out of the scope of this project, matter with input is best left up the user.

**Comment by opakholis** [comment]
Exactly. Why not add more options to make it easier for users, right?

Like SS below, users can select input using keyboard or voice.

![Screenshot_20231215-073429_YouTube.png](https://github.com/recloudstream/cloudstream/assets/49778014/9db522e4-dc84-4edc-97d4-bf2b4cc576ed)

**Comment by IndusAryan** [comment]
@opakholis if you really need this you can use inbuilt gboard mic in phones, its works almost same, difference is that you would be pressing mic button from keyboard not app
it is available is most TV's also if remote has mic

**Comment by fire-light42** [comment]
I wont add this, however if someone want to I leave this here https://stackoverflow.com/questions/12308381/android-recognizerintent-speech-recognition

However I still think this is best left to the OS/keyboard/remote

**Comment by Luna712** [comment]
I don't personally think this would be the best from a UI perspective myself.

**Comment by opakholis** [comment]
Well, looks like I need to switch to gboard for this. Thank you all for your responses. 

This thread can be closed🍻
