### ISSUE TITLE
Trakt.Tv implementation 

### ISSUE THREAD

**Issue by aghostbehindyou** [recloudstream/cloudstream#815]
### Describe your suggested feature

I know it's been requested before, but I just wanna re-echo it. I feel Trakt support should be added as well, so users do not have to rely solely on Simkl. I appreciate the efforts of the developers so far.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Duplicate
