### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by soner0000** [recloudstream/cloudstream#825]
### Describe your suggested feature

Subtitles for All Language and Films & Tv Shows

### Other details

![Screenshot_20231219_171233_Gallery](https://github.com/recloudstream/cloudstream/assets/137823110/fb1da485-14b2-4454-8071-dfcb5db74f1a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
this is a provider issue and cant be solved by us
