### ISSUE TITLE
Move upgrade dialog to show in AccountSelectActivity, unless skipped

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#827]
### Describe your suggested feature

I will do this later, but creating the issue so I don't forget, the upgrade dialog, if enabled, should be shown on the app being opened, which means in AccountSelectActivity rather than MainActivity, unless AccountSelectActivity is skipper either due to preference or because there is only one account, then it would show in MainActivity. That way you don't have to select an account, upgrade, which restarts app, then open again and have to select account. It just improves the flow a bit.

Like I said though, I will do this myself in the next couple days if someone doesn't beat me, just creating the issue so I don't forget.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IndusAryan** [comment]
what,updater dialog , is it really needed

**Comment by IndusAryan** [comment]
what,updater dialog?? , is it really needed on account select

**Comment by Luna712** [comment]
> what,updater dialog?? , is it really needed on account select

It should just be shown on app opening IMO since AccountSelectActivity is the first activity shown is just be shown there when the app opens if it is needed.

![Screenshot_20231219_103746_CloudStream Debug](https://github.com/recloudstream/cloudstream/assets/142361265/185fd6a0-afdb-4d2c-8192-7c73b9bf6493)

**Comment by Luna712** [comment]
@fire-light42 thoughts on this? Is it necessary or not? If not necessary then there is probably no point in putting the work into it, but I don't think it would be all that hard...

**Comment by fire-light42** [comment]
> @fire-light42 thoughts on this? Is it necessary or not? If not necessary then there is probably no point in putting the work into it, but I don't think it would be all that hard...

It is a separate activity meaning that I dont know if they can share a request and I dont want to do 2 requests per launch. so I dont think this small pet peeve should be focused given that it only affect ppl that are on the bleeding edge on every prerelease update, and will save at most like 2s every update
