### ISSUE TITLE
Allow to remove items directly from library

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#829]
### Describe your suggested feature

When you remove some extension it becomes impossible to open the item to remove it without readding the source, which it doesn't say which to readd, this then makes it impossible to remove some items from the library, I was able to remove some using the duplicate check feature, but there was a couple that isn't picked up by that and thus now impossible for me to remove. A couple I know the provider but the videos no longer exist making it impossible to remove even if you do know the provider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
this has been on todo a while, the prefered solution that has not yet been implemented is showing the popup like holding on normal results
