### ISSUE TITLE
Fast forward for the player

### ISSUE THREAD

**Issue by Zeddy-Coder** [recloudstream/cloudstream#832]
### Describe your suggested feature

Watching the 200th episode of Bleach, I felt that I was missing fast-forwarding, as it is implemented in the YouTube application. I have attached a video with an example below.

### Other details

https://github.com/recloudstream/cloudstream/assets/83463963/7526b426-e7f1-4c1b-abb1-527326eb0281

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
duplicate and denied because we dont want ppl fucking up attention spans
