### ISSUE TITLE
Watch on vr mode 

### ISSUE THREAD

**Issue by Rockymar11** [recloudstream/cloudstream#839]
### Describe your suggested feature

Please add feature like watch on vr mode just like in YouTube please 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Out of scope for this project
