### ISSUE TITLE
Support for multiple Profiles

### ISSUE THREAD

**Issue by Akv2021** [recloudstream/cloudstream#84]
### Describe your suggested feature

It should work similar to multiple profiles supported in Netflix. 
On app launch the first screen should be "who's watching" and then after selecting profile the current homepage will be launched.
It will help manage the "continue watching" and different bookmark lists on profile level.

### Other details

To simplify things we can keep extensions and app settings common across all profiles. Only "continue watching", bookmark lists and previously selected provider could be saved for each profile.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by imxcr** [comment]
i vote for this ^^

**Comment by LagradOst** [comment]
I already anticipated this feature when making the app, so all bookmarks ect are stored under profiles but you cant switch profiles because there is no UI

**Comment by Akv2021** [comment]
> I already anticipated this feature when making the app, so all bookmarks ect are stored under profiles but you cant switch profiles because there is no UI

Will it be a good idea to create a placeholder ticket/issue for the same so that it can be picked at a later point in time ?
Just a simple option in settings to change the current profile should be enough.

**Comment by binyaminyblatt** [comment]
+1

**Comment by Rayforest** [comment]
I think this would be a good feature when recommended movies and series gets integrated to the library based on the movies and series we watch. Then the multiple user feature makes more sense imo

**Comment by LagradOst** [comment]
In pre, top right
