### ISSUE TITLE
No Links Found 

### ISSUE THREAD

**Issue by soner0000** [recloudstream/cloudstream#840]
### Steps to reproduce

When I want to watch a film or tv shows the app says "No Links Found" and i checked the website i can watch the film but in the app doesn't working and i have pre-version and stable version but the both  doesn't working.

### Expected behavior

And i cant watch a film in cloudstream but i can watch a film in website. VIDEO SHOULD BE PLAYED WITH NO ISSUES!

### Actual behavior

![Screenshot_20231228_201005_Gallery](https://github.com/recloudstream/cloudstream/assets/137823110/a1f8135b-519e-40af-b455-94b8133cebf4)

### Cloudstream version and commit hash

4.3.0 

### Android version

Android 14 One UI 6.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
this repo is not for provider issues

**Comment by Funnyfiend1986** [comment]
I'm facing same issue
