### ISSUE TITLE
SoraStream and SoraStream-Lite issue

### ISSUE THREAD

**Issue by italoboy** [recloudstream/cloudstream#842]
### Steps to reproduce

If you try to download anything from any source then cancel your download or it failed to download, you can never redownload it. 
It fails to redownload and none of sources work anymore.

### Expected behavior

.

### Actual behavior

.

### Cloudstream version and commit hash

4.3.0

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by mizu-048** [comment]
issue with a repository or its extensions has nothing to do with cloudstream, kindly report on the extensions own source.
