### ISSUE TITLE
App not working with VPN

### ISSUE THREAD

**Issue by munendra-kondeti** [recloudstream/cloudstream#845]
### Steps to reproduce

1:-Iam connected to vpn and try to play it's showing some Java socket error 
2:- after disconnected still not connected to internet

### Expected behavior

Need to connect with vpn without error or else vpn not supported.

### Actual behavior

Showing some socket issue exceptions

### Cloudstream version and commit hash

4.3.0

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [ ] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is a provider issue/vpn issue and I have no problem with a VPN.
