### ISSUE TITLE
(Android TV) Audio track error after that multiple audio track PR

### ISSUE THREAD

**Issue by krrishkap** [recloudstream/cloudstream#85]
### Steps to reproduce

Just play anything in superstream in android tv ( i tried with family guy) it throws an error this is happening after that multiple audio track PR , video attached below . 

### Expected behavior

It should play the content as usual

### Actual behavior

it throws an error something related to "audio track init" , exact error is in the video attached. 

### Cloudstream version and commit hash

3.1.4 93daf48

### Android version

Android 9

### Logcat

```java
https://pastebin.com/e8E9UEx6
```

### Other details

https://user-images.githubusercontent.com/86251706/188297351-71bb70e5-166a-463a-9f9e-23ebe676874f.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by krrishkap** [comment]
nvm it got fixed on fresh install

**Comment by krrishkap** [comment]
now its not working in any type of layout

**Comment by Blatzar** [comment]
Yeah i was testing tunneling, see if https://github.com/recloudstream/cloudstream/commit/6f3e9891c5bdaccfddd83efb19c0e929ce9d146f fixes it

**Comment by krrishkap** [comment]
thanx
