### ISSUE TITLE
AnimeSAGA extension is not working

### ISSUE THREAD

**Issue by kusokohei** [recloudstream/cloudstream#852]
### Steps to reproduce

The pre released version of the app also had the same exact issue 

### Expected behavior

When I try to play anything from that server it's give me a blank screen and shuts off 

### Actual behavior

Please tell me a solution for this as this is recently happening previous before the update it was fine 

### Cloudstream version and commit hash

Version : 4.3

### Android version

13

### Other details

Other Hindi extension are also not working seems like the server is the problem but na even after connecting VPN it's still gives the same issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
this is not the repo for extensions
