### ISSUE TITLE
Allow tap and hold gestures to temporarily change playback speed

### ISSUE THREAD

**Issue by x-legion** [recloudstream/cloudstream#862]
### Describe your suggested feature

**Description**

Currently, changing the playback speed requires pausing the video, opening the speed menu, changing the speed value, and resuming playback. This is not very accessible during video watching. 

**Proposal**

- Allow users to tap and hold on the video player to trigger a faster playback speed (e.g. 2x)
- When released, playback returns to normal speed
- The speed multiply value could be set from the usual speed menu

**Benefits**

- Greatly increases accessibility of variable speed playback
- Saves users time compared to current menu approach
- Easy to trigger temporary faster playback when desired

This gesture would make speed control much more seamless during video watching. Please consider adding this capability.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Denied multiple times, this is not tiktok
