### ISSUE TITLE
Can devs add new websites? <3

### ISSUE THREAD

**Issue by soner0000** [recloudstream/cloudstream#873]
### Describe your suggested feature

https://watchseries.pe/ 

https://www.allmovie.com/

https://movie4kto.net/

https://www.yidio.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
No, this is the wrong repository to create site requests
