### ISSUE TITLE
Can devs add new website? 

### ISSUE THREAD

**Issue by soner0000** [recloudstream/cloudstream#874]
### Steps to reproduce

https://watchseries.pe/

https://www.allmovie.com/

https://movie4kto.net/

https://www.yidio.com/

https://www.dizigom1.com/

when this is wrong repo for site requests where is the right repo? 

### Expected behavior

. 

### Actual behavior

. 

### Cloudstream version and commit hash

4.3.1 PRE

### Android version

One Uİ 6.0 android 14 samsung

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
No, this is the wrong repository to create site requests

**Comment by fire-light42** [comment]
the right repo is the repo for a specific extention, check the discord or extentions inapp
