### ISSUE TITLE
Sleep Timer Feature

### ISSUE THREAD

**Issue by Variant1987** [recloudstream/cloudstream#880]
### Describe your suggested feature

Please add a Sleep Timer feature, enabling users to set a specific time for automatic playback cessation. This enhancement aims to optimize user experience by providing a convenient way to control playback duration.

**Benefits**
- Users can personalize the duration of playback to suit their preferences.
- Reduces energy consumption by automatically halting playback when not needed.
- Enhances user satisfaction through added flexibility in app usage.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by IndusAryan** [comment]
reduce energy consumption? what? what do you want atually, close the app after certain time that is chosen by user ?

**Comment by Variant1987** [comment]
Sorry for the confusion. Simply put, I mean a timer button in the video player, e.g. 30 minutes. When the timer expires, the video should be paused and the device should lock itself (should be controlled by the standby time regulated in the system, e.g. 30 seconds screen off). This means that the device does not run all night when you watch a series to fall asleep, which in turn saves power. In addition, the next day you don't have to look for the episode you were watching last

**Comment by fire-light42** [comment]
I would suggest using VLC or any other foss apps that handle this, however I think it is out of the scope of this project. That being said, I would accept that PR if someone wanted to do it

**Comment by ayush99336** [comment]
Yes much needed
