### ISSUE TITLE
Site request in cloudstream app

### ISSUE THREAD

**Issue by Mrunknow3** [recloudstream/cloudstream#882]
### Describe your suggested feature

Ik you can go GitHub provider and request, but most people don't know github and don't understand I see some people are request in reddit i want cloudstream app site request in app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
you should request addition of new sites on a plugin repository
