### ISSUE TITLE
Add support for "Continue watching" on Google TV home screen

### ISSUE THREAD

**Issue by KibSquib48** [recloudstream/cloudstream#884]
### Describe your suggested feature

Google TV has a "Continue watching" section on its home screen which shows recently watched TV shows and movies from different streaming services, and I think it would be very nice and convenient if CloudStream could support this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
Not really an option:

1. Requires a server
2. Requires a certification process

Both are a no-go

https://developer.android.com/training/tv/discovery/watch-next-add-programs#steps

**Comment by KibSquib48** [comment]
Oh, that sucks

guess I should close this then
