### ISSUE TITLE
Doesn't work on TV anymore

### ISSUE THREAD

**Issue by HiddenLeveI** [recloudstream/cloudstream#886]
Hello, I have a TCL Android TV from 2020 and I've had cloud stream on there for over a year and it worked fine. Now, every thing I click on says "no link found."

I tried to install the beta, remove and re add the updated English repository, it just won't work. But in my phone, it still works fine. Idk what to do at this point.

**Comment by HiddenLeveI** [comment]
Update, so it was a bit of the pain as you can't type easily on TV, but I managed to delete the og and the beta, and download the newest version of cloud stream that isn't the beta, then added the repository, and now it seems to work for the most part.

My phone still uses an old version I like from a long time ago because I can work that. So idk why my TV needed to do this, I only watched 1 show but it seems to work again.

**Comment by fire-light42** [comment]
closed as it solved? btw you can download all repos by using the url `megarepo`
