### ISSUE TITLE
Scrolling up/down isn't smooth at higher refresh rates

### ISSUE THREAD

**Issue by kryptobolt200528** [recloudstream/cloudstream#894]
### Steps to reproduce
Just scroll up/down on homepage on device with higher screen refresh rates(>60Hz)

### Expected behavior

Scrolling up/down on homepage should be smooth for higher refresh rates.

### Actual behavior

Scrolling up/down on homepage isn't smooth for higher refresh rates.

### Cloudstream version and commit hash

4.3.0

### Android version

Android 10/11/13

### Priority
I don't think the issue is serious/needs immediate attention, also acknowledge that loading a larger set of "thumbnail" might be a part of issue, but the issue is fixable in my opinion.
I was a bit hesitant to add this issue but anyways, scrolling up/down on homepage isn't smooth at higher refresh rates(120/90),but scrolling sideways is quite smooth.
Have verified issue on Android 10/11/13 on various devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is because the homepage is recycled and that more or less means that it has to recreate all views when scrolling (including loading images). This only has a slight noticeable experience when scrolling up and now for you. However we choose that as without it a very noticeably lag would happen when going into the homepage.
