### ISSUE TITLE
Add " toonstream " website for Hindi and English anime 

### ISSUE THREAD

**Issue by Indian-goku** [recloudstream/cloudstream#897]
### Describe your suggested feature

Website -> " https://toonstream.in "

### Other details

Add toonstream website as plugin for Hindi anime and cartoon. It is ads free and also it has no re captcha. 
Website -> " https://toonstream.in "

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This repo is not for site requests, make this issue on the extentions repo instead
