### ISSUE TITLE
Image on top of android tv  homescreen gets cut off when you browse between new featured movies/series

### ISSUE THREAD

**Issue by JimZiii** [recloudstream/cloudstream#905]
### Steps to reproduce

1. Start CS on Android tv
2. Press down once to be able to browse between the featured movies/series
3. The top of the image is now cut off and it's impossible to browse the featured content without it cutting off
![SC 1](https://github.com/recloudstream/cloudstream/assets/7854537/e1288da3-eaf1-4fd6-8fe1-7a1160283aca)
![SC 2](https://github.com/recloudstream/cloudstream/assets/7854537/c32d2680-e205-43fe-a280-d0ac06680ba5)

### Expected behavior

Would be nice if it didn't cut off so you're able to browse featured content without moving up every now and then to look at the full image and then moving back down to continue browsing featured content

### Actual behavior

Gets cut off

### Cloudstream version and commit hash

4.3.1 01f21e0

### Android version

Android 11 on android tv. Nvidia Shield 2019 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is impossible to solve atm as you cant navigate to unrendered views and the home scrolling is a recyleview (does not render views outside the screen view for performance)

**Comment by JimZiii** [comment]
> This is impossible to solve atm as you cant navigate to unrendered views and the home scrolling is a recyleview (does not render views outside the screen view for performance)

No idea what you're talking about, this can be fixed by adjusting the centering because currently the screen centers on the button you got selected, which is why the screen is centered on the play button when you move down one step to browse between featured content

**Comment by fire-light42** [comment]
![image](https://github.com/recloudstream/cloudstream/assets/147925818/586fcefa-21d0-4668-8291-7c782718f293)
Here the views that are on screen is black and the views outside the screen is rendered in red. In this case we try to navigate to a view offscreen in lets say continue watching then it should move down and show that. However because the view is offscreen, it is not rendered and **CANT** be focused. The reason why it centers the buttons is because otherwise you would not be able to navigate down on TV and this was a real issue before

**Comment by fire-light42** [comment]
It is not that I dislike what you want, but it is simply that by implementing it you cause another more severe issue

**Comment by fire-light42** [comment]
That being said, it may be possible to adjust it slightly in this case

**Comment by JimZiii** [comment]
> That being said, it may be possible to adjust it slightly in this case

My bad, i misunderstood your first reply.
Yea i remember this not being a thing till you guys updated the centering, and if i switch to emulator layout in settings its not hidden. But that brings some other issues like not being able to move below the watching, plan to watch, etc etc buttons if i hid that row by not having any button selected.

But yea, i just wanted to point it out and hopefully you can find a workaround you're comfortable with. There's probably more ways than the ones i mentioned, you could even lower the image slightly, but I'll leave that up to you guys.

**Comment by fire-light42** [comment]
I think this will get fixed in the TV PR https://github.com/recloudstream/cloudstream/pull/950 that will soon be merged

**Comment by JimZiii** [comment]
@KingLucius just updated and saw your fix, thnx man. haven't used the featured content at all till now. The issue pretty much made it unusable, unless you wanna move the selector up on every movie/series to see what it is and back down to scroll to the next one. 
I really appreciate this one
