### ISSUE TITLE
Two Malware Detection

### ISSUE THREAD

**Issue by AuraNight80** [recloudstream/cloudstream#907]
### Steps to reproduce

First Force-Stop And Clear Cache Cloudstream App Then Connect Psiphon Pro VPN And Then Open Cloudstream It Will Show Two Malware Detection One Is Like Name Rmnert And Another Don't Remember And It Is In Blue Real Base App.

### Expected behavior

Don't Know.

### Actual behavior

Don't Know Maybe Slow Down Device.

### Cloudstream version and commit hash

Latest

### Android version

12

### Logcat

```java
If Want Reply.
```

### Other details

Plz Remove Malware Otherwise App Is So Good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
False positive

**Comment by AuraNight80** [comment]
> all your issues are hard to read.
> 
> it's called false positive. cloudstream is open source and you can go through the code.
> 
> > Plz Remove Malware Otherwise App Is So Good.
> 
> no malware
> 
> > Don't Know Maybe Slow Down Device.
> 
> nice accusation without evidence

I Am Not Accusing But Psiphon Pro App Ehich Is A VPN App Which Alert Us When A Malware Traffic Is Detected Alert Us And It Alerted Me So I Say You Can Atleat Check If Your App Have Malware Or Not.

**Comment by asl97** [comment]
How sure are you that it wasn't another app on your device?

Or that you installed a bad extension or cloudstream from a bad source?

You can't bother providing the version, 'Latest' is not a version or is that what it says on the version of cloudstream you installed?

If so, you clearly installed a random untrusted version of cloudstream, the official app has the version at the bottom of the setting page, the version number and the 8 characters commit.

The fact that pressing the `show logcat` button only gives you `If Want Reply.` is just another sign that it isn't the official cloudstream app that you installed.

____

On a fresh install with your 'instruction' of clearing cache, the app only connects to api.github.com, probably just to check for updates.

If your VPN is warning about api.github.com, then it's stupid.

**Comment by AuraNight80** [comment]
No It Was Not Other App It Only Show Malware Info When Opening Your App And It Is Not A New Issue Approx 1,2 Years Ago When I Opened Your App With Psiphon Pro VPN Connected It Also Showed Same Malware Info Alert And It Has 100M+ Download On Playstore And Widely Used And It Is Not Warning About api.github.com And The Version I Am Using Is 4.30 And I Think You Misunderstood Me When I Write Reply Me If Want Is That I Am Telling You If You Want Logcat Then Reply Me Because I Had To Copy Logcat And Then Paste Logcat And The App Is Downloaded From This Website Which I Think Is Your's I Think My App Is Geninue So You Can See It By Yourself.
Website:-https://cloudstream.on.fleek.co/
