### ISSUE TITLE
Multiple Downloads Problem

### ISSUE THREAD

**Issue by AuraNight80** [recloudstream/cloudstream#908]
### Describe your suggested feature

Hey When You Try To Download Multiple Episodes Or Say Movies Or Anything You Can't Download More Then 3 Downloads At A Time If You Put Episode To Download It Will Say Download Started But Download Is Not Started And Only Start If One Of Previous Tgree Downloads Is Finished Which I Think You Should Increase Limit And So I'd We Download Multipke Files From More Than 1 Website In Your App The Downloads Fails Which Is Not Good,Plz Fix That.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AuraNight80** [comment]
> Limited to 3 to not lag phones

That's Very Goof But If You Add Option To Increase Limit With Also Warning That It Can Lag Then It Would Be Bery Good For People Like Us Who Like To Download For Their Vacations On Their Village Or When Internet Is Not Available To Watch It With Their Families Then It Will Be Very Good,It's Your Choice Then.😊

**Comment by Hal-Jordan2814** [comment]
I agree if the default is 3 downloads at a time but there should be an option in settings to increase or decrease it
