### ISSUE TITLE
Schedule Download Option

### ISSUE THREAD

**Issue by AuraNight80** [recloudstream/cloudstream#909]
### Describe your suggested feature

Hey I Would Like You To Add A Schedule Download Option So That We Can Schedule Download To Start On A Specific Time Or Date Like 1DM+ App Hey I Am An Android User I Have Mobile Connection Which I Get Unlimited From Time 12 A.M To 6 A.M So I Had To Copy Link From Your App Of Episode And Then Put It In 1DM App So That My Download Start Automatically At 12 A.M I Put My 1DM Battery Udage To Unrestricted And Background Data To Allow And Also Locked The App So It Don't Get Killed I Want You To Add The Same Option From 1DM To Your App To Schedule Downloads You Can Use 1DM App To Understand Mire In Scheduling Otherwise Your App Is Great App I Am An Old User Like For 3 Years.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
1DM is closed source and wont be supported
