### ISSUE TITLE
Make It A Window App Or Mac's App Too

### ISSUE THREAD

**Issue by AuraNight80** [recloudstream/cloudstream#910]
### Describe your suggested feature

Hey I Want You To Make It A Windows App Too Plz I Know It will Be A Lot Of Work But If You Would It Would Be Great Because I Have Windows Laptop That I Would Like To Watch Free Movies And Shows By Your App In Big Screen And If So Making For Windows You Can Also Maje It For Macs Too

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Out of scope

**Comment by AuraNight80** [comment]
> all your issues are hard to read.
> 
> for windows: https://rentry.org/wsa https://cutt.ly/cs3onwin11
> 
> for mac: stop using mac :)

Thanks,I Appericiate It Very Much,You Are Very Smart,Love You❤.
