### ISSUE TITLE
FOR TELUGU PEOPLE

### ISSUE THREAD

**Issue by Kira0116** [recloudstream/cloudstream#911]
### Describe your suggested feature

Please add this two sites it's just enough for all the telugu people 😔🙏🙏
Please do this little help for us 😭😭 I mean telugu is the second largest speaking language in 🇮🇳 please consider us.

### Other details

Teluguflix :- https://ww2.teluguflix.biz/
(Provides every telugu movie with links)

Animerulz:- https://animerulz.in/home/
(No skip ads thing and have every language especially telugu)

Movierulz:- https://5movierulz.red/ (optional)
(Main provider for telugu people not much an ui and easy to code)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This repo is not for site requests, make an issue on the respective extentions repo
