### ISSUE TITLE
Add subtitle like opensubtitle

### ISSUE THREAD

**Issue by Mrunknow3** [recloudstream/cloudstream#916]
### Describe your suggested feature

Open subtitle we have but open subtitle some time doesn't match with movie,series or anime

### Other details

I request you add subscene and Subdl it's like opensubtitle. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Already exist

**Comment by Mrunknow3** [comment]
Where? Cloudstream have only open subtitles.
