### ISSUE TITLE
Another app source

### ISSUE THREAD

**Issue by gadz91** [recloudstream/cloudstream#918]
### Describe your suggested feature

Hoping you can add the source of this app. It has a lot to offer movies/series as well. I do not know if all of you can explore the source of it. It is good if these all are in this app.

It has a lot of adds so this is very annoying as well while you are using it.

 More power to all of you and to this app. ☺❤

You can download here and explore this app. https://f34g9.nt73e.com/share/cinemaen/index.html?test=&vod_id=160489&vod_from_id=0

![Screenshot_2024-01-28-00-45-27-63_7b3a4166d2e54fb44c6cb44b324512ec](https://github.com/recloudstream/cloudstream/assets/86019036/39344044-8be7-435d-8ec3-233ced78e3f3)
![Screenshot_2024-01-28-00-45-42-59_7b3a4166d2e54fb44c6cb44b324512ec](https://github.com/recloudstream/cloudstream/assets/86019036/dc1a4f74-08e8-4ba6-ae1c-426d608bc800)
![Screenshot_2024-01-28-00-45-46-40_7b3a4166d2e54fb44c6cb44b324512ec](https://github.com/recloudstream/cloudstream/assets/86019036/b9e5f73d-244a-4e5d-9d3e-58480d44162a)
![Screenshot_2024-01-28-00-46-00-52_7b3a4166d2e54fb44c6cb44b324512ec](https://github.com/recloudstream/cloudstream/assets/86019036/a01d85a4-dc58-4ba1-ab41-665b78419897)
![Screenshot_2024-01-28-00-46-03-93_7b3a4166d2e54fb44c6cb44b324512ec](https://github.com/recloudstream/cloudstream/assets/86019036/c56c41bd-70d4-489e-8162-e79f27f85170)
![Screenshot_2024-01-28-00-46-07-76_7b3a4166d2e54fb44c6cb44b324512ec](https://github.com/recloudstream/cloudstream/assets/86019036/5e93767d-b13a-41a8-bf26-c4bbe9aeff55)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
This is not the place to make source requests. This repository is for the app itself not the extensions.

**Comment by gadz91** [comment]
> This is not the place to make source requests. This repository is for the app itself not the extensions.

Ok I will remake it 😊
