### ISSUE TITLE
Feature request for online subtitles 

### ISSUE THREAD

**Issue by ShankarKSH001** [recloudstream/cloudstream#924]
### Describe your suggested feature

Add option for adding online subtitles to get subtitles from opensubtitles.org like mxplayer.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by inventor7** [comment]
There's already this option , in the video player  clikc on **source** then on the right side there's the **subtitles** section with 3 options :

1- There's subtitles provided from the provider itself, just tap them and it will load automatically. 

2-Another option is to get subtitles from your local storage,  where you can download subtitles and import them into the app.

3-Online Subtitles :the last option , it's under the last 2 options:
![Screenshot_20240205-072414_CloudStream Beta.jpg](https://github.com/recloudstream/cloudstream/assets/63302853/42a15078-77bf-4f12-b5e0-08b5941bb8ad)



** you must have an account of Opensubtitles.org and log in in**
 **settings>>Account>>OpenSubstitles**

![Screenshot_20240205-072326_CloudStream Beta.jpg](https://github.com/recloudstream/cloudstream/assets/63302853/a0405c5a-1861-4047-acd5-0a690295aad3)

**Comment by ShankarKSH001** [comment]
Yes I already i tried it but it gives less no of subs than MX player in some contents no subs found.
Any possibility for enhance the feature.

**Comment by fire-light42** [comment]
online subtitles already exist
