### ISSUE TITLE
Adding Starlive.xyz Provider

### ISSUE THREAD

**Issue by ExoZNiK** [recloudstream/cloudstream#93]
### Describe your suggested feature

Hello i just want to suggest to add starlive.xyz as livestreaming provider in multilanguage repository. It's a reliable source for all sports (not only football which is already implemented) and with the voices in many language (so could be a all round soluzion sport for all languages). It's just a pain to go trough the site with all poup-up and ads so implement this one in the app would be pretty awesome :)

### Other details

The site is https://starlive.xyz to implement in the multilanguage repository extension.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
please open the issue on the correct repository. (dont ask for providers here)
