### ISSUE TITLE
WSATools not responding whenever installation attempt is made

### ISSUE THREAD

**Issue by fawnyeo** [recloudstream/cloudstream#937]
### Steps to reproduce

downloaded wsatools and the cloudstream apk from github, and produces an unknown error
![image](https://github.com/recloudstream/cloudstream/assets/102406279/ea6aafc6-801e-4256-adc4-00c4feb73656)
![image](https://github.com/recloudstream/cloudstream/assets/102406279/4f48e648-7161-4470-8290-c733fbc0fd0e)

### Expected behavior

successful installation

### Actual behavior

unknown error

### Cloudstream version and commit hash

latest release

### Android version

windows subsystem for android idk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
This seems to be an issue with WSATools
