### ISSUE TITLE
Time4tv

### ISSUE THREAD

**Issue by TLAflash** [recloudstream/cloudstream#942]
### Steps to reproduce

![Screenshot_2024-02-19-20-55-14-27_cfa2fd239c8cded9285432912d0e0818](https://github.com/recloudstream/cloudstream/assets/160544722/f1788fee-7937-48cd-8e25-252197915b76)

### Expected behavior

Run the stream

### Actual behavior

Backing out no streaming 

### Cloudstream version and commit hash

4.3.0

### Android version

Oxygen 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
This is not the right repo to create a provider issue at
