### ISSUE TITLE
Hide unwanted buttons

### ISSUE THREAD

**Issue by M-BOUAB** [recloudstream/cloudstream#943]
### Describe your suggested feature

I don't understand how nobody asked for this feature before, but it would be really nice if we could just hide some of the UI buttons we don't want. this way, everyone will have the app customized to its needs.
Something like YouTube revanced extended where you can hide any unwanted navbar buttons.
Everything in the app is useful for most people except for the library button & the providers button in the bottom right corner of the home screen, which some people would like hidden
Thanks 🙏

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Nope, wont be added
