### ISSUE TITLE
Keep screen active

### ISSUE THREAD

**Issue by AnyoneMouse** [recloudstream/cloudstream#947]
### Describe your suggested feature

I have 1 minute "screen timeout" set in my system setting. Because of that sometimes when I leave the phone while keeping a video paused screen gets locked. But I'd like it to stay active in those times.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
It is literally designed that way, and it wont change https://github.com/recloudstream/cloudstream/blob/93d81ea038ca3decc15b97d582c09eb8e4303c31/app/src/main/java/com/lagradost/cloudstream3/ui/player/AbstractPlayerFragment.kt#L150
