### ISSUE TITLE
search is not working properly

### ISSUE THREAD

**Issue by salman731** [recloudstream/cloudstream#951]
### Steps to reproduce

I have selected Movies and TV series from search tab screen but when I select anime then app search functionality does not working properly

https://github.com/recloudstream/cloudstream/assets/25194088/fa443b3e-292f-460a-abf7-c37619c0a972

### Expected behavior

search should be work according to categories i.e Movies, TV Series etc

### Actual behavior

search not working properly on changing category.

### Cloudstream version and commit hash

Pre-release  93d81ea

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
The search functionality is not broken, it filters the extensions themself and not the search results
