### ISSUE TITLE
EPISODE SEARCH

### ISSUE THREAD

**Issue by darkwaters-coder** [recloudstream/cloudstream#960]
### Describe your suggested feature

when using the livestream extension ,there is a section for soccer ,when you click on it there's many matches displayed so if you could add an option to search for  a match it will be good ,i know there's a select option but if you don't know the time the match starts you will have hard time looking for it so PLEASE MAKE IT WORK

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by C10udburst** [comment]
Please do not report issues regarding extensions here, this is only for the app itself

**Comment by RokeJulianLockhart** [comment]
> https://github.com/recloudstream/cloudstream/issues/960#issuecomment-2204365007

@C10udburst, since this explicitly requests a way to search "matches" - which presumably necessitates a special interaction which is the purview of the extension - is there no merit to the more broad request of a way to search for specific episodes?
