### ISSUE TITLE
Suggestion to use a different icon for library

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#962]
### Describe your suggested feature

I end up getting library confused with account quite often. I suggest using a different icon, such as a folder icon or something.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by KingLucius** [comment]
Library needs many improvements actually, i plan to reconstruct library ui (on TV) maybe by then we can suggest which fits better

**Comment by fire-light42** [comment]
Ye a folder icon might fit better
