### ISSUE TITLE
Auto Update watch progress not working 

### ISSUE THREAD

**Issue by Krishna-art-dev** [recloudstream/cloudstream#963]
### Steps to reproduce

1. Add any sync account
2. Check if the movie server support sync or not 
3. Watch any anime or movie fully
4. And check update progress 

### Expected behavior

It should update episode progress or movie watched progress on sync account automatically 

### Actual behavior

Doesn't automatically sync watch progress 

### Cloudstream version and commit hash

4.3.1  809a385

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Plewu** [comment]
so whats solution to this bug ? have the same problem

**Comment by Krishna-art-dev** [comment]
> so whats solution to this bug ? have the same problem

Check that source support auto update or not 
Cloudstream needs like 85% watch progress to update anime automatically 
Don't use skip outro, filler in the end, if video get 85% watch progress on anime it will automatically update that 

And sometimes anilist server down, for me I opened this issue because I didn't watch 85% of the anime, because filler and outro, I skipped it and it doesn't update that
