### ISSUE TITLE
Issues with biometric authentication (or rather when it is disabled)

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#969]
### Steps to reproduce

When I turn *off* biometric authentication I still get this which is meaningless if it is being turned *off*:
![Screenshot_20240307_220920_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/142361265/2fc6d105-8c7c-417b-ae6a-6adb9fc93ab8)

I see this everytime I open the app, even if it is not enabled at all in CloudStream:
![Screenshot_20240307_220827_CloudStream Beta](https://github.com/recloudstream/cloudstream/assets/142361265/32a6fb8a-8ebf-4517-b955-510c02c25339)

Also this should not say "fingerprint" as there are other types of biometric authentication.

It also shows the "Logged in with" toast before you actually complete login with biometric if enabled, it should wait to show that for the login to actually be completed.

### Expected behavior

...

### Actual behavior

...

### Cloudstream version and commit hash

4.3.1 bd69054

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
I'm going to ping @IndusAryan here as the one who worked on biometric auth to begin with. I personally only like it to work for default account anyway since we can't have a PIN there, I don't find it necessary for other accounts and seems a bit overkill but it's fine and at least provides a bit of extra nice security, so thanks for that...

**Comment by IndusAryan** [comment]
1. the warning appearing twice + backup has been solved.

2. the toast has been removed , not needed anywasys because the prompt only appears when certain conditions are met, if there is no lock then no matter setting is on, it remains a dummy setting.

3. the logged in with $accountName wont be solved because we are not freezing any activity of the app, we are just hinding it for reasons otherwise app open will be slowed by about 4 seconds.

**Comment by Luna712** [comment]
@IndusAryan also I found another a major issue I think, adding biometric_key to nonTransferableKeys wont stop it from backing up IIRC, nonTransferableKeys has no actual affect, it was supposed to be fixed with #623 but that seems dead at this point? https://github.com/recloudstream/cloudstream/issues/744#issuecomment-1789466340 — but I guess maybe we should just apply that fix anyway if that isn't progressing anymore?

**Comment by IndusAryan** [comment]
oh, then you should pr, even if it is not dead , it will take months

**Comment by Luna712** [comment]
> oh, then you should pr, even if it is not dead , it will take months

@IndusAryan 

I'll PR that specific fix within the next couple days I guess. Hopefully tomorrow.
