### ISSUE TITLE
Extension update notification toggle

### ISSUE THREAD

**Issue by M-BOUAB** [recloudstream/cloudstream#972]
### Describe your suggested feature

Hy wssup GGGs
I know I won't get an answer until a week from now, but can you please add a settings toggle to switch off extensions updates notifications? I use megarepo & I get bombarded by notifications from Arabic providers repository (it has some bug that makes me get update notifications each time I open the app) so to get rid of this, a toggle would help.
If you think it's a good idea, please add it?
Thank you :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Blatzar** [comment]
There is already a notification channel called "Extensions", which you can turn off.
If one repository is bugged then I'd suggest you remove it and re-add it, that might fix the issue, if not please make a detailed issue about which extension in what repository and it can be checked.

![image](https://github.com/recloudstream/cloudstream/assets/46196380/5a876f9f-5722-4998-af72-d6e12d058e38)

**Comment by M-BOUAB** [comment]
![Screenshot_2024-03-08-18-25-02-525_com lagradost cloudstream3 prerelease](https://github.com/recloudstream/cloudstream/assets/101053017/4e046cdb-b673-4358-a70c-9fc943581bfc)
Oh okay, I've never modified the notifications settings of an app from the android apps notifications menu. I just checked it out & as expected, it solved the problem. Although adding a toggle inside the providers settings or below the extensions menu in the updates & backups settings would be more UX friendly for most of the users in my opinion, so if it's a 10 mins work, you can add it or close the issue if it's not
Thank you ❤️

**Comment by Blatzar** [comment]
Better UX? Arguably yes.
But sadly its not 10m of work, especially counting the extra time to translate the nessecary strings for all languages. 
Also there is the issue of bloating the settings tab with things which can already be found elsewhere, there is already too many settings.

**Comment by M-BOUAB** [comment]
Got it, so it not worth it then. I'm closing this.
But please, just for future updates, if you're trying to avoid bloating the settings tab with too many settings, a good solution would be to add an advanced settings tab for devs & nerds who like to check & modify all the settings, or just a hold click on the settings button or home button to enter the advanced settings menu.
This way, devs who wants more control are happy, & simple people who want an easy to use settings menu are also happy.
Better than avoiding the addition of new settings toggles altogether just to keep the menu clean.
Thanks again 🤝
