### ISSUE TITLE
OOM when restoring data from backup

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#974]
### Steps to reproduce

Restore a backup file

### Expected behavior

Data should be restored

### Actual behavior

OOM is received, throwing the app into safemode:
![Screenshot_20240308_131912_CloudStream Debug](https://github.com/recloudstream/cloudstream/assets/142361265/3d3b2894-b7f7-4b09-a6aa-bc716fe433bc)

### Cloudstream version and commit hash

4.3.1 bd69054

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
![napoleon-there-is-nothing-we-can-do](https://github.com/recloudstream/cloudstream/assets/147925818/d91366d0-8dae-45b3-8624-f344d88cda8a)

**Comment by Luna712** [comment]
OOMs are always the worst in any sort of development so I kinda figured it may not be fixable, but thought I'd open this incase something could be done to improve the performance of backup restoration.

**Comment by Luna712** [comment]
@fire-light42 feel free to close this if you don't think there is anything that can be done to improve this.

**Comment by fire-light42** [comment]
After testing the issue has been found, this will be closed in eta 10min

**Comment by fire-light42** [comment]
https://github.com/recloudstream/cloudstream/commit/527046766a6d855157619d4bfbe737b11def9b62

**Comment by fire-light42** [comment]
#623 does not fix the issue, nor was the issue the size of the data like "plots". The issue was that calling apply after every key is "correct", but when doing 10000000 keys caused a major memory spike as it has to "atomically performs the requested modifications", meaning that is probs had to read the entire database or smth.

**Comment by Luna712** [comment]
> #623 does not fix the issue, nor was the issue the size of the data like "plots". The issue was that calling apply after every key is "correct", but when doing 10000000 keys caused a major memory spike as it has to "atomically performs the requested modifications", meaning that is probs had to read the entire database or smth.

Oh that makes a ton of sense... thanks!

**Comment by Luna712** [comment]
That's amazing... so much faster restore also, almost does it instantly now... Thanks a ton for that fix!
