### ISSUE TITLE
Bugs on new TV UI

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#975]
### Steps to reproduce

1. Open a series
2. Go to recommended and click a new series
3. Click the back button to go back to previous series

### Expected behavior

Should show the same buttons as originally

### Actual behavior

It now shows two S1:E1 buttons as well as the Play Movie button:
![image](https://github.com/recloudstream/cloudstream/assets/142361265/d293568f-dcc6-40a8-9416-721b497b5803)

### Cloudstream version and commit hash

4.3.1 510d11f

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
There is also another issue where this random 0 appears sometimes:
![image](https://github.com/recloudstream/cloudstream/assets/142361265/daded05f-8116-446c-b863-2d771eed49fa)

**Comment by KingLucius** [comment]
Confirmed, working on it
Thanks for reporting

**Comment by Luna712** [comment]
> Confirmed, working on it Thanks for reporting

@KingLucius 

Thanks! And I appreciate all the work you've done on this UI! Looks great!

**Comment by KingLucius** [comment]
> There is also another issue where this random 0 appears sometimes:
> ![image](https://github.com/recloudstream/cloudstream/assets/142361265/daded05f-8116-446c-b863-2d771eed49fa)
> 

Can you please try to reproduce this, it is my first time to see this.

**Comment by Luna712** [comment]
> > There is also another issue where this random 0 appears sometimes:
> > ![image](https://private-user-images.githubusercontent.com/142361265/311462361-daded05f-8116-446c-b863-2d771eed49fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMTIxODUsIm5iZiI6MTcxMDAxMTg4NSwicGF0aCI6Ii8xNDIzNjEyNjUvMzExNDYyMzYxLWRhZGVkMDVmLTgxMTYtNDQ2Yy1iODYzLTJkNzcxZWVkNDlmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQxOTE4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjk0ZjM2ZjhlZjNkNTUwM2FjNjQyZjIyNzdhZWE2MzBhMTE1NTNlYzgwZjIwZTY2OGQ5YzM3NGNmZTU4ODVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UV5n73CNJT4dT6amg9dg1JPU4z0_tMVrDm5WG4nT_8Y)
> 
> Can you please try to reproduce this, it is my first time to see this.

@KingLucius 

![image](https://github.com/recloudstream/cloudstream/assets/142361265/8c8c1325-c168-4e05-a6a0-18b4a29177f4)
Clicked on a random movie in my home page and ended up in here just testing things and noticed it, don't know if it is a one off but for this one in particular happens every time.

**Comment by Luna712** [comment]
@KingLucius it seems that 0 may not be related to this UI actually it seems to happen on phone also, it may be a provider issue, or maybe it can be fixed in CS, but it seems it may be unrelated.

**Comment by KingLucius** [comment]
> @KingLucius it seems that 0 may not be related to this UI actually it seems to happen on phone also, it may be a provider issue, or maybe it can be fixed in CS, but it seems it may be unrelated.

I think there is one of the meta data doesn't hide correctly and instead it shows 0 string

**Comment by Luna712** [comment]
Yeah that is what I was thinking also. I just am not able to debug which one myself right now.

**Comment by KingLucius** [comment]
I will check it

**Comment by KingLucius** [comment]
Fixed in #983 , thanks for reporting
