### ISSUE TITLE
Microsoft stopped supporting WSA, any plans for desktop version?

### ISSUE THREAD

**Issue by jackuars7** [recloudstream/cloudstream#976]
### Describe your suggested feature

It would be amazing if you guys could develop a desktop version for Windows as Microsoft has now stopped supporting WSA and therefore we are unable to run APK's on Windows. I don't want to resort to using emulators. 

Has the team considered making Cloudstream available for Windows? 

### Other details

Microsoft stopped supporting WSA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
This will almost certainly not happen. I use BlueStacks emulator for it, which works fine, other than that I don't think they will ever make a desktop app for it.

**Comment by fire-light42** [comment]
Out of scope atm
