### ISSUE TITLE
DNS is not working

### ISSUE THREAD

**Issue by salman731** [recloudstream/cloudstream#977]
### Steps to reproduce

select provider(blocked) from home screen

### Expected behavior

It should load site content because when I use cloudflare android app dns then it works.

### Actual behavior

Unable to load websites which are blocked in my country

### Cloudstream version and commit hash

4.3.1 - 510d11f

### Android version

Android 11

### Other details

Check Out This = > https://stackoverflow.com/questions/65420610/how-to-implement-a-custom-dns-for-okhttp3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Custom DNS already exist

**Comment by salman731** [comment]
You have update it 
https://stackoverflow.com/questions/65420610/how-to-implement-a-custom-dns-for-okhttp3
