### ISSUE TITLE
Android TV Video lagging 

### ISSUE THREAD

**Issue by Xchiii21** [recloudstream/cloudstream#98]
### Steps to reproduce

When you play video on certain sites like sflix.to it lags

### Expected behavior

Video should run smoothly 

### Actual behavior

It stutters

### Cloudstream version and commit hash

3.1.5 - 1db1baef

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by Xchiii21** [comment]
On other providers it doesn't lag

**Comment by Blatzar** [comment]
This sounds like a video host issue. Their servers are simply too weak to deliver the content to your network with sufficient speeds. We do not control the video servers at all and cannot fix this.
