### ISSUE TITLE
Consider adding country select (optional) to initial setup and settings

### ISSUE THREAD

**Issue by Luna712** [recloudstream/cloudstream#980]
### Describe your suggested feature

I was thinking something like https://github.com/hbb20/AndroidCountryPicker. My thoughts is that we could then use it for some local personalization, such as getting content ratings for their particular country.

### Other details

I'm not sure if this is really a good idea or something you'd want in the app, so if not feel free to close it. I'm just creating this as I think personalization based on country could be quite helpful as well. I say it should be optional because their should be no obligation to select any country.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
👎 I really dont want to bloat setup, and atm localization is not used anywhere

**Comment by Luna712** [comment]
> 👎 I really dont want to bloat setup, and atm localization is not used anywhere

@fire-light42 

I mostly wanted to know if this is even something you'd accept, I planned to do a patch for it to support this and use it for things like filter content based on country (this part is a little more difficult but I think it could probably be done), and support getting content rating based off country, etc...

But if you don't think it's something that should be done I didn't want to waste my time working on it, in that case this can just be closed. Thanks!

**Comment by fire-light42** [comment]
If an extension supports that, then it should be placed in the extension settings

**Comment by Luna712** [comment]
> If an extension supports that, then it should be placed in the extension settings

@fire-light42 

Oh extension settings... that is a good idea... I forgot about extension settings, and just remembered the whole reason I made it possible to provide any country code in fetchContenrRatings when I added that support was for this exact thing, to allow extensions making this extension settings. So please ignore me, as I guess I forget things I do myself...
