### ISSUE TITLE
New episodes in continue watching 

### ISSUE THREAD

**Issue by pathania07** [recloudstream/cloudstream#981]
### Describe your suggested feature

If there is a new episode of an anime or web series. It automatically shows at the continue watching tab. It will be helpful as you don't have to search it again or go look for it in the library.
Ps: sorry if my English is bad 
And thanks for the wonderful app

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Was talked about in #950 and tldr: it is not possible atm because of reasons
