### ISSUE TITLE
SuperStream Not Casting, Works When Not Trying To Cast

### ISSUE THREAD

**Issue by aplegs** [recloudstream/cloudstream#982]
### Steps to reproduce

1. Open Any Title in the SuperStream extension.
2. Press Cast Button
3. Press episode or movie to play it

### Expected behavior

Should cast the selected media

### Actual behavior

Nothing happens.

### Cloudstream version and commit hash

4.3.1 2b7d102

### Android version

Android 12

### Other details

When I normally open something in Superstream it works, but after I put it in cast mode the extension doesn't work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by aplegs** [comment]
Just updated to version 4.3.1 81df68e and the issue persists

**Comment by JimZiii** [comment]
I just tried casting from superstream and its working just fine. Tried casting both to chromecast through the CS app and with web video caster.
Have you tried it recently and have you tried casting from something else to see if it's actually CS that's the issue

**Comment by C10udburst** [comment]
Please do not report any provider bugs here. This repository does not contain any providers. Please find the appropriate repository and report your issue there or join the [discord](https://discord.gg/5Hus6fM).
