### ISSUE TITLE
Automatically open most used account on startup 

### ISSUE THREAD

**Issue by AnyoneMouse** [recloudstream/cloudstream#984]
### Describe your suggested feature

Don't make it default. Add another option for this along with "Skip account selection at startup".

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Luna712** [comment]
If you enable "Skip account selection at startup" it will use the most *recently* used account. I am not sure if it's even really possible to track the most *used* account...

**Comment by Luna712** [comment]
I'm actually not sure why this would even be necessary, it could just be an option to select the default startup account (manually selecting the most used account) but I don't think it'll happen, personally I don't like it as I feel it is an unnecessary setting that would just bloat settings a bit.

**Comment by Luna712** [comment]
That would personally be my preference

**Comment by Luna712** [comment]
That this be closed as I don't think its necessary or for that matter I'm not sure it's possible, but it's just a suggestion.
