### ISSUE TITLE
Multi Audio Stream Link not opening 

### ISSUE THREAD

**Issue by rusunny123** [recloudstream/cloudstream#985]
### Steps to reproduce

1) Open The App
2) Go to Downloads Section
3 ) Click Stream Button and paste a multi stream download link ( example: https://m.sunnys.workers.dev/1:/TheGdriveXbot/John%20Wick:%20Chapter%204%20(2023)%20720p%2010bit%20ITunes%20WEBRip%20x265%20HEVC%20[Org%20Itunes%20Hindi%20HE-AAC%205.1%20~%20256Kbps%20+%20English%20AAC%205.1]%20ESub%20~%20PSA.mkv )

4) start playing 

### Expected behavior

It should play with multiple audio & able to select Audio from player " tracks" button 

### Actual behavior

showing a error message 

### Cloudstream version and commit hash

latest Version 

### Android version

Android 9

### Other details

Fix this problem sir

" Respect 🤝 to the creator of this app & thanks for contribution"

also add some Features

1) Two fingers zoom like MXplayer
2) Play with extenal player ( currently app allows only VLC and mpv player only )
3) make the app access storage video and act as a video player

Have a nice day sir 💚🧡❤️

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
While you did not provide enough information, I assume the error is "NO_EXCEEDS_CAPABILITIES" and that is because your hardware does not support it. If this is the issue then take it up with androidx.media not this repo. 

But yes, cs3 does support multi audio tracks.

**Comment by rusunny123** [comment]
![Screenshot_20240314-092113](https://github.com/recloudstream/cloudstream/assets/73994046/ab059437-9190-4b96-b622-5ac142235e66)

this is exactly what error I'm getting

**Comment by rusunny123** [comment]
Sir i tested Redmi Note 12 & Realme 9i with the latest version of Cloud Stream app (4.3.0 & 4.3.1_PRE)

having same issues again... **encoding error** 


i will post a video of the problem when my WiFi returns

thanks again
Have a nice day

**Comment by rusunny123** [comment]
![IMG_20240314_130147_324](https://github.com/recloudstream/cloudstream/assets/73994046/cc0367ab-f744-470e-8ef8-d06e63aa2897)


here
