### ISSUE TITLE
None of the movies from 2022- present time is working in Superstream

### ISSUE THREAD

**Issue by Rinhak** [recloudstream/cloudstream#989]
### Steps to reproduce

1. Choose Superstream as your provider.
2. Select any movie fo 2022, 2023 or 2024, example I choose Avatar way of Water, Oppenheimer.
3. It shows 'no links found'.

### Expected behavior

All the movies should be streaming.

### Actual behavior

None of the movies after October 2022 are streaming properly. Superstream is the only link working properly. I was using Sorastream but it has stopped working completely. Please kindly look into it.

### Cloudstream version and commit hash

4.2.1 4817b29

### Android version

Android 14

### Logcat

```java
Shows error copying.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by fire-light42** [comment]
Create that issue on the repository hosting that extention, not this repo. This repo is for the app only.
