### ISSUE TITLE
Can't hide player UI by hitting back button anymore.

### ISSUE THREAD

**Issue by MarshMeadow** [recloudstream/cloudstream#992]
### Steps to reproduce

For an easy to reproduce way to see this issue:
1. Play a video using the internal player.
2. Pause the video. (The player UI appears in front of the [paused] video.)
3. Press the back button.

### Expected behavior

The player UI should disappear, leaving the video visible.

### Actual behavior

The player is closes, and you can't see the video anymore.

### Cloudstream version and commit hash

a3bb853691aa84dd89fc14f37bc8d174ded0b7c3

### Android version

Android TV 9

### Other details

The text in this post was not written by me. I'm posting it on behalf of someone who is having GitHub account troubles right now,  but I would also like to have this problem fixed.

There are times when I watch subtitled content, where a subtitle disappears too fast for me to read it, so I back up and rewatch up to that segment of the video, and pause when the subtitle is on screen again. At this point, want to be able to read the subtitle while the video is paused, but the player UI is in the way, so until the last beta update I would hit the back button to hide the player UI, read the subtitle, then continue playing the video. Now, hitting the back button immediately closes the player. I find this very frustrating. Please bring back the ability to hide the player UI by pressing the back button without closing the player.

FYI: I'm using this on an Android TV based set top box.  Occasionally CloudStream doesn't hide the player UI automatically while a video plays, but this has never bothered me before because I could simply hit the back button to manually hide it without interrupting the video. Without the ability to hide the player UI with the back button, this becomes a much bigger problem.
Also, the version I was using before I updated earlier today, which did not have this issue (by which I mean it did allow for hiding the player UI with the back button was 510d11f705b5c112773a2d6f31d7a1c64d20a713, the change that caused this issue must have occurred between 510d11f705b5c112773a2d6f31d7a1c64d20a713 and a3bb853691aa84dd89fc14f37bc8d174ded0b7c3.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

**Comment by LagradOst** [comment]
Should be fixed
